### ISSUE TITLE
aes.c: "error: control reaches end of non-void function"

### ISSUE THREAD

**Issue by gonzzor** [wolfSSL/wolfssl#1126]
https://github.com/wolfSSL/wolfssl/blob/34dc4a493d64160d6d87a5cfbd7c0ca803fce68a/wolfcrypt/src/aes.c#L3148

Building with STM32F2 and stdperih lib.

**Comment by dgarske** [comment]
Hi Gonzzor,

Thanks for the these AES STM32F2 StdPeriLib reports. I'm working on fixes these and should have a PR released soon.

Thanks, David Garske

**Comment by dgarske** [comment]
Fixes for STM32F2/F4 StdPeriLib have been pushed to PR #1116 and passed our wolfCrypt tests. 

Please let me know if you have any issues. Thanks, David Garske, wolfSSL.
