### ISSUE TITLE
Converting application from openssl to wolfssl

### ISSUE THREAD

**Issue by PiedPieper** [wolfSSL/wolfssl#1134]
Hello, 

I have been reading your documentation here : https://www.wolfssl.com/wolfSSL/Docs-wolfssl-manual-13-openssl-compatibility.html and I am trying to use it to convert my application from WolfSSL due to size constraints. 

The first thing I did is replace all of the calls to #include <openssl/**> with <wolfssl/openssl/**>. From here, I get a bunch of warnings telling me : 
```
"#warning "TLS-PSK not supported, openssl too old." [-Wcpp]
 #    warning "TLS-PSK not supported, openssl too old."
```
When I compiled wolfssl, I compiled with the flags `"./configure --enable-ecc --enable-psk --enable-aesccm C_EXTRA_FLAGS="-DWOLFSSL_STATIC_PSK" ` so I don't think I should be getting this warning.

Secondly, I am getting implicit declarations of many wolfssl functions, for example :
```
 "warning: implicit declaration of function ‘sk_GENERAL_NAME_value’ [-Wimplicit-function-declaration]
    nval = sk_GENERAL_NAME_value(san, i);"
```

However, in your forum, it says that you included this feature: https://www.wolfssl.com/forums/topic238-how-to-parse-alt-names-with-wolfssl.html

is this not included in the standard distribution/are there configure flags I need to support this?
Why am I getting the psk warnings when I added them through ./configure?

**Comment by dgarske** [comment]
Hi PiedPieper,

I don't recognize that warning message for our library, which indicates you are probably including openssl stuff still.

You can implement our compatibility layer without changing your code. To do so you'll want to:

1. Change your compiler include path `-Iwolfssl -Iwolfssl/wolfssl`. This includes the wolfssl root and the wolfssl/wolfssl header folder.
2. Change your library to use `-lwolfssl`.

Also when build the wolfssl library to include the openssl compatibility layer you'll need to add the `--enable-opensslextra` option. To see a list of options you can use `./configure --help`.

Thanks,
David Garske, wolfSSL
