### ISSUE TITLE
[INVALID] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [wolfSSL/wolfssl#1182]
Dear WolfSSL team,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by sergeevabc** [comment]
Oh, there is no executable (similar to OpenSSL or  LibreSSL), just a library. Wrong request then.

**Comment by CristiFati** [comment]
@sergeevabc: You can take a look at https://github.com/CristiFati/Prebuilt-Binaries/tree/master/WolfSSL.
