### ISSUE TITLE
Remove use of CyaSSL_Mutex in wolfcrypt

### ISSUE THREAD

**Issue by aburks** [wolfSSL/wolfssl#12]
There are a few vestigial uses of CyaSSL_Mutex in wolfcrypt:

AES: https://github.com/wolfSSL/wolfssl/blob/master/wolfcrypt/src/aes.c#L1438
ECC: https://github.com/wolfSSL/wolfssl/blob/master/wolfcrypt/src/ecc.c#L2653

**Comment by toddouska** [comment]
Thanks!  Good finds.
