### ISSUE TITLE
Missing hashHandle in wc_Sha for STM32

### ISSUE THREAD

**Issue by liubing** [wolfSSL/wolfssl#1213]
The following definition is missing from wc_Sha:
`#if defined(STM32_HASH) && defined(WOLFSSL_STM32_CUBEMX)`
`    HASH_HandleTypeDef hashHandle;`
`#endif`

wc_Md5 doesn't have this problem.

**Comment by dgarske** [comment]
Fixed in PR #1215. Thanks for the report.
