### ISSUE TITLE
wc_AesCbcEncryptWithKey The result is wrong

### ISSUE THREAD

**Issue by zero-rp** [wolfSSL/wolfssl#1225]
wolfssl:
    char iv[] = { 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f };
    char aes_key[] = { 0x00, 0x01, 0x02, 0x03,0x04, 0x05, 0x06, 0x07,0x08, 0x09, 0x0a, 0x0b,0x0c, 0x0d, 0x0e, 0x0f,
        0x10, 0x11, 0x12, 0x13,0x14, 0x15, 0x16, 0x17,0x18, 0x19, 0x1a, 0x1b,0x1c, 0x1d, 0x1e, 0x1f };

    char s[] = { 0x00, 0x01, 0x02, 0x03,0x04, 0x05, 0x06, 0x07,0x08, 0x09, 0x0a, 0x0b,0x0c, 0x0d, 0x0e, 0x0f,
        0x10, 0x11, 0x12, 0x13,0x14, 0x15, 0x16, 0x17,0x18, 0x19, 0x1a, 0x1b,0x1c, 0x1d, 0x1e, 0x1f };
    char o[100] = { 0 };
    wc_AesCbcEncryptWithKey(o, s, 32, aes_key, 32, iv);

openssl:

     AES_KEY aes;
    if (AES_set_encrypt_key(aes_key, 128, &aes) < 0)
        return;
    AES_cbc_encrypt((unsigned char*)s, (unsigned char*)o, 32, &aes, iv, AES_ENCRYPT);

Output of openssl:

```
c6 a1 3b 37 87 8f 5b 82 6f 4f 81 62 a1 c8 d8 79 35 d9 dc db 82 9f ec 33 52 e7 bf 10 b8 4b e4 a5
```

Output of wolfssl:

```
f2 90 00 b6 2a 49 9f d0 a9 f3 9a 6a dd 2e 77 80 95 43 b8 6f c0 46 fa 88 3a 94 46 b8 2e 47 d1 2d
```

**Comment by JacobBarthelmeh** [comment]
Hi zero-rp,

Thanks for sending across the calls it was helpful for debugging. The issue looks to be a difference in key sizes used in OpenSSL vs wolfSSL. To get a matching output use 256 (bit) as the input parameter to AES_set_encrypt_key or use a key size of 16 (bytes) as the input to wc_AesCbcEncryptWithKey.

Regards,
Jacob
