### ISSUE TITLE
FREERTOS define does not allow XMALLOC_USER

### ISSUE THREAD

**Issue by aburks** [wolfSSL/wolfssl#130]
I cannot override the memory functions with the `XMALLOC_USER` define if `FREERTOS` is defined. The build will fail in settings.h around line 325.

**Comment by kaleb-himes** [comment]
Hi Aburks,

Which version of wolfSSL were you using? Was line 325 at the time of this issue the #ifdef FREERTOS?

Regards,

Kaleb

**Comment by aburks** [comment]
This was version 3.6.6 at commit 5ce39e147d681ba9deeb0172d190562eef223ffe.

**Comment by aburks** [comment]
This also causes problems with `NO_WOLFSSL_MEMORY`. We removed our `XMALLOC_USER` code because these defines were added but then couldn't build because `XMALLOC` was redefined at line 177 of types.h.

**Comment by aburks** [comment]
Additionally the FreeRTOS version of `XMALLOC` doesn't use the types, which causes build errors with -Wall turned on.

**Comment by kaleb-himes** [comment]
Hi Aburks,

Thank you. I will try to get this fixed as soon as possible. Were you able to move forward with your project?

Regards,

Kaleb

**Comment by aburks** [comment]
Thanks. We were able to move forward by forking and fixing it ourselves :disappointed:

**Comment by kaleb-himes** [comment]
Hi Aburks,

I see. I apologize I did not get to this sooner for you.

I see you have contributed to our repository in the past, and you are the first to have implemented your own custom allocators when building with FREERTOS.

If you have a .patch file, could explain how you fixed the issue, or simply open a pull request on your branch, we would be happy to review them and see if it is something we can support going forward.

Kind Regards,

Kaleb

**Comment by kaleb-himes** [comment]
Hi Aburks,

I was able to register my own callbacks for XMALLOC and XFREE with the changes made in the commit above. Were there any other conflicts that you observed and I am not aware of in regards to XMALLOC_USER and NO_WOLFSSL_MEMORY?


Regards,

Kaleb

**Comment by kaleb-himes** [comment]
Fixed as of commit 67e08e48c51ade64c865531649297bc08daf4b7c. Feel free to open another issue if there is anything further.

Regards,

Kaleb
