### ISSUE TITLE
Using Python with DTLS

### ISSUE THREAD

**Issue by catchmeajay1** [wolfSSL/wolfssl#143]
Hi,

Is there a python swig component for DTLS. Could find only a TLS one. If there is one for DTLS, kindly let know.

Thanks.
Ajay

**Comment by cconlon** [comment]
Hi Ajay,

We don't currently have DTLS support in the Python SWIG wrapper we currently have.  You can find the existing SWIG Python wrapper under the <wolfssl_root>/swig directory.

Best Regards,
Chris
