### ISSUE TITLE
README content too long

### ISSUE THREAD

**Issue by ibakirov** [wolfSSL/wolfssl#1465]
README content consist of information about project, changelogs and building options. Changelogs takes most of document and makes huge document which is hard to read. I propose to take out changelog information from README documents into corresponding Changelog document.

**Comment by kaleb-himes** [comment]
Hi @ibakirov,

Thank you Kindly for your suggestion and feature request to reduce the README size by moving release notes to the Changelog. We are evaluating the request internally.

Warm Regards,

K
