### ISSUE TITLE
pkcs7.c Build errors when NO_RSA is defined 

### ISSUE THREAD

**Issue by hajjihraf** [wolfSSL/wolfssl#1472]
Conditions to reproduce:
define macros:
HAVE_PKCS7
NO_RSA
HAVE_ECC

**Comment by dgarske** [comment]
Hi hajjihraf,

We went ahead and issued a pull request #1473 to resolve that. Previously that scenario was not supported:

```
./configure --enable-pkcs7 --disable-rsa --enable-ecc && make
configure: error: please enable rsa if enabling pkcs7.
```

With this PR a subset of PKCS7 is supported with just ECC enabled.

Let us know how this works for you.

Thanks,
David Garske, wolfSSL

**Comment by hajjihraf** [comment]
Hi David,

Thanks for the quick fix, it works for me.

Best Regards,
Achraf
