### ISSUE TITLE
Latest stable version?

### ISSUE THREAD

**Issue by ilovezfs** [wolfSSL/wolfssl#1513]
Are the non-explicit-GitHub-release tags considered releases?

I cannot tell if the latest version is 3.14.0 or 3.14.4
https://github.com/wolfSSL/wolfssl/releases shows 3.14.4 exists
https://github.com/wolfSSL/wolfssl/releases/latest points to 3.14.0 since it's the last explicit GitHub release

**Comment by dgarske** [comment]
Hi ilovezfs,

The official releases are the ones the end with `-stable` and the last one is:
https://github.com/wolfSSL/wolfssl/releases/tag/v3.14.0-stable

The more recent ones are intermediate releases done for specific projects or customers.

Thanks,
David Garske, wolfSSL

**Comment by ilovezfs** [comment]
Thanks!
