### ISSUE TITLE
QNX 6.6 cross compilation error

### ISSUE THREAD

**Issue by dagonzal01** [wolfSSL/wolfssl#1576]
Hi,

I'm tring to crosscompile wolfssl library using Ubuntu as host OS, QNX 6.6 as target OS and with the next compilation options (./configure options):

`./configure CFLAGS=-Os CPPFLAGS=-DWOLFSSL_HAVE_MIN --host=arm-unknown-nto-qnx6.6.0eabi --enable-opensslextra --enable-fortress --enable-aesgcm --enable-ecc --enable-eccencrypt --enable-tlsx --enable-hkdf --enable-ocsp --enable-ocspstapling --enable-ocspstapling2 --enable-sessioncerts --enable-cmac --enable-keygen --enable-testcert --enable-certgen`

However the compilation fails. I downloaded a copy of the master branch with [https://github.com/wolfSSL/wolfssl/commit/be9ae9a3c45ff692eac264ecf95fc50139a38f97](url) as latest commit.

Log:

damian@damian-VirtualBox:~/shared_with_windows/wolfssl-3.14.0$ ./configure CFLAGS=-Os CPPFLAGS=-DWOLFSSL_HAVE_MIN --host=arm-unknown-nto-qnx6.6.0eabi --enable-opensslextra --enable-fortress --enable-aesgcm --enable-ecc --enable-eccencrypt --enable-tlsx --enable-hkdf --enable-ocsp --enable-ocspstapling --enable-ocspstapling2 --enable-sessioncerts --enable-cmac --enable-keygen --enable-testcert --enable-certgen
checking build system type... x86_64-unknown-linux-gnu
checking host system type... arm-unknown-nto-qnx6.6.0eabi
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for arm-unknown-nto-qnx6.6.0eabi-strip... arm-unknown-nto-qnx6.6.0eabi-strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '1000' is supported by ustar format... yes
checking whether GID '1000' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking how to print strings... printf
checking for style of include used by make... GNU
checking for arm-unknown-nto-qnx6.6.0eabi-gcc... arm-unknown-nto-qnx6.6.0eabi-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether arm-unknown-nto-qnx6.6.0eabi-gcc accepts -g... yes
checking for arm-unknown-nto-qnx6.6.0eabi-gcc option to accept ISO C89... none needed
checking whether arm-unknown-nto-qnx6.6.0eabi-gcc understands -c and -o together... yes
checking dependency style of arm-unknown-nto-qnx6.6.0eabi-gcc... gcc3
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by arm-unknown-nto-qnx6.6.0eabi-gcc... /home/damian/qnx660/host/linux/x86/usr/bin/arm-unknown-nto-qnx6.6.0eabi-ld
checking if the linker (/home/damian/qnx660/host/linux/x86/usr/bin/arm-unknown-nto-qnx6.6.0eabi-ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /home/damian/qnx660/host/linux/x86/usr/bin/arm-unknown-nto-qnx6.6.0eabi-nm -B
checking the name lister (/home/damian/qnx660/host/linux/x86/usr/bin/arm-unknown-nto-qnx6.6.0eabi-nm -B) interface... BSD nm
checking whether ln -s works... no, using cp -pR
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to arm-unknown-nto-qnx6.6.0eabi format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /home/damian/qnx660/host/linux/x86/usr/bin/arm-unknown-nto-qnx6.6.0eabi-ld option to reload object files... -r
checking for arm-unknown-nto-qnx6.6.0eabi-objdump... arm-unknown-nto-qnx6.6.0eabi-objdump
checking how to recognize dependent libraries... pass_all
checking for arm-unknown-nto-qnx6.6.0eabi-dlltool... no
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for arm-unknown-nto-qnx6.6.0eabi-ar... arm-unknown-nto-qnx6.6.0eabi-ar
checking for archiver @FILE support... @
checking for arm-unknown-nto-qnx6.6.0eabi-strip... (cached) arm-unknown-nto-qnx6.6.0eabi-strip
checking for arm-unknown-nto-qnx6.6.0eabi-ranlib... arm-unknown-nto-qnx6.6.0eabi-ranlib
checking command to parse /home/damian/qnx660/host/linux/x86/usr/bin/arm-unknown-nto-qnx6.6.0eabi-nm -B output from arm-unknown-nto-qnx6.6.0eabi-gcc object... ok
checking for sysroot... no
checking for arm-unknown-nto-qnx6.6.0eabi-mt... no
checking for mt... mt
configure: WARNING: using cross tools not prefixed with host triplet
checking if mt is a manifest tool... no
checking how to run the C preprocessor... arm-unknown-nto-qnx6.6.0eabi-gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if arm-unknown-nto-qnx6.6.0eabi-gcc supports -fno-rtti -fno-exceptions... no
checking for arm-unknown-nto-qnx6.6.0eabi-gcc option to produce PIC... -fPIC -shared -DPIC
checking if arm-unknown-nto-qnx6.6.0eabi-gcc PIC flag -fPIC -shared -DPIC works... yes
checking if arm-unknown-nto-qnx6.6.0eabi-gcc static flag -static works... yes
checking if arm-unknown-nto-qnx6.6.0eabi-gcc supports -c -o file.o... yes
checking if arm-unknown-nto-qnx6.6.0eabi-gcc supports -c -o file.o... (cached) yes
checking whether the arm-unknown-nto-qnx6.6.0eabi-gcc linker (/home/damian/qnx660/host/linux/x86/usr/bin/arm-unknown-nto-qnx6.6.0eabi-ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... ldqnx.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for arm-unknown-nto-qnx6.6.0eabi-g++... arm-unknown-nto-qnx6.6.0eabi-g++
checking whether we are using the GNU C++ compiler... yes
checking whether arm-unknown-nto-qnx6.6.0eabi-g++ accepts -g... yes
checking dependency style of arm-unknown-nto-qnx6.6.0eabi-g++... gcc3
checking how to run the C++ preprocessor... arm-unknown-nto-qnx6.6.0eabi-g++ -E
checking for ld used by arm-unknown-nto-qnx6.6.0eabi-g++... /home/damian/qnx660/host/linux/x86/usr/bin/arm-unknown-nto-qnx6.6.0eabi-ld
checking if the linker (/home/damian/qnx660/host/linux/x86/usr/bin/arm-unknown-nto-qnx6.6.0eabi-ld) is GNU ld... yes
checking whether the arm-unknown-nto-qnx6.6.0eabi-g++ linker (/home/damian/qnx660/host/linux/x86/usr/bin/arm-unknown-nto-qnx6.6.0eabi-ld) supports shared libraries... yes
checking for arm-unknown-nto-qnx6.6.0eabi-g++ option to produce PIC... -fPIC -shared -DPIC
checking if arm-unknown-nto-qnx6.6.0eabi-g++ PIC flag -fPIC -shared -DPIC works... yes
checking if arm-unknown-nto-qnx6.6.0eabi-g++ static flag -static works... yes
checking if arm-unknown-nto-qnx6.6.0eabi-g++ supports -c -o file.o... yes
checking if arm-unknown-nto-qnx6.6.0eabi-g++ supports -c -o file.o... (cached) yes
checking whether the arm-unknown-nto-qnx6.6.0eabi-g++ linker (/home/damian/qnx660/host/linux/x86/usr/bin/arm-unknown-nto-qnx6.6.0eabi-ld) supports shared libraries... yes
checking dynamic linker characteristics... ldqnx.so
checking how to hardcode library paths into programs... immediate
checking whether the -Werror option is usable... yes
checking for simple visibility declarations... yes
checking whether make supports nested variables... (cached) yes
checking size of long long... 8
checking size of long... 4
checking for __uint128_t... no
checking for gethostbyname... no
checking for getaddrinfo... no
checking for gettimeofday... yes
checking for gmtime_r... yes
checking for inet_ntoa... no
checking for memset... yes
checking for socket... no
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking errno.h usability... yes
checking errno.h presence... yes
checking for errno.h... yes
checking for socket in -lnetwork... no
checking whether byte ordering is bigendian... no
checking for arm-unknown-nto-qnx6.6.0eabi-gcc... (cached) arm-unknown-nto-qnx6.6.0eabi-gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether arm-unknown-nto-qnx6.6.0eabi-gcc accepts -g... (cached) yes
checking for arm-unknown-nto-qnx6.6.0eabi-gcc option to accept ISO C89... (cached) none needed
checking whether arm-unknown-nto-qnx6.6.0eabi-gcc understands -c and -o together... (cached) yes
checking dependency style of arm-unknown-nto-qnx6.6.0eabi-gcc... (cached) gcc3
checking whether arm-unknown-nto-qnx6.6.0eabi-gcc and cc understand -c and -o together... yes
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether arm-unknown-nto-qnx6.6.0eabi-g++ accepts -g... (cached) yes
checking dependency style of arm-unknown-nto-qnx6.6.0eabi-g++... (cached) gcc3
checking for size_t... yes
checking for uint8_t... yes
checking dependency style of arm-unknown-nto-qnx6.6.0eabi-gcc... gcc3
checking for cos in -lm... yes
checking for thread local storage (TLS) class... __thread
checking for debug... no
checking whether arm-unknown-nto-qnx6.6.0eabi-gcc is Clang... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking for openssl... yes
checking for fast RSA... no
checking for library containing gethostbyname... no
checking for library containing socket... -lsocket
checking for vcs system... none
checking for vcs checkout... no
checking whether the linker accepts -Werror... yes
checking whether the linker accepts -z relro -z now... yes
checking whether the linker accepts -pie... yes
checking whether C compiler accepts -Werror... yes
checking whether C compiler accepts -Wno-pragmas... yes
checking whether C compiler accepts -Wall... yes
checking whether C compiler accepts -Wno-strict-aliasing... yes
checking whether C compiler accepts -Wextra... yes
checking whether C compiler accepts -Wunknown-pragmas... yes
checking whether C compiler accepts -Wthis-test-should-fail... no
checking whether C compiler accepts --param=ssp-buffer-size=1... yes
checking whether C compiler accepts -Waddress... yes
checking whether C compiler accepts -Warray-bounds... yes
checking whether C compiler accepts -Wbad-function-cast... yes
checking whether C compiler accepts -Wchar-subscripts... yes
checking whether C compiler accepts -Wcomment... yes
checking whether C compiler accepts -Wfloat-equal... yes
checking whether C compiler accepts -Wformat-security... yes
checking whether C compiler accepts -Wformat=2... yes
checking whether C compiler accepts -Wmaybe-uninitialized... yes
checking whether C compiler accepts -Wmissing-field-initializers... yes
checking whether C compiler accepts -Wmissing-noreturn... yes
checking whether C compiler accepts -Wmissing-prototypes... yes
checking whether C compiler accepts -Wnested-externs... yes
checking whether C compiler accepts -Wnormalized=id... yes
checking whether C compiler accepts -Woverride-init... yes
checking whether C compiler accepts -Wpointer-arith... yes
checking whether C compiler accepts -Wpointer-sign... yes
checking whether C compiler accepts -Wredundant-decls... yes
checking whether C compiler accepts -Wshadow... yes
checking whether C compiler accepts -Wshorten-64-to-32... no
checking whether C compiler accepts -Wsign-compare... yes
checking whether C compiler accepts -Wstrict-overflow=1... yes
checking whether C compiler accepts -Wstrict-prototypes... no
checking whether C compiler accepts -Wswitch-enum... yes
checking whether C compiler accepts -Wundef... yes
checking whether C compiler accepts -Wunused... yes
checking whether C compiler accepts -Wunused-result... yes
checking whether C compiler accepts -Wunused-variable... yes
checking whether C compiler accepts -Wwrite-strings... yes
checking whether C compiler accepts -fwrapv... yes
creating wolfssl-config - generic 3.14.0 for -lwolfssl -lsocket
checking the number of available CPUs... 1
configure: adding automake macro support
configure: creating aminclude.am
configure: added jobserver support to make for 2 jobs
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating stamp-h
config.status: creating Makefile
config.status: creating wolfssl/version.h
config.status: creating wolfssl/options.h
config.status: creating support/wolfssl.pc
config.status: creating rpm/spec
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
---
Running make clean...
---
Generating user options header...
option w/o begin -D is -Os, not saving to wolfssl/options.h
option w/o begin -D is -fvisibility=hidden, not saving to wolfssl/options.h
not outputting (N)DEBUG to wolfssl/options.h
option w/o begin -D is -pthread, not saving to wolfssl/options.h
option w/o begin -D is -Wall, not saving to wolfssl/options.h
option w/o begin -D is -Wno-unused, not saving to wolfssl/options.h
option w/o begin -D is -Os, not saving to wolfssl/options.h
option w/o begin -D is -fomit-frame-pointer, not saving to wolfssl/options.h

---
Configuration summary for wolfssl version 3.14.0

   * Installation prefix:        /usr/local
   * System type:                unknown-nto-qnx6.6.0eabi
   * Host CPU:                   arm
   * C Compiler:                 arm-unknown-nto-qnx6.6.0eabi-gcc
   * C Flags:                    -Os -Wno-pragmas -Wall -Wno-strict-aliasing -Wextra -Wunknown-pragmas --param=ssp-buffer-size=1 -Waddress -Warray-bounds -Wbad-function-cast -Wchar-subscripts -Wcomment -Wfloat-equal -Wformat-security -Wformat=2 -Wmaybe-uninitialized -Wmissing-field-initializers -Wmissing-noreturn -Wmissing-prototypes -Wnested-externs -Wnormalized=id -Woverride-init -Wpointer-arith -Wpointer-sign -Wredundant-decls -Wshadow -Wsign-compare -Wstrict-overflow=1 -Wswitch-enum -Wundef -Wunused -Wunused-result -Wunused-variable -Wwrite-strings -fwrapv 
   * C++ Compiler:               arm-unknown-nto-qnx6.6.0eabi-g++
   * C++ Flags:                  
   * CPP Flags:                  -DWOLFSSL_HAVE_MIN -fvisibility=hidden
   * CCAS Flags:                 -Os
   * LIB Flags:                   -pie -z relro -z now 
   * Debug enabled:              no
   * Coverage enabled:           
   * Warnings as failure:        no
   * make -j:                    2
   * VCS checkout:               no

   Features 
   * Single threaded:            no
   * Filesystem:                 yes
   * OpenSSH Build:              no
   * OpenSSL Extra API:          yes
   * OpenSSL Coexist:            no
   * Old Names:                  yes
   * Max Strength Build:         no
   * Distro Build:               no
   * fastmath:                   no
   * Assembly Allowed:           yes
   * sniffer:                    no
   * snifftest:                  no
   * ARC4:                       no
   * AES:                        yes
   * AES-NI:                     no
   * AES-GCM:                    yes
   * AES-CCM:                    no
   * AES-CTR:                    no
   * DES3:                       no
   * IDEA:                       no
   * Camellia:                   no
   * NULL Cipher:                no
   * MD5:                        yes
   * RIPEMD:                     no
   * SHA:                        yes
   * SHA-224:                    no
   * SHA-512:                    yes
   * SHA3:                       no
   * BLAKE2:                     no
   * CMAC:                       yes
   * keygen:                     yes
   * certgen:                    yes
   * certreq:                    no
   * certext:                    no
   * HC-128:                     no
   * RABBIT:                     no
   * CHACHA:                     yes
   * Hash DRBG:                  yes
   * PWDBASED:                   yes
   * scrypt:                     no
   * wolfCrypt Only:             no
   * HKDF:                       yes
   * X9.63 KDF:                  no
   * MD4:                        no
   * PSK:                        no
   * Poly1305:                   yes
   * LEANPSK:                    no
   * LEANTLS:                    no
   * RSA:                        yes
   * RSA-PSS:                    no
   * DSA:                        no
   * DH:                         yes
   * ECC:                        yes
   * CURVE25519:                 no
   * ED25519:                    no
   * FPECC:                      no
   * ECC_ENCRYPT:                yes
   * ASN:                        yes
   * Anonymous cipher:           no
   * CODING:                     yes
   * MEMORY:                     yes
   * I/O POOL:                   no
   * LIGHTY:                     no
   * HAPROXY:                    no
   * STUNNEL:                    no
   * NGINX:                      no
   * SIGNAL:                     no
   * ERROR_STRINGS:              yes
   * DTLS:                       no
   * SCTP:                       no
   * Indefinite Length:          no
   * Multicast:                  no
   * Old TLS Versions:           yes
   * SSL version 3.0:            no
   * TLS v1.0:                   no
   * TLS v1.3:                   no
   * TLS v1.3 Draft 18:          no
   * TLS v1.3 Draft 22:          no
   * TLS v1.3 Draft 23:          no
   * TLS v1.3 Draft 26:          no
   * Post-handshake Auth:        no
   * Early Data:                 no
   * Send State in HRR Cookie:   no
   * OCSP:                       yes
   * OCSP Stapling:              yes
   * OCSP Stapling v2:           yes
   * CRL:                        no
   * CRL-MONITOR:                no
   * Persistent session cache:   no
   * Persistent cert    cache:   no
   * Atomic User Record Layer:   no
   * Public Key Callbacks:       no
   * NTRU:                       no
   * QSH:                        no
   * Whitewood netRandom:        no
   * Server Name Indication:     yes
   * ALPN:                       yes
   * Maximum Fragment Length:    yes
   * Truncated HMAC:             yes
   * Supported Elliptic Curves:  yes
   * Session Ticket:             no
   * Extended Master Secret:     yes
   * Renegotiation Indication:   no
   * Secure Renegotiation:       no
   * All TLS Extensions:         yes
   * PKCS#7                      no
   * wolfSSH                     no
   * wolfSCEP                    no
   * Secure Remote Password      no
   * Small Stack:                no
   * valgrind unit tests:        no
   * LIBZ:                       no
   * Examples:                   yes
   * User Crypto:                no
   * Fast RSA:                   no
   * Single Precision:           no
   * Async Crypto:               no
   * Cavium:                     no
   * ARM ASM:                    no
   * AES Key Wrap:               no
   * Write duplicate:            no
   * Intel Quick Assist:         no
   * Xilinx Hardware Acc.:       no
   * Inline Code:                yes

---
damian@damian-VirtualBox:~/shared_with_windows/wolfssl-3.14.0$ make
make: Warning: File `aminclude.am' has modification time 474 s in the future
make -j2  all-am
make[1]: Entering directory `/home/damian/shared_with_windows/wolfssl-3.14.0'
make[1]: Warning: File `aminclude.am' has modification time 470 s in the future
  CC       wolfcrypt/src/src_libwolfssl_la-integer.lo
In file included from wolfcrypt/src/integer.c:41:0:
./wolfcrypt/src/misc.c:252:26: error: expected ')' before 'a'
./wolfcrypt/src/misc.c:252:26: error: expected ')' before '>' token
./wolfcrypt/src/misc.c:252:26: error: expected ')' before '?' token
make[1]: *** [wolfcrypt/src/src_libwolfssl_la-integer.lo] Error 1
make[1]: Leaving directory `/home/damian/shared_with_windows/wolfssl-3.14.0'
make: *** [all] Error 2

**Comment by kaleb-himes** [comment]
Hi @dagonzal01,

It looks like you're specifying an alternate host with ```--host=arm-unknown-nto-qnx6.6.0eabi``` but your compiler isn't being specified for cross compilation, this would typically be done something like:

```
./configure --host=arm-unknown-nto-qnx6.6.0eabi \
CC=/path/to/toolchain/bin/arm-unknown-nto-qnx6.6.0eabi-gcc \
AR=/path/to/toolchain/bin/arm-unknown-nto-qnx6.6.0eabi-ar \
AS=/path/to/toolchain/bin/arm-unknown-nto-qnx6.6.0eabi-gcc \
RANLIB=/path/to/toolchain/bin/arm-unknown-nto-qnx6.6.0eabi-ranlib \
LD=/path/to/toolchain/bin/arm-unknown-nto-qnx6.6.0eabi-ld \
<now CFLAG options and other configure options here>
```

Could you try that and let us know your results?

Warm Regards,

Kaleb

**Comment by kaleb-himes** [comment]
Hi @dagonzal01,

Disregard my last, I see you have the toolchain in your path and it is being properly detected as we see in the configure log example:

```
checking for ld used by arm-unknown-nto-qnx6.6.0eabi-gcc... /home/damian/qnx660/host/linux/x86/usr/bin/arm-unknown-nto-qnx6.6.0eabi-ld
checking if the linker (/home/damian/qnx660/host/linux/x86/usr/bin/arm-unknown-nto-qnx6.6.0eabi-ld) is GNU ld... yes
```

I suspect then you must be getting a conflict somewhere. Could you try using these CFLAGS instead:

CFLAGS="-Os -DWOLFSSL_HAVE_MIN -DWOLFSSL_HAVE_MAX" and let me know if adding the have max resolves the conflict.

Warm Regards,

Kaleb

**Comment by dagonzal01** [comment]
Hi @kaleb-himes,

Thanks for your answer. I modified a little bit your suggestion like this:

`./configure CFLAGS=-Os CPPFLAGS="-DWOLFSSL_HAVE_MIN -DWOLFSSL_HAVE_MAX" --host=arm-unknown-nto-qnx6.6.0eabi --enable-opensslextra --enable-fortress --enable-aesgcm --enable-ecc --enable-eccencrypt --enable-tlsx --enable-hkdf --enable-ocsp --enable-ocspstapling --enable-ocspstapling2 --enable-sessioncerts --enable-cmac --enable-keygen --enable-testcert`

And the build process was successful :)

However, "make check" was not. This was the output of the command and test-suite.log:

#####make check#####

damian@damian-VirtualBox:~/shared_with_windows/wolfssl-3.14.0$ make check
make -j2  check-am
make[1]: Entering directory `/home/damian/shared_with_windows/wolfssl-3.14.0'
make -j2   testsuite/testsuite.test tests/unit.test   scripts/resume.test  scripts/ocsp.test scripts/ocsp-stapling.test scripts/ocsp-stapling-with-ca-as-responder.test scripts/ocsp-stapling2.test     scripts/external.test scripts/google.test scripts/openssl.test
make[2]: Entering directory `/home/damian/shared_with_windows/wolfssl-3.14.0'
make[2]: warning: -jN forced in submake: disabling jobserver mode.
make[2]: Nothing to be done for `scripts/resume.test'.
make[2]: Nothing to be done for `scripts/ocsp.test'.
make[2]: Nothing to be done for `scripts/ocsp-stapling.test'.
make[2]: Nothing to be done for `scripts/ocsp-stapling-with-ca-as-responder.test'.
make[2]: Nothing to be done for `scripts/ocsp-stapling2.test'.
make[2]: Nothing to be done for `scripts/external.test'.
make[2]: Nothing to be done for `scripts/google.test'.
make[2]: Nothing to be done for `scripts/openssl.test'.
make[2]: `tests/unit.test' is up to date.
make[2]: Leaving directory `/home/damian/shared_with_windows/wolfssl-3.14.0'
make -j2  check-TESTS
make[2]: Entering directory `/home/damian/shared_with_windows/wolfssl-3.14.0'
make[2]: warning: -jN forced in submake: disabling jobserver mode.
make[3]: Entering directory `/home/damian/shared_with_windows/wolfssl-3.14.0'
make[3]: warning: -jN forced in submake: disabling jobserver mode.
PASS: scripts/resume.test
PASS: scripts/external.test
PASS: scripts/ocsp.test
PASS: scripts/openssl.test
PASS: scripts/google.test
FAIL: scripts/ocsp-stapling.test
FAIL: testsuite/testsuite.test
FAIL: scripts/ocsp-stapling-with-ca-as-responder.test
FAIL: tests/unit.test
PASS: scripts/ocsp-stapling2.test
make[4]: Entering directory `/home/damian/shared_with_windows/wolfssl-3.14.0'
make[4]: warning: -jN forced in submake: disabling jobserver mode.
make -j2  all-am
make[5]: Entering directory `/home/damian/shared_with_windows/wolfssl-3.14.0'
make[5]: warning: -jN forced in submake: disabling jobserver mode.
make[5]: Leaving directory `/home/damian/shared_with_windows/wolfssl-3.14.0'
make[4]: Leaving directory `/home/damian/shared_with_windows/wolfssl-3.14.0'
============================================================================
Testsuite summary for wolfssl 3.14.0
============================================================================
# TOTAL: 10
# PASS:  6
# SKIP:  0
# XFAIL: 0
# FAIL:  4
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
Please report to https://github.com/wolfssl/wolfssl/issues
============================================================================
make[3]: *** [test-suite.log] Error 1
make[3]: Leaving directory `/home/damian/shared_with_windows/wolfssl-3.14.0'
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory `/home/damian/shared_with_windows/wolfssl-3.14.0'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory `/home/damian/shared_with_windows/wolfssl-3.14.0'
make: *** [check] Error 2

#####test-suite.log#####

======================================
   wolfssl 3.14.0: ./test-suite.log
======================================

# TOTAL: 10
# PASS:  6
# SKIP:  0
# XFAIL: 0
# FAIL:  4
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: testsuite/testsuite
=========================

./testsuite/testsuite.test: line 117: /home/damian/shared_with_windows/wolfssl-3.14.0/testsuite/.libs/lt-testsuite.test: cannot execute binary file: Exec format error
./testsuite/testsuite.test: line 117: /home/damian/shared_with_windows/wolfssl-3.14.0/testsuite/.libs/lt-testsuite.test: Success

FAIL: tests/unit
================

./tests/unit.test: line 117: /home/damian/shared_with_windows/wolfssl-3.14.0/tests/.libs/lt-unit.test: cannot execute binary file: Exec format error
./tests/unit.test: line 117: /home/damian/shared_with_windows/wolfssl-3.14.0/tests/.libs/lt-unit.test: Success

FAIL: scripts/ocsp-stapling
===========================

./examples/client/client: line 117: /home/damian/shared_with_windows/wolfssl-3.14.0/examples/client/.libs/lt-client: cannot execute binary file: Exec format error
./examples/client/client: line 117: /home/damian/shared_with_windows/wolfssl-3.14.0/examples/client/.libs/lt-client: Success
-e 

Client connection failed

FAIL: scripts/ocsp-stapling-with-ca-as-responder
================================================

./examples/client/client: line 117: /home/damian/shared_with_windows/wolfssl-3.14.0/examples/client/.libs/lt-client: cannot execute binary file: Exec format error
./examples/client/client: line 117: /home/damian/shared_with_windows/wolfssl-3.14.0/examples/client/.libs/lt-client: Success
-e 

Client connection failed

Best regards,

Damian

**Comment by kaleb-himes** [comment]
Hi @dagonzal01,

Just to be sure, the make check would only succeed if run on the target architecture. We would not expect this to pass for example if you compiled for a host arm-unknown-nto-qnx6.6.0eabi but then ran the make check on a non-qnx architecture.

To get the make check passing in this scenario you would want to add ```--disable-examples``` to the build settings.

Warm Regards,

KH

**Comment by dagonzal01** [comment]
Hi @kaleb-himes,

Thank you for your quick answer. After adding `--disable-examples`, `make check` succeeded.

Best regards,

Damian
