### ISSUE TITLE
Initialization of the Crypto HW protection may be unsafe

### ISSUE THREAD

**Issue by aburks** [wolfSSL/wolfssl#164]
Thanks a lot for adding support for the Crypto HW protection! Looking at the diff it seems like there may be a race condition when initializing the mutex: https://github.com/wolfSSL/wolfssl/blob/master/wolfcrypt/src/wc_port.c#L56-L57. 

Here's the scenario that concerns me:

1. Thread A calls `wolfSSL_CryptHwMutexLock()`, which starts the init process
1. Thread A gets preempted by Thread B, which also calls `wolfSSL_CryptHwMutexLock()` and starts the init process
1. Thread B finishes creating the mutex and Thread A leaks the mutex it created

**Comment by dgarske** [comment]
That is correct and it is documented in the wc_port.h lines 152 - 155. We recommend that you call "wolfSSL_CryptHwMutexInit()" during your crypto initialization to prevent this.
