### ISSUE TITLE
DTLS problems on El Capitan

### ISSUE THREAD

**Issue by chris-wood** [wolfSSL/wolfssl#173]
Some DTLS functions don't seem to be working after upgrading to El Capitan (OS X). For example, `wolfDTLSv1_2_client_method` is not found in the library, although it was configured, built, and installed with DTLS enabled. Can anyone else reproduce this issue?

llc-dtls-client-test.c:165:33: warning: implicit declaration of function 'wolfDTLSv1_2_client_method' is invalid in C99
      [-Wimplicit-function-declaration]
    if ( (ctx = wolfSSL_CTX_new(wolfDTLSv1_2_client_method())) == NULL) {

**Comment by ejohnstown** [comment]
Did you include the header file "wolfssl/options.h" before including "wolfssl/ssl.h"?

**Comment by chris-wood** [comment]
That did it. Thanks!
