### ISSUE TITLE
 wolfssl/wolfcrypt/src/aes_asm.asm -> Looks like AT&T Assembly Syntax

### ISSUE THREAD

**Issue by fresponse** [wolfSSL/wolfssl#176]
My assembly is really rusty, but that looks like AT&T Assembly code in the " wolfssl/wolfcrypt/src/aes_asm.asm" update from 5 days ago. I could start converting it to Intel, but I'm quite certain I'd do more harm than good. Won't compile in VS15 which further cements my thinking.. Thanks!

**Comment by ejohnstown** [comment]
We're looking into this today and should have a fix soon.

**Comment by fresponse** [comment]
No worries John, the more I dug into it the more I forgot how different Intel and ATT syntax is.. I'll leave it to your far more capable hands :)

**Comment by ejohnstown** [comment]
This has been fixed with commit 17c9494.
