### ISSUE TITLE
Makefiles for Python wrapper

### ISSUE THREAD

**Issue by lechner** [wolfSSL/wolfssl#1774]
Hi, having seen some recent interest from Debian users, I would like to package more features. The Python module in `wrapper/python/wolfssl/` comes with a Makefile, but I could not find one for `wrapper/python/wolfcrypt/`. Was there ever a second Makefile that was lost somehow? Thank you!

**Comment by ejohnstown** [comment]
Felix:

There is another makefile, but it is in our wolfcrypt-py repository. The engineer who was working on it part time has moved onto other things and no one else has picked it up yet.

--John

**Comment by ejohnstown** [comment]
Felix:

We have moved our wolfSSL and wolfCrypt wrappers for Python to their own projects.

1. https://github.com/wolfssl/wolfssl-py
2. https://github.com/wolfssl/wolfcrypt-py

At this point, I wouldn't use the Python builds in the source archive.

**Comment by ejohnstown** [comment]
Also, which features were you looking to add? We recently expanded our API in the Python wrappers.

**Comment by dgarske** [comment]
Hi Felix,

As always, thank you for your contributions to this project. Following up on this issue to make sure its fully resolved.

Do you have any feedback for John on the previous question about features to add?

Thanks,
David Garske, wolfSSL

**Comment by ejohnstown** [comment]
Felix:

I'm going to close this issue at this time. If you want to make some suggestions for additions to the wolfSSL Python wrappers, please see the GitHub repository for [wolfSSL-py](https://github.com/wolfssl/wolfssl-py). Thank you.

--John
