### ISSUE TITLE
How to make .a file ?

### ISSUE THREAD

**Issue by Vaibhav1587** [wolfSSL/wolfssl#1807]
I wanted to know, how to make .a lib for wolfssl only. I tried as per my knowledge but, getting .la file.

Please guide me how do i generate .a file use it in my own project (linux based).
So that I can use it with windows machine for wolfssh implementation for STM32.

**Comment by ejohnstown** [comment]
If you are using "configure" to set up your build, you need to add "--disable-shared". This option will force the build of the static library and disable the dynamic library. It will produce the library archive file.

**Comment by ejohnstown** [comment]
Which toolchain/IDE are you using?

**Comment by Vaibhav1587** [comment]
I'm using Atollic TrueSTUDIO IDE.

**Comment by ejohnstown** [comment]
It sounds like you got it building over in that wolfSSH Issue. I'm going to close this one.
