### ISSUE TITLE
Session external cache

### ISSUE THREAD

**Issue by hajjihraf** [wolfSSL/wolfssl#1852]
Hi,

I'm using the external cache feature, however there is no way to use only external cache and disable the internal cache so no memory will be alloacted for the session storage: SessionCache table

Thanks,
Achraf

**Comment by haydenroche5** [comment]
Currently, the only way to disable allocation of SessionCache is with the define NO_SESSION_CACHE, but that also disables the ability to use sessions. If users are interested in us implementing a more targeted option to prevent allocation of SessionCache, feel free to reach out to facts@wolfssl.com. In the meantime, I've added this request to our internal feature request tracking document.
