### ISSUE TITLE
Clang warnings in ecc25519

### ISSUE THREAD

**Issue by briandw** [wolfSSL/wolfssl#19]
I'm seeing these warnings from Xcode 6.3:

/.../wolfssl/wolfcrypt/src/ecc25519.c:153:24: warning: comparison of array 'private_key->k.point' equal to a null pointer is always false [-Wtautological-pointer-compare]
    if (private_key->k.point == NULL || public_key->p.point == NULL)
        ~~~~~~~~~~~~~~~^~~~~    ~~~~
/.../wolfssl/wolfcrypt/src/ecc25519.c:153:55: warning: comparison of array 'public_key->p.point' equal to a null pointer is always false [-Wtautological-pointer-compare]
    if (private_key->k.point == NULL || public_key->p.point == NULL)
                                        ~~~~~~~~~~~~~~^~~~~    ~~~~

**Comment by JacobBarthelmeh** [comment]
Thanks for the catch.
