### ISSUE TITLE
Issue using URL with wolfSSL

### ISSUE THREAD

**Issue by weolar** [wolfSSL/wolfssl#1902]
hi, I build wolfSSL with HAVE_SNI, but this url (https://rexl.tk/) show 
"Curl_failf:SSL_connect failed with error -313: revcd alert fatal error"

**Comment by dgarske** [comment]
Hi weolar,

This is also in issue #1900. This `reak.tk` server also requires SNI. All tests pass fine assuming wolfSSL is built with --enable-sni or `HAVE_SNI` and curl is built properly using wolfSSL.

What platform are you building on? Double check your build steps. You might need `sudo ldconfig` after sudo make install. If you are still seeing issues please submit a Wireshark capture.

```
./examples/client/client -p 443 -h rexl.tk -x -d -g -S rexl.tk
```

```
curl https://rexl.tk/

<li><a href="#" class="am-icon-home">首页</a></li>
<li class="am-active">关于我</li>
</ol>
...
```

Thanks,
David Garske, wolfSSL
