### ISSUE TITLE
OpenSSL APIs incompatibilities found when hitch TLS proxy compile with wolfSSL

### ISSUE THREAD

**Issue by roytam1** [wolfSSL/wolfssl#1957]
when I tried to compile hitch-1.4.8 TLS proxy with wolfSSL(with openssl extra switch), I found some incompatibilities:

- in OpenSSL, every ASN1_* is actually same as ASN1_STRING which has type and length field.
- V_ASN1_GENERALIZEDTIME is missing

further compiling is not tested.

compile log:

````
  CC       hitch-asn_gentm.o
asn_gentm.c: In function ‘asn1_generalizedtime_to_tm’:
asn_gentm.c:135: error: ‘WOLFSSL_ASN1_TIME’ has no member named ‘type’
asn_gentm.c:135: error: ‘V_ASN1_GENERALIZEDTIME’ undeclared (first use in this function)
asn_gentm.c:135: error: (Each undeclared identifier is reported only once
asn_gentm.c:135: error: for each function it appears in.)
asn_gentm.c:137: error: ‘WOLFSSL_ASN1_TIME’ has no member named ‘length’
make[3]: *** [hitch-asn_gentm.o] Error 1

````

**Comment by haydenroche5** [comment]
The latest version of wolfSSL shouldn't give these compilation errors anymore. WOLFSSL_ASN1_TIME has both type and length members, and V_ASN1_GENERALIZEDTIME is defined. As such, I'm going to close this out.
