### ISSUE TITLE
ARMv8 support is not well defined

### ISSUE THREAD

**Issue by trevor403** [wolfSSL/wolfssl#1977]
This page is incorrect. 
https://www.wolfssl.com/armv8-hardware-acceleration-with-wolfssl/

According to this thread, ARMv8 ASM features have been marked broken since January.
http://lists.busybox.net/pipermail/buildroot/2018-January/211561.html

I am personally having troubling building this and I was wondering if we have a certain subset of processors supported on a compatibility list.

**Comment by JacobBarthelmeh** [comment]
Hi trevor403, we updated the build system to take care of setting the flag on 64bit systems. Am going to close out this issue but feel free to reopen it or contact us at support (at) wolfssl.com.
