### ISSUE TITLE
Memory leak when used threaded?

### ISSUE THREAD

**Issue by bagder** [wolfSSL/wolfssl#1989]
Hi!

When we build libcurl to use WolfSSL for HTTPS, and we invoke it from multiple threads, we get memory leaks reported by valgrind. These leaks are not there when we don't use any threads. 

The leaks seem to origin from the wolfssl_connect() call that we call here: https://github.com/curl/curl/blob/4849267197682e69cfa056c2bd7a44acd123a917/lib/vtls/cyassl.c#L489

Is there a particular cleanup method we should use that we currently don't?

This issue was filed in the curl bug tracker: https://github.com/curl/curl/issues/3387 - I see this error with WolfSSL 3.14.0 on Debian Linux.

**Comment by dgarske** [comment]
Hi @bagder 

The issue was due to libcurl not calling `CyaSSL_Cleanup();` to free our ECC fixed point cache. A libcurl patch has been pushed to: https://github.com/curl/curl/pull/3395

Thanks,
David Garske, wolfSSL
