### ISSUE TITLE
Missing check in client_test

### ISSUE THREAD

**Issue by ManSoSec** [wolfSSL/wolfssl#2037]
I am not sure how much this is critical but it seems a check is missing in client.c while it has been done in server.c

https://github.com/wolfSSL/wolfssl/blob/master/examples/client/client.c#L2125
wolfSSL_CTX_SetMinDhKey_Sz(ctx, (word16)minDhKeyBits);

https://github.com/wolfSSL/wolfssl/blob/master/examples/server/server.c#L1410
if (wolfSSL_CTX_SetMinDhKey_Sz(ctx, (word16)minDhKeyBits) != WOLFSSL_SUCCESS) {
        err_sys_ex(runWithErrors, "Error setting minimum DH key size");

I can send a pull request.

**Comment by ejohnstown** [comment]
Thank you for bringing this to our attention. I'll go ahead and fix this and the other two issues.

**Comment by ManSoSec** [comment]
Great!
