### ISSUE TITLE
Missing check on input arguments (NULL dereference)

### ISSUE THREAD

**Issue by ManSoSec** [wolfSSL/wolfssl#2038]
I noticed this missing argument check here (in HashOutput)
https://github.com/wolfSSL/wolfssl/blob/master/src/internal.c#L6477

While it is done in 2 functions (HashInput and HashOutputRaw) here:
https://github.com/wolfSSL/wolfssl/blob/master/src/internal.c#L6431
https://github.com/wolfSSL/wolfssl/blob/master/src/internal.c#L6550

if (ssl->hsHashes == NULL)
        return BAD_FUNC_ARG;

I can send a pull request.

**Comment by ejohnstown** [comment]
Thank you for bringing this to our attention. I'll go ahead and fix this and the other two issues.
