### ISSUE TITLE
Redundant Check in CheckBitString

### ISSUE THREAD

**Issue by ManSoSec** [wolfSSL/wolfssl#2039]
I noticed a redundant check in CheckBitString:

https://github.com/wolfSSL/wolfssl/blob/master/wolfcrypt/src/asn.c#L812
https://github.com/wolfSSL/wolfssl/blob/master/wolfcrypt/src/asn.c#L827

if ((idx + 1) > maxIdx)
        return BUFFER_E;

if (idx + 1 > maxIdx) {
        WOLFSSL_MSG("Attempted buffer read larger than input buffer");
        return BUFFER_E;
    }

The second one needs to be removed.

**Comment by ejohnstown** [comment]
Thank you for bringing this to our attention. I'll go ahead and fix this and the other two issues.

**Comment by ejohnstown** [comment]
I do not believe the second check is redundant. The variable `idx` is advanced in between the two checks.

**Comment by ManSoSec** [comment]
Thank you for checking! The reason I reported that is because of in 2 other locations, there is only one check. So I thought those locations might need an additional check. Would you please check them:

https://github.com/wolfSSL/wolfssl/blob/master/wolfcrypt/src/asn.c#L5448
https://github.com/wolfSSL/wolfssl/blob/master/wolfcrypt/src/asn.c#L2064

In both cases, GetLength is called in the same way in CheckBitString
https://github.com/wolfSSL/wolfssl/blob/master/wolfcrypt/src/asn.c#L818

**Comment by ejohnstown** [comment]
`GetLength()` performs its own check on what it is going to read from the buffer against the buffer bounds. In `GetDateInfo()`, `GetASNObjectId()`, and `CheckBitString()`, we are first checking that the first byte, the ASN chunk type, is in the buffer. Then we call `GetLength()` which checks that the length is inside the buffer.

The checks aren't looking redundant to me.

**Comment by ManSoSec** [comment]
ok, thanks for the information.
