### ISSUE TITLE
Missing check on mp_init_multi

### ISSUE THREAD

**Issue by ManSoSec** [wolfSSL/wolfssl#2045]
I noticed a check is missing here:

https://github.com/wolfSSL/wolfssl/blob/master/wolfcrypt/src/ecc.c#L3831
```C
err = mp_init_multi(pub->x, pub->y, pub->z, NULL, NULL, NULL);
```

While it is done here:
https://github.com/wolfSSL/wolfssl/blob/master/wolfcrypt/src/ecc.c#L5650
```C
err = mp_init_multi(point->x, point->y, point->z, NULL, NULL, NULL);
#endif
    if (err != MP_OKAY)
        return MEMORY_E;
```

I wonder if it could cause an issue.
Thanks!

**Comment by ejohnstown** [comment]
The err return value is checked. This function does a chain of `if (err == MP_OKAY)` and will skip to near the end to clean up any allocated memory if that initialization fails.
