### ISSUE TITLE
2 more inconsistencies

### ISSUE THREAD

**Issue by ManSoSec** [wolfSSL/wolfssl#2057]
We noticed 2 more inconsistencies in the code:

1) Missing null check on `out' for L359 before calling XMEMCPY:
https://github.com/wolfSSL/wolfssl/blob/master/wolfcrypt/src/random.c#L488
```C
if (out != NULL && outSz != 0) {
                if (outSz >= OUTPUT_BLOCK_LEN) {
                    XMEMCPY(out, digest, OUTPUT_BLOCK_LEN);
                    outSz -= OUTPUT_BLOCK_LEN;
                    out += OUTPUT_BLOCK_LEN;
                    array_add_one(data, DRBG_SEED_LEN);
                }
                else {
                    XMEMCPY(out, digest, outSz);
                    outSz = 0;
                }
            }
```
https://github.com/wolfSSL/wolfssl/blob/master/wolfcrypt/src/random.c#L359
```C
if (ret == 0) {
            if (outSz > OUTPUT_BLOCK_LEN) {
                XMEMCPY(out, digest, OUTPUT_BLOCK_LEN);
                outSz -= OUTPUT_BLOCK_LEN;
                out += OUTPUT_BLOCK_LEN;
            }
            else {
                XMEMCPY(out, digest, outSz);
            }
        }
```
-------------------------------------------------------------------------------------------------------------

2) Missing free on error before function return

https://github.com/wolfSSL/wolfssl/blob/master/src/internal.c#L5072
```C
/* On error free handshake key */
    if (ret != 0) {
        FreeKey(ssl, type, pKey);
    }

    return ret;
```
https://github.com/wolfSSL/wolfssl/blob/master/src/internal.c#L5123
```C
return ret;
```

**Comment by ejohnstown** [comment]
> 1. Missing null check on `out' for L359 before calling XMEMCPY

This is an internal API, and it is only ever called with valid pointers.

> 2. Missing free on error before function return

This function, `ReuseKey()`, frees the key then tries to create a new one. If the key create fails, the key is already free.
