### ISSUE TITLE
Wolfssl with haproxy

### ISSUE THREAD

**Issue by git001** [wolfSSL/wolfssl#2071]
The issue #1335 is closed but I can't find a answer there if wolfssl is a possible TLS/SSL library for haproxy.

As I build haproxy with openssl and boringssl I'm courious if wolfssl is also a possible TLS/SSL library for haproxy, not only technically also from license point of view.

These are the image which I maintain.  
https://hub.docker.com/r/me2digital/haproxy19  
https://hub.docker.com/r/me2digital/haproxy-19-boringssl

**Comment by dgarske** [comment]
Hi git001,

Yes we do have a port of haproxy for wolfSSL. Currently its in a private repo. Please email us directly at info@wolfssl.com and we should be able to get you a copy of the source code.

Thanks,
David Garske, wolfSSL

**Comment by git001** [comment]
@dgarske thanks.

I have some questions before I try to create a new Docker image.

* Can I push a wolfSSL builded image on public docker hub?
* What's the license for the port of haproxy for wolfSSL?  
* Do you plan to provide the patches to the upstream?

**Comment by kaleb-himes** [comment]
Being in Zendesk.
