### ISSUE TITLE
DecodeECC_DSA_Sig signature length check

### ISSUE THREAD

**Issue by taviso** [wolfSSL/wolfssl#2088]
I'm confused why wolfssl only checks the length isn't too big in ECC-DSA signatures, it can be totally wrong and the signature still verifies. This doesn't match what OpenSSL, NSS, GnuTLS all do who verify the length is exact.

```c
/* Der Decode ECC-DSA Signature, r & s stored as big ints */
int DecodeECC_DSA_Sig(const byte* sig, word32 sigLen, mp_int* r, mp_int* s)
{
    word32 idx = 0;
    int    len = 0;

    if (GetSequence(sig, &idx, &len, sigLen) < 0) {
        return ASN_ECC_KEY_E;
    }

    if ((word32)len > (sigLen - idx)) { // why > instead of !=?
        return ASN_ECC_KEY_E;
    }

   // ...
    return 0;
}
```

**Comment by dgarske** [comment]
Hi Taviso,

Thanks for the excellent feedback. We will review and let you know our results.

Thanks,
David Garske, wolfSSL
