### ISSUE TITLE
"host name validation"

### ISSUE THREAD

**Issue by TerrenceYyang** [wolfSSL/wolfssl#2188]
wolfSSL_X509_check_host() function is defined but not referred,does the latest version support "host name validation"?

**Comment by kaleb-himes** [comment]
@YYangJ,

Yes wolfSSL supports this, did you configure with --enable-opensslall to get access to the API in src/ssl.c?

- KH

**Comment by YYangJ** [comment]
No,How can I enable this feature in Windows environment?I try to call the function in ProcessPeerCerts, and it seems to work well,does wolfssl team plan to add macro to enable/disable "host name validation"?

**Comment by dgarske** [comment]
Hi YYangJ,

Have you tried using our `wolfSSL_check_domain_name(ssl, domain);` API? This should be called before `wolfSSL_connect` and sets a hostname/domain name, that will be checked on connect.

Failures will be reported like this:

```
ret = wolfSSL_connect(ssl);
if (ret != WOLFSSL_SUCCESS) {
    err = wolfSSL_get_error(ssl, 0);
}
```

The `err` will be `DOMAIN_NAME_MISMATCH`.

Example:
https://github.com/wolfSSL/wolfssl/blob/master/examples/client/client.c#L2761

Thanks,
David Garske, wolfSSL

**Comment by YYangJ** [comment]
Hi David Garske,
  I will try to use wolfSSL_check_domain_name(ssl, domain);API and give you feedfack ASAP.Thanks for your prompt and patient answers.

**Comment by YYangJ** [comment]
Hi David Garske,
I used wolfSSL_check_domain_name(ssl, domain);API before wolfssl_connect,ProcessPeerCerts() function will check whether domain name match common name and alt names,I added wolfSSL_X509_check_host in ProcessPeercerts before, it looks like the same effect as calling wolfSSL_check_domain_name() before wolfssl_connect.

Thanks

**Comment by YYangJ** [comment]
Hi David Garske,
I have another question,if the host is IP address, using wolfSSL_check_domain_name(ssl, domain);API before wolfssl_connect，will the SSL connection be established successfully or not? 

Thanks

**Comment by dgarske** [comment]
Hi YYangJ,

If the domain name check fails then `wolfSSL_Connect(ssl)` will fail with `WOLFSSL_FAILURE`. You can see the error code using `wolfSSL_get_error(ssl, 0)`.

Thanks,
David Garske, wolfSSL

**Comment by dgarske** [comment]
Hi YYangJ,

The `domain` argument is a string that is matched again subject common name or alternate names from the peer certificate. It does work with IP addresses if they are in a string format "192.168.0.1". Note: its very uncommon to use an IP address in a certificate, but is allowed. The certificate fields allow wildcard strings `*`. You can see the code in `MatchDomainName` here: https://github.com/wolfSSL/wolfssl/blob/683646e4526326e5ab757949249e04c21f241a13/src/internal.c#L8102

Thanks,
David Garske, wolfSSL

**Comment by kaleb-himes** [comment]
Just to come back to your earlier question:

>> Yes wolfSSL supports this, did you configure with --enable-opensslall to get access to the API in src/ssl.c?

> No,How can I enable this feature in Windows environment?I try to call the function in ProcessPeerCerts, and it seems to work well,does wolfssl team plan to add macro to enable/disable "host name validation"?

To enable opensslall in windows add this define to wolfssl-x.x.x/IDE/WIN/user_settings.h:

```
#define OPENSSL_ALL
```

- K
