### ISSUE TITLE
Build error for iOS Simulator due to inline code

### ISSUE THREAD

**Issue by MrArtichaut** [wolfSSL/wolfssl#221]
When building (in Debug) WolfSSL from the "wolfssl_ios" target for the simulator I get the following error : 

```
tfm.c:479:11 : Inline assembly requires more registers than available
                asm.c:1287:6: Expanded from macro 'MULADD'

tfm.c:1421:11: Inline assembly requires more registers than available
                asm.c:676:6: Expanded from macro 'SQRADD2'
```

Those error don't occur when building for a device.

**Comment by dgarske** [comment]
It looks like the iOS devices for iPad 2, iPad Retina, iPhone 4s and iPhone 5 do not support the assembly versions of our fast math library (specifically the MULADD and SQRADD2 functions). To resolve this add "#define TFM_NO_ASM" to your user_settings.h.

So your user_settings.h would look like:
/* Configuration */
#define IPHONE	/* Needed for Xcode */
#define HAVE_HASHDRBG
#define HAVE_AESGCM
#define WOLFSSL_SHA512
#define WOLFSSL_SHA384

#ifdef HAVE_FIPS
#define NO_MD4
#define NO_HC128
#define NO_RABBIT
#define NO_DSA
#define NO_PWDBASED
#else
#define USE_FAST_MATH
#define TFM_NO_ASM
#endif
