### ISSUE TITLE
 WolfSSL website certificate problems

### ISSUE THREAD

**Issue by albjerto** [wolfSSL/wolfssl#2220]
As of 04/29/2019, the website https://www.wolfssl.com gives a 503 error. I am sorry if this is not the right place to report this issue.
I printed the error message below:

Error 503 certificate has expired

certificate has expired
Guru Mediation:

Details: cache-lax8630-LAX 1556528326 2473892731

**Comment by dgarske** [comment]
Thanks Albjerto for the report. The SSL certificate has been updated and wolfssl.com access restored at 7:52 AM PDT (4/29/19).
