### ISSUE TITLE
Session Ticket

### ISSUE THREAD

**Issue by TerrenceYyang** [wolfSSL/wolfssl#2372]
Hi wolfssl team,

I want to add session ticket extension to resume a session,for the first ssl handshake, ssl->session.ticketLen is 0, how can I send an empty SessionTicket extension?

#ifdef HAVE_SESSION_TICKET
        if (ssl->options.resuming && ssl->session.ticketLen > 0) {
            SessionTicket* ticket;

            ticket = TLSX_SessionTicket_Create(0, ssl->session.ticket,
                                             ssl->session.ticketLen, ssl->heap);
            if (ticket == NULL) return MEMORY_E;

            ret = TLSX_UseSessionTicket(&ssl->extensions, ticket, ssl->heap);
            if (ret != WOLFSSL_SUCCESS) {
                TLSX_SessionTicket_Free(ticket, ssl->heap);
                return ret;
            }

            idSz = 0;
        }
#endif

**Comment by cariepointer** [comment]
Hi TerrenceYyang,

Thanks for reaching out to wolfSSL. An empty SessionTicket can be set by calling `wolfSSL_CTX_UseSessionTicket`. An example use case for this can be found in ./examples/client/client.c for reference. There you will also find an example of the SessionTicket callback function, `wolfSSL_set_SessionTicket_cb`.

Please let us know if you have any additional questions.
