### ISSUE TITLE
Example sketch wolfssl_client.ino: TLS Connect Error: received alert fatal error

### ISSUE THREAD

**Issue by torntrousers** [wolfSSL/wolfssl#2394]
Hi,

I'm using the Arduino environment with an ESP32 MCU's. Running the example sketch wolfssl_client.ino and have that successfully connected to the example wolfssl_server sketch.  Now updating the the IP address used by the client to try to talk to a different server written in Golang and it fails with the message "TLS Connect Error: received alert fatal error" at this line [here](https://github.com/wolfSSL/wolfssl/blob/master/IDE/ARDUINO/sketches/wolfssl_client/wolfssl_client.ino#L108).

How can I debug what the problem is?

**Comment by kaleb-himes** [comment]
Hi torntrousers,

Can you define ```DEBUG_WOLFSSL``` in user_settings.h and call wolfSSL_Debugging_ON(); on startup? This should give you a log to review.

Let us know if this helps to resolve.

- K
