### ISSUE TITLE
ecc25519_fe includes are out of order

### ISSUE THREAD

**Issue by aburks** [wolfSSL/wolfssl#24]
The includes for the ecc25519_fe header and implementation file are out of order:

* ecc25519_fe.c should include the ecc25519_fe header before checking the `HAVE_ECC25519` definition: https://github.com/wolfSSL/wolfssl/blob/master/wolfcrypt/src/ecc25519_fe.c#L27
* ecc25519_fe.h should include the `<wolfssl/wolfcrypt/settings.h>` header before checking the `HAVE_ECC25519` definition: https://github.com/wolfSSL/wolfssl/blob/master/wolfssl/wolfcrypt/ecc25519_fe.h#L28

**Comment by toddouska** [comment]
Thanks!  Fixed.
