### ISSUE TITLE
PVS Studio report

### ISSUE THREAD

**Issue by pavel-pimenov** [wolfSSL/wolfssl#2444]
V735 Possibly an incorrect HTML. The "</body" closing tag was encountered, while the "</pre" tag was expected. echoserver.c 384

                const char resp[] =
                    "HTTP/1.0 200 ok\r\nContent-type: text/html\r\n\r\n"
                    "<html><body BGCOLOR=\"#ffffff\"><pre>\r\n"
                    "greetings from wolfSSL\r\n</body></html>\r\n\r\n";

Full report:
http://www.fly-server.ru/pvs-studio/wolfssl/

**Comment by JacobBarthelmeh** [comment]
Thanks for the report Pavel, we updated the echoserver here https://github.com/wolfSSL/wolfssl/pull/2761
