### ISSUE TITLE
InitSSL() allocates ECC memory irrespective of specified cipher suites

### ISSUE THREAD

**Issue by jceven** [wolfSSL/wolfssl#25]
In `InitSSL()` there are large (8.4KB) ECC buffers allocated for the SSL structure even if no ECC TLS ciphers have been specified. The specific line numbers are here: https://github.com/wolfSSL/wolfssl/blob/master/src/internal.c#L1900-L1927

**Comment by toddouska** [comment]
Thanks for the report!  Fixed.
