### ISSUE TITLE
Add OpenSSL compatibility API’s  for picotls support!

### ISSUE THREAD

**Issue by patrickkh7788** [wolfSSL/wolfssl#2528]
the missing api:

* EVP_chacha20
* EVP_chacha20_poly1305
* EVP_PKEY_CTX_set_rsa_pss_saltlen
* EVP_PKEY_CTX_set_rsa_mgf1_md

the missing macro define:
* X509_FILETYPE_DEFAULT
* CRYPTO_add
* CRYPTO_LOCK_X509_STORE
* CRYPTO_LOCK_EVP_PKEY

**Comment by tmael** [comment]
Hi @patrickkh7788,

Thanks for contacting wolfSSL with your request!
 
You are correct that those APIs are not available yet. 
We are constantly expanding the OpenSSL compatibility layer based on customer needs and the missing APIs didn't come up before. 

Any good reasons why you are building our library with another TLS? 

Thanks,
Tesfa

**Comment by patrickkh7788** [comment]
Thanks for quick replay.

picotls provide nice api to control TLS ticket, EDNS and others.  It also allow user to switch backend(Openssl, Windows native, minicrypto).  

I already create a async api with picotls,  but with openssl & Picotls the binary  size is huge. that is why I try with wolfSSL.  

wolfSSL provide nice build options to control binary size, but lake support EDNS.

**Comment by patrickkh7788** [comment]
hi @tmael 

Today I build wolfssl with picotls,  find that `EVP_chacha20` is missing, so I add them to the list and remove some already exists apis.

Can you give some tips about how to add `EVP_chacha20` ? I can add patch to make picotls work without rest apis, but chach20 is a must have feature, and I guess other projects also could depends on `EVP_chacha20`  since it is the most frequency mobile encryption stream cipher.

Thanks,  
Patrick

**Comment by bgermann** [comment]
I second EVP_PKEY_CTX_set_rsa_pss_saltlen for SWUpdate: https://groups.google.com/forum/#!topic/swupdate/HQYFvx8T8Ao

**Comment by tmael** [comment]
Closing because we are tracking this feature request internally. 
If you would like to expedite the request, please contact us at support@wolfssl.com
