### ISSUE TITLE
Porting to new build system - for the build system.

### ISSUE THREAD

**Issue by IngwiePhoenix** [wolfSSL/wolfssl#253]
I am working on a build tool/system that is supposed to support HTTP and HTTPS. In order for the latter to work, I need an SSL library. And idealy, one that I can port to the tool's mechanism easily.

That is when I found wolfSSL, while having found yaSSL before. From what I can tell, it is very straight-forward with many things. So, I'd like to use it.

Question: Which parts do I need to compile, to get a most basic version of wolfssl going, that will allow me to create a socket, an SSL/TLS context, and then issue a HTTP request over that so I can progress the download of a file?

Kind regards, Ingwie.

**Comment by cconlon** [comment]
Hi Ingwie,

We have a wolfSSL Porting Guide which covers porting wolfSSL to a new platform.  I have attached it here for your reference.

Best Regards,
Chris
[wolfssl_porting_guide.pdf](https://github.com/wolfSSL/wolfssl/files/96324/wolfssl_porting_guide.pdf)
