### ISSUE TITLE
There is a coding-miss of MACRO in pkcs7.c

### ISSUE THREAD

**Issue by guangqing** [wolfSSL/wolfssl#2546]
in wc_PKCS7_DecodeAuthEnvelopedData(PKCS7* pkcs7, byte* in,
                                                 word32 inSz, byte* output,
                                                 word32 outputSz)

#if defined(HAVE_AESGCM) || defined(HAVE_AESCC)
should be 
#if defined(HAVE_AESGCM) || defined(HAVE_AESCCM)

**Comment by guangqing** [comment]
in asn.h

#ifndef IGNORE_NAME_CONSTRAINT
should be 
#ifndef IGNORE_NAME_CONSTRAINTS

**Comment by JacobBarthelmeh** [comment]
Hi @guangqing ,

Thank you for the report, I reviewed it and it appears accurate. Will be opening a PR with a fix shortly.

Regards,
Jacob

**Comment by JacobBarthelmeh** [comment]
Out of curiosity was a tool used to find these or a build that you are using that ran into it?
