### ISSUE TITLE
Missing check

### ISSUE THREAD

**Issue by ManSoSec** [wolfSSL/wolfssl#2577]
As it is done here:

https://github.com/wolfSSL/wolfssl/blob/e329431bc114142178275b1f758a20b71d3ae239/wolfcrypt/src/dh.c#L1920-L1937

This check 

https://github.com/wolfSSL/wolfssl/blob/e329431bc114142178275b1f758a20b71d3ae239/wolfcrypt/src/dh.c#L1930

seems to be missed here (GeneratePublicDh):

https://github.com/wolfSSL/wolfssl/blob/e329431bc114142178275b1f758a20b71d3ae239/wolfcrypt/src/dh.c#L1268-L1278

**Comment by SparkiDev** [comment]
@ManSoSec 

I'm assuming you are talking about line 1268 not checking 'ret == 0'.
This is not an issue as ret can only be 0 and therefore is a redundant check.

Sean
