### ISSUE TITLE
WolfSSL /w hardware acceleration cannot be used in multithreaded environment 

### ISSUE THREAD

**Issue by roel0** [wolfSSL/wolfssl#2580]
"wolfSSL (formerly CyaSSL) is thread safe by design"

It might be thread safe, but when you enable hardware acceleration it becomes unusable. (Ex. STM32F2_CRYPTO)

This leads to ex. bad_record_mac when two threads are doing some decrypting/encrypting at the same time.

**Comment by roel0** [comment]
I think the fault lies in the fact that the __HAL_LOCK API from the STM32 HAL library is misunderstood by the developer who added the STM32 support to wolfSSL

`     #define __HAL_LOCK(__HANDLE__)                                           \                                                         
                                   do{                                        \     
                                       if((__HANDLE__)->Lock == HAL_LOCKED)   \     
                                       {                                      \     
                                          return HAL_BUSY;                    \     
                                       }                                      \     
                                       else                                   \     
                                       {                                      \     
                                          (__HANDLE__)->Lock = HAL_LOCKED;    \     
                                       }                                      \     
                                     }while (0U)     
`

**Comment by kaleb-himes** [comment]
@roel0,

Thank you for your notes, we will review and get back to you soon with any notes.

Warmest Regards,

- K

**Comment by dgarske** [comment]
HI @roel0,

Thanks for reporting the threading mutex issue with STM32. I've enabled our hardware mutex protection around the STM32 hardware calls. See PR #2586. Looking forward to your feedback on it.

Thanks,
David Garske, wolfSSL

**Comment by dgarske** [comment]
HI @roel0,

The changes to support mutex locking on the STM32 hardware have finished testing on our side.  See PR #2586.

Thanks,
David Garske, wolfSSL
