### ISSUE TITLE
HAVE_SECRET_CALLBACK not currently exposed via autoconf

### ISSUE THREAD

**Issue by jrmithdobbs** [wolfSSL/wolfssl#262]
Currently I see no actual ./configure option to set this during automake/build without setting ```AM_CFLAGS='-DHAVE_SECRET_CALLBACK'``` in the environment where configure is run.

Maybe a ```--with-secret-callback``` ?

**Comment by ejohnstown** [comment]
The feature was added for supporting protocols that use TLS as a base, but want to use different key derivation, like EAP-FAST, and at the time there wasn't any other use for it, so we didn't make that public.

What are you trying to do with the secret callback? I'm assuming from your comments in issue 263 that you are just trying to get the master secret for a TLS session. To do that you should call the function `wolfSSL_get_keys()`.
