### ISSUE TITLE
Cookie exchange in Session-Resuming Handshake

### ISSUE THREAD

**Issue by probas** [wolfSSL/wolfssl#2674]
Hi,

As per Figure 2 from [Datagram Transport Layer Security Version 1.2](https://tools.ietf.org/html/rfc6347) there are only 3 flights for the handshake that employs session resumption:
![fig2](https://user-images.githubusercontent.com/4686892/70933893-6c4c6680-2045-11ea-85ad-b40526c8cf37.png)

However, when I perform resumption from examples using client and server as I see an extra flight with cookie exchange at the very beginning caused by HelloVerifyRequest from the server, e.g packets 52-54:
![resumption](https://user-images.githubusercontent.com/4686892/70933953-88e89e80-2045-11ea-9b1d-7fc321328c77.png)

Questions are: can cookie exchange in the lib examples be explained by section 4.2.1. Denial-of-Service Countermeasures of the above mentioned RFC? Are there other reasons of having HelloVerifyRequest during session resumption?

Usage example of client/server built from the latest sources:
server -s -u -r
client -s -u -r

**Comment by kaleb-himes** [comment]
@probas,

Thank you so much for reaching out to wolfSSL. I will check with our resident DTLS expert and get you an answer as soon as possible!

Regards,

K

**Comment by ejohnstown** [comment]
Yes, we are opting to perform a cookie exchange in line with section 4.2.1 of the RFC. The hello verify transaction is still providing a filter before the server bothers to allocate resources towards performing the shortened resume handshake.

**Comment by ejohnstown** [comment]
Is this something you want to have changed?

**Comment by probas** [comment]
Sorry for delay.
My question was rather a clarification, as I faced the issue with my WolfSSL-based client failing to complete the handshake if the server did not send HelloVerifyRequest.
The issue had been already resolved through WolfSSL support. Thank you!
