### ISSUE TITLE
Memory leak in ATECC608A implementation

### ISSUE THREAD

**Issue by akmcomau** [wolfSSL/wolfssl#2701]
Hi, I have discovered a memory leak in the part of the code that releases memory for the public key (the function wc_ecc_free() in ecc.c) when the ATECC608A chip is used for authentication.  There is an #if which makes the code not release the memory consumed by the public key.  Removing this condition around the code that free's the memory seems to resolve the issue.

The memory seems to get consumed DoServerKeyExchange and EccSharedSecret and seems to leak 194 bytes per client connection.  See [memory leak.txt](https://github.com/wolfSSL/wolfssl/files/3997418/memory.leak.txt) with the output from an iteration of a client connection.  I defined my own malloc/realloc/free functions which printed out the memory usage to find where the issue was.

When the ECC is done in software rather than hardware, this memory leak does not occur.

The following patch seems to resolve the issue:
```
diff --git a/wolfcrypt/src/ecc.c b/wolfcrypt/src/ecc.c
index d910446d4..ff0e952f5 100644
--- a/wolfcrypt/src/ecc.c
+++ b/wolfcrypt/src/ecc.c
@@ -5172,14 +5172,13 @@ int wc_ecc_free(ecc_key* key)
 #ifdef WOLFSSL_ATECC508A
     atmel_ecc_free(key->slot);
     key->slot = ATECC_INVALID_SLOT;
-#else
+#endif /* WOLFSSL_ATECC508A */
 
     mp_clear(key->pubkey.x);
     mp_clear(key->pubkey.y);
     mp_clear(key->pubkey.z);
 
     mp_forcezero(&key->k);
-#endif /* WOLFSSL_ATECC508A */
 
 #ifdef WOLFSSL_CUSTOM_CURVES
     if (key->deallocSet && key->dp != NULL)
```

**Comment by embhorn** [comment]
Thank you for the memory leak report. We will investigate and report our findings back to you.

wolfSSL Support
