### ISSUE TITLE
X509_sign has wrong behavior.

### ISSUE THREAD

**Issue by ArtBlnd** [wolfSSL/wolfssl#2718]
https://github.com/wolfSSL/wolfssl/blob/ce0475a8e0812ec4d9b800436ca87e3f2aa83639/wolfcrypt/src/asn.c#L12056-L12058

Initializing `Cert` object always have selfSigned flag. so using `wolfSSL_X509_set_issuer_name` always being ignored and it just changes to subject name. 

it will be fixed by just replacing 
```cert->selfSigned ? &cert->subject : &cert->issuer```
to
``` &cert->issuer ```

or maybe make additional parameters that check its self-signed certification will helped.

**Comment by ejohnstown** [comment]
I have a fix for this. PR details should automatically appear when I set it up. I call out this issue in the commit. I want to fix your other issue.
