### ISSUE TITLE
WolfSSL_sk_X509_EXTENSION_pop_free - warning C4028: formal parameter 2 different from declaration

### ISSUE THREAD

**Issue by vaintroub** [wolfSSL/wolfssl#2752]
MSVC rightfully complains that function declaration and definition differ for WolfSSL_sk_X509_EXTENSION_pop_free 

looks like a typo in ssl.h
```
WOLFSSL_API void wolfSSL_sk_X509_EXTENSION_pop_free(
        WOLF_STACK_OF(WOLFSSL_X509_EXTENSION)* sk,
        void f (WOLFSSL_X509_EXTENSION*));
```

second parameter should be corrected to be classic "function to pointer"
```
void (*f) (WOLFSSL_X509_EXTENSION*)
```

to be consistent with definition in ssl.c

**Comment by JacobBarthelmeh** [comment]
Thanks for the report, a fix for the typo is under way here https://github.com/wolfSSL/wolfssl/pull/2770
