### ISSUE TITLE
Missing function

### ISSUE THREAD

**Issue by zero-rp** [wolfSSL/wolfssl#2780]
SSL_get_servername_type
X509_add_ext

**Comment by kaleb-himes** [comment]
@zero-rp,

Thank you for submitting this feature request to add additional OpenSSL compatibility APIs'.

Can you share a bit about the project you are working on and what your timelines are? When would these need to be added to meet your project deadline?

Regards,

K

**Comment by haydenroche5** [comment]
X509_add_ext has since been added to our OpenSSL compatibility layer. I'm going to close this out due to inactivity. Feel free to reach out again if you're interested in us implementing SSL_get_servername_type. Thanks!
