### ISSUE TITLE
menu.js source file column too wide

### ISSUE THREAD

**Issue by ottok** [wolfSSL/wolfssl#2783]
In `wolfssl/doc/formats/html/html_changes/menu.js` there are two lines that are over 600 characters wide. This is not good practice and should be fixed..

**Comment by kaleb-himes** [comment]
Hi @ottok,

Thank you for submitting this pull request. As wolfSSL is a commercial organization and licenses this software by default we can only accept non-wolfssl-employee contributions after we have a formal license agreement in place that allows for code contributions OR in lack of a license agreement we can send you an individual contributor agreement to review, sign, and return if you agree with the terms of the agreement.

Can you tell us if this was part of an effort involving a licensed wolfSSL product? If this was not for an already licensed product could you please send an email to "support [at] wolfssl [dot] com" with the subject "Attn @kaleb: Request for contributor agreement regarding PR 2783" and I'll be happy to get the review process started by first sending you a contributor agreement for review and signing.

Thank you and Regards,

K
