### ISSUE TITLE
#define FREERTOS implies NO_DH

### ISSUE THREAD

**Issue by jceven** [wolfSSL/wolfssl#28]
We'd like to use TLS_DHE* cipher suites, but since we are using FREERTOS settings.h inside WolfSSL sees FREERTOS and then defines NO_DH.

**Comment by toddouska** [comment]
Thanks for the request.  If you define HAVE_DH in user_settings.h (or in some other way) the FREERTOS in settings.h will no longer automatically disable DH.  I added the same for SHA-512 with HAVE_SHA512.
