### ISSUE TITLE
OpenSSL PKCS7_SIGNER_INFO API

### ISSUE THREAD

**Issue by bgermann** [wolfSSL/wolfssl#2816]
Please add the OpenSSL API to the compatibility layer that is related to PKCS7_SIGNER_INFO.

**Comment by JacobBarthelmeh** [comment]
Hi bgermann, thanks for the request! Adding all API related to PKCS7_SIGNER_INFO represents a significant amount of work, can you tell us some about the use case or narrow down the API's requests?

**Comment by bgermann** [comment]
This is to resolve https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=952399 but maybe this gets resolved otherwise.

**Comment by JacobBarthelmeh** [comment]
Thanks for the feedback on this, we are reviewing the feature request internally. In the mean time it has been added to the feature request list.

**Comment by bgermann** [comment]
Debian changed its position on linking with OpenSSL, so the kmod issue is not relevant anymore.
