### ISSUE TITLE
Why I cannot find v4.3.0-stable git tag in source code?

### ISSUE THREAD

**Issue by awsa2ron** [wolfSSL/wolfssl#2832]
Hi,
Maybe this is a silly question. Why I cannot find v4.3.0-stable git tag in source code? And how can I checkout the v4.3.0-stable source code? Because I want to use the new added libwebsockets feature.

Thanks!

**Comment by embhorn** [comment]
Hello @awsa2ron 

Thanks for contacting wolfSSL Support. 
Instructions for checking out a tag:

1. clone the wolfSSL repository `git clone https://github.com/wolfSSL/wolfssl.git`
2. `cd wolfssl`
3. Fetch the tags that are not normally pulled down `git fetch && git fetch --tags`
4. Checkout the release tag to a new branch `git checkout -b v4.3.0-stable`

Hope that helps,
Eric Blankenhorn 
wolfSSL Support

**Comment by awsa2ron** [comment]
Hi,

I can see v4.3.0-stable after git fetch -–tags
Thank you very much.
