### ISSUE TITLE
Change MCU via STM32CubeMX example

### ISSUE THREAD

**Issue by dBarmpxkos** [wolfSSL/wolfssl#2843]
Hi,
I load the [example .ioc file](https://github.com/wolfSSL/wolfssl/tree/master/IDE/OPENSTM32) for the STM32CubeMX in order to configure it per my hardware (I have a NUCLEO-F401RE). The README states _2. Adjust the HAL options based on your specific micro-controller._

Apparently, this example was generated with STM32CubeMX v4.16.1, in which I cannot change target MCU after loading a project. By trying with a newer version of STM32CubeMX (v.5.0.0), where I can change the target, it re-initializes a project as "untitled", and when I generate code it creates 3 directories, "Inc", "MXTmpFiles" and "Src", out of which only MXTmpFiles is not empty, and has a file "license.tmp".
It seems more like a compatibility issue and not wolfSSL problem, but I was wondering, is there a way to get it going with another ST development board with HAL support relatively fast?
For now, I generated code using the default MCU selected and I will manually create another project where I will migrate the files, but the main problem here is that HAL drivers mismatch between devices (e.g. I don't have TRNG, no lwIP support etc.).

Keep up the good work,
Dimitris

**Comment by dgarske** [comment]
Hi @dBarmpxkos ,

We fully support using any of the following STM32 processors: STM32F2, STM32F4, STM32L4 and STM32F7. Our library has no specific hardware requirements preventing you for switching boards. When using the CubeMX tool to generate HAL code you should include the RNG if possible. If your chip supports it there are also Hash and Crypto peripheral options that should be included. If those are not present use the `NO_STM32_CRYPTO` and `NO_STM32_HASH` options to disable that support.

Here are the applicable build options in the `Inc/user_settings.h`:

```
* WOLFSSL_STM32[F1 | F2 | F4 | F7 | L4] use one of these defines when building for the appropriate STM32 device.

* WOLFSSL_STM32_CUBEMX when using the CubeMX tool to generate Hardware Abstraction Layer (HAL) API’s use this setting to add appropriate support in wolfSSL.

* WOLFSSL_CUBEMX_USE_LL When using the CubeMX tool to generate APIs there are two options, HAL (Hardware Abstraction Layer) or Low Layer (LL). Use this define to control which headers are include in wolfssl-root/wolfssl/wolfcrypt/settings.h in the WOLFSSL_STM32[F1/F2/F4/F7/L4] section.

* NO_STM32_CRYPTO For when an STM32 part does not offer hardware crypto support

* NO_STM32_HASH For when an STM32 part does not offer hardware hash support

* NO_STM32_RNG For when an STM32 part does not offer hardware RNG support
```

You might also find our FAQ and porting guide links useful:
https://www.wolfssl.com/docs/porting-guide/
https://www.wolfssl.com/docs/frequently-asked-questions-faq/

Thanks,
David Garske, wolfSSL
