### ISSUE TITLE
boost::asio::ssl::context::set_default_verify_paths fails silently

### ISSUE THREAD

**Issue by bgemmill** [wolfSSL/wolfssl#2902]
Good afternoon, I was looking into using wolfssl with boost::asio, and it looks like the paradigm of:
```
boost::asio::ssl::context ctx;
ctx.set_default_verify_paths();
ctx.set_verify_mode(boost::asio::ssl::verify_peer);
```
fails at ssl handshake time because no certificates were actually loaded in the `set_default_verify_paths()` step.

Tracing through the code reveals `wolfSSL_CTX_set_default_verify_paths` seems stubbed out.

Without any certs, it gives a somewhat cryptic error like issue #2753 of `non-blocking socket write buffer full`.

Would it be possible to have `wolfSSL_CTX_set_default_verify_paths` load system certificates?

**Comment by kaleb-himes** [comment]
@bgemmill,

Yes that would be possible. I've added it to our feature request list. Feature requests are worked on in our spare time between funded efforts and have no guaranteed implementation timeline. If a feature ever becomes a blocker for a project and a hard timeline is needed it can be accelerated! Just shoot us an email at support [at] wolfssl [dot] com and let us know which feature and what your timeline is to get the ball rolling on a finite timeline effort.

```
Request Summary:

Requested Feature: please add support where wolfSSL_CTX_set_default_verify_paths will load system certs
Requesting Org: Unknown
Requestor Name: Ben Gemmill
Requestor Email: UNKNOWN, reach w/ @bgemmill on github or see https://github.com/bgemmill
Requested Source: Github Issue #2902 (wolfSSL)
Source Link: https://github.com/wolfSSL/wolfssl/issues/2902
Requested Date: 13 Apr 2020
Implementation Date: Unfunded effort, no timeline
```

Warm Regards,

K
