### ISSUE TITLE
--enable-all also enables SSL 3.0

### ISSUE THREAD

**Issue by Lekensteyn** [wolfSSL/wolfssl#2940]
The `--enable-all` option (as used in the curl automated tests) enables SSL 3.0 contrary to the documented behavior:
```
$ ./configure --help
...
  --enable-all            Enable all wolfSSL features, except SSLv3 (default:
                          disabled)
...
$ ./configure --enable-all
...
   * Old TLS Versions:           yes
   * SSL version 3.0:            yes
   * TLS v1.0:                   no
   * TLS v1.3:                   yes
```

I guess this is due to a1f69f0d648626c01066a9cdfc50422bf03b1448 (@MJSPollard, 2018) which made `ENABLE_HAPROXY` imply SSL 3.0 support. Either the documentation should be updated, or even better, HAPROXY support should not imply SSL 3.0.

See also [RFC 7568 - Deprecating Secure Sockets Layer Version 3.0](https://tools.ietf.org/html/rfc7568).

**Comment by haydenroche5** [comment]
Fixed by https://github.com/wolfSSL/wolfssl/pull/3182.
