### ISSUE TITLE
documentation missing for wc_AesGcmSetExtIV and wc_AesGcmEncrypt_ex

### ISSUE THREAD

**Issue by grooverdan** [wolfSSL/wolfssl#2941]
I'm trying to work out how to do a stream version of AesGcm.

**Comment by haydenroche5** [comment]
Thanks for letting us know about the missing documentation. We'll add a todo for that to our internal list of cleanups/feature requests.

As for a streaming version of AES GCM, check out this other issue: https://github.com/wolfSSL/wolfssl/issues/3460
