### ISSUE TITLE
Implementation issues in TLS 1.3 integrity-only cipher suites

### ISSUE THREAD

**Issue by Lekensteyn** [wolfSSL/wolfssl#2945]
Hi!

@SparkiDev implemented [draft-camwinget-tls-ts13-macciphersuites-05][1](*1) in 51dfc35aac1a1c85eca40c6ae68acc869a1cf915 via https://github.com/wolfSSL/wolfssl/pull/2386 (included with WolfSSL 4.2.0, released Oct 2019). Based on an interoperability test against an [implementation in Wireshark][2], I've discovered two potential issues:
- WolfSSL uses 12 zero bytes as "nonce" instead of the `write_iv` from the TLS 1.3 key schedule. This "nonce" is used as part of the HMAC data.
- WolfSSL uses half the size of the HKDF hash algorithm as HMAC key instead of the full size.

For SHA-256, this reduces the size of the key from 32 bytes to 16 bytes (128 bits) which should be reasonable even when facing a quantum computer. Reducing the key length does not seem to gain you a lot of benefits though, both for key extraction and for HMAC calculation.

Although the draft is underspecified, it seems that the intent is to follow TLS 1.3 unless stated otherwise. See also https://github.com/ncamwing/tls13-ciphersuites/issues/1 for feedback relayed to the author.

In the interest of learning about further potential interoperability issues, are you aware of any WolfSSL users that have this non-standard cipher enabled? What prompted for implementation of this feature in WolfSSL? It would require a very specific configuration that enables both TLS 1.3 and null ciphers (`./configure --enable-tls13 --enable-nullcipher`).

*1) draft-camwinget-tls-ts13-macciphersuites-03 was the most recent version at the time of the PR, but there are no significant differences with the current draft version.

 [1]: https://tools.ietf.org/html/draft-camwinget-tls-ts13-macciphersuites-05
 [2]: https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=16543

**Comment by SparkiDev** [comment]
Hi Peter,

First of all I'd like to thank you for taking the time to find the interoperability issues in the code.
A pull request has been put up that I believe address the issues: https://github.com/wolfSSL/wolfssl/pull/2947

Please let me know if there is still something wrong!

We are not aware of anyone using the integrity only cipher suites - it was asked for by the writers of the draft document.
Feedback on the implementation and questions on the using the nonce for security reasons was sent but not response received.
I've left the ability to include the nonce in the code but it is disabled.

Thanks,
Sean
