### ISSUE TITLE
TLSv1.0 broken in 4.4.0 (tested with schannel)

### ISSUE THREAD

**Issue by vaintroub** [wolfSSL/wolfssl#2960]
Testing MariaDB, found that e6affa386f67cb6428d95bdf0d3de1adb78dfb79 breaks TLSv1.0 with Schannel , on Windows 10.
Attached are network traces (good.pcap with 4.3.0, bad.pcap with current master), viewable e.g with Wireshark.
[network_trace.zip](https://github.com/wolfSSL/wolfssl/files/4596331/network_trace.zip)

server (WolfSSL) is instructed to use TLSv1.0 only, via SSL_CTX_set_options.
client(Schannel) supports TLSv1.0 (but also TLSv1.1 and TLSv1.2)
client fails with The token supplied to function is invalid. Error 0x80090308(SEC_E_INVALID_TOKEN)

**Comment by vaintroub** [comment]
Found via git bisect

**Comment by vaintroub** [comment]
Perhaps, Schannel is confused, since a server which does not support TLSv1.3  sends TLSv1.3 "DOWNGRD" in its "random"

We build so far without 1.3 support, and in this case also instructed WolfSSL server to use TLSv1.0 only.

**Comment by SparkiDev** [comment]
Hi @vaintroub,

I believe I've got a fix for this: https://github.com/wolfSSL/wolfssl/pull/2964
The problem appears to be that wolfSSL wasn't checking the flag for no TLS v1.2.

Please  let me know if this works!

Sean

**Comment by vaintroub** [comment]
@SparkiDev , yes, this patch works for me.

**Comment by SparkiDev** [comment]
Hi @vaintroub,

Thanks for reporting the issue!
The pull request has been merged and the patch worked for you so I'm closing this issue.

Sean
