### ISSUE TITLE
Zephyr setup fails with Zephyr 2.2.+

### ISSUE THREAD

**Issue by mdecandia81** [wolfSSL/wolfssl#2981]
Hi All,
I'm trying to install wolfssl tests in Zephyr sources following  README

https://github.com/wolfSSL/wolfssl/tree/master/IDE/zephyr
zephyr/ext/lib/crypto and zephyr/samples/crypto folder does not exits so script fails.

If adding them manually, the IDE/zephyr/setup.sh was successfully completed but trying to build with west it fails:

_west build -pauto -b qemu_x86 samples/crypto/wolfssl_test/
-- west build: generating a build system
-- Application: /home/michele/devel/zephyrproject/zephyr/samples/crypto/wolfssl_test
-- Zephyr version: 2.2.99 (/home/michele/devel/zephyrproject/zephyr)
-- Found Python3: /usr/bin/python3.8 (found suitable exact version "3.8.2") found components: Interpreter 
-- Board: qemu_x86
-- Found west: /home/michele/.local/bin/west (found suitable version "0.7.2", minimum required is "0.7.1")
-- Found toolchain: zephyr (/home/michele/devel/zephyr-sdk-0.11.2)
-- Found BOARD.dts: /home/michele/devel/zephyrproject/zephyr/boards/x86/qemu_x86/qemu_x86.dts
-- Generated zephyr.dts: /home/michele/devel/zephyrproject/zephyr/build/zephyr/zephyr.dts
-- Generated devicetree_unfixed.h: /home/michele/devel/zephyrproject/zephyr/build/zephyr/include/generated/devicetree_unfixed.h

/home/michele/devel/zephyrproject/zephyr/samples/crypto/wolfssl_test/prj.conf:20: warning: attempt to assign the value 'y' to the undefined symbol WOLFSSL_DEBUG

/home/michele/devel/zephyrproject/zephyr/samples/crypto/wolfssl_test/prj.conf:23: warning: attempt to assign the value 'y' to the undefined symbol WOLFSSL

/home/michele/devel/zephyrproject/zephyr/samples/crypto/wolfssl_test/prj.conf:24: warning: attempt to assign the value 'y' to the undefined symbol WOLFSSL_BUILTIN
Parsing /home/michele/devel/zephyrproject/zephyr/Kconfig
Loaded configuration '/home/michele/devel/zephyrproject/zephyr/boards/x86/qemu_x86/qemu_x86_defconfig'
Merged configuration '/home/michele/devel/zephyrproject/zephyr/samples/crypto/wolfssl_test/prj.conf'

error: Aborting due to Kconfig warnings

CMake Error at /home/michele/devel/zephyrproject/zephyr/cmake/kconfig.cmake:217 (message):
  command failed with return code: 1
Call Stack (most recent call first):
  /home/michele/devel/zephyrproject/zephyr/cmake/app/boilerplate.cmake:504 (include)
  CMakeLists.txt:2 (include)_
`
Any help?

Thank you

**Comment by haydenroche5** [comment]
Hi @mdecandia81. Apologies for the (very) late reply. If you're still having issues with this and are interested in getting it fixed, can you reach out to support@wolfssl.com? Thanks!
