### ISSUE TITLE
--enable-all option compiling error

### ISSUE THREAD

**Issue by sacca97** [wolfSSL/wolfssl#2999]
![immagine](https://user-images.githubusercontent.com/26978820/82930063-0dd8cc00-9f85-11ea-89c6-5722b2c5c762.png)

Both master and latest release.

**Comment by JacobBarthelmeh** [comment]
Hi @sacca97. Thanks for the report. Which compiler can be used to reproduce this? So far have tried on my local machine with gcc 9.2.0 and an older version of clang without success in reproducing the compiler message.

**Comment by sacca97** [comment]
@JacobBarthelmeh I'm on gcc 10.1.0, didn't think about trying an earlier version though.

**Comment by JacobBarthelmeh** [comment]
I can reproduce the compiler error with gcc 10.1 and am working on a solution. A work around is using older compiler version.

**Comment by JacobBarthelmeh** [comment]
Hi @sacca97 a fix for this was merged into master.
