### ISSUE TITLE
Missing Sanity Check for malloc() plus possible memory leak in wolfssl-3.8.0

### ISSUE THREAD

**Issue by dogbert2** [wolfSSL/wolfssl#300]
Hello All,

    In reviewing code in wolfssl-3.8.0, in file '/src/sniffer.c', there is
a call to malloc() which is not checked for a return value of NULL,
indicating failure.  Additionally, if this occurs, the previously
allocated memory assigned to loadBuf is not released after the call
to malloc() in function 'LoadKeyFile()'.  The patch file which
addresses/corrects this issue is below:

--- sniffer.c.orig      2016-02-09 13:22:56.710139686 -0800
+++ sniffer.c   2016-02-09 13:24:20.800827180 -0800
@@ -1068,6 +1068,10 @@
 
     if (typeKey == SSL_FILETYPE_PEM) {
         saveBuf = (byte*)malloc(fileSz);
+       if (saveBuf == NULL) {
+           free(loadbuf);
+           return -1;
+       }
 
         saveBufSz = wolfSSL_KeyPemToDer(loadBuf, (int)fileSz,
                                                 saveBuf, (int)fileSz, password);
												 
=======================================================================

**Comment by ejohnstown** [comment]
Bill:

Thanks for the catch! Luckily the first thing that `wolfSSL_KeyPemToDer()` does is check that pointer and returns a bad argument error immediately. But, I agree that sniffer.c as an application of wolfSSL should check its allocation before calling into the wolfSSL API.

I'm going to fix this in a slightly different manner so I can clean up after any possible failures in `wolfSSL_KeyPemToDer()` as well.
