### ISSUE TITLE
wolfcrypt\src\asn.c(14005): error C2065: “buffer”:

### ISSUE THREAD

**Issue by zhaooptimus** [wolfSSL/wolfssl#3049]
when set HAVE_ED448 i got this error
wolfcrypt\src\asn.c(14005): error C2065: “buffer”: undefined
should i replace buffer to buf??

**Comment by SparkiDev** [comment]
Hi @zhaooptimus,

Thanks for raising this issue!
A new pull request has been put up that fixes this and your other issue;
  https://github.com/wolfSSL/wolfssl/pull/3053

Let us know how this goes!

Sean, wolfSSL
