### ISSUE TITLE
issues in mutex test

### ISSUE THREAD

**Issue by teddyzhai** [wolfSSL/wolfssl#3109]
In `mutex_test` in `wolfcrypt/test/test.c `,
```
#ifdef WOLFSSL_PTHREADS
    if (wc_InitMutex(&m) != 0)
        return -12701;
    if (wc_LockMutex(&m) != 0)
        return -12702;
    if (wc_FreeMutex(&m) != BAD_MUTEX_E)
        return -12703;
```
Here, `wc_FreeMutex` does not necessarily  fail, because it calls `pthread_mutex_destroy` underneath.

According to spec: https://pubs.opengroup.org/onlinepubs/009695399/functions/pthread_mutex_destroy.html
"_Attempting to destroy a locked mutex results in undefined behavior_."
So, undefined behavior means any behavior is possible.

We have a POSIX implementation where free a locked mutex does not fail.

So, should we make this test optional? Thanks a.ot.

**Comment by dgarske** [comment]
Hi @teddyzhai,

I am not a fan of test `-12703` either. We will review and discuss internally. 

Perhaps we can just remove that test case. These tests only run when pthreads is used, which is supported across many platforms with varying behavior. We already have a `!WOLFSSL_SOLARIS` case added there... https://github.com/wolfSSL/wolfssl/blob/master/wolfcrypt/test/test.c#L28004

Thanks,
David Garske, wolfSSL
