### ISSUE TITLE
Doc and example about returned value for wc_RsaPublicEncrypt are inconsistent

### ISSUE THREAD

**Issue by kam193** [wolfSSL/wolfssl#3161]
Doc says: ` Upon successfully encrypting the input message, returns the number bytes written to out` (L62), but example presents test for return value `!=0`:
https://github.com/wolfSSL/wolfssl/blob/3eff20904a2a8ba14b90ceec48f2630c129e6b67/doc/dox_comments/header_files/rsa.h#L117-L120
The proper test should be `>= 0`.

The whole reported doc is here:
https://github.com/wolfSSL/wolfssl/blob/3eff20904a2a8ba14b90ceec48f2630c129e6b67/doc/dox_comments/header_files/rsa.h#L57-L126

**Comment by kaleb-himes** [comment]
PR up for this @ PR #3465
