### ISSUE TITLE
Port to vcpkg

### ISSUE THREAD

**Issue by wangwenx190** [wolfSSL/wolfssl#3226]
wolfSSL uses CMake so I think it's not diffcult to port to vcpkg.

**Comment by haydenroche5** [comment]
I have filed this request in our internal feature request list. If there's interest in having us port wolfSSL to vcpkg, please reach out to facts@wolfssl.com. Thanks!

**Comment by Kiddinglife** [comment]
any comments on vcpkg ? now it is still not possible to install wolfssl via vcpkg.

**Comment by elms** [comment]
@wangwenx190 I've update https://github.com/wolfSSL/wolfssl/issues/4323 to indicate that there is a [PR](https://github.com/microsoft/vcpkg/pull/24348) to add vcpkg support

**Comment by wangwenx190** [comment]
> @wangwenx190 I've update #4323 to indicate that there is a [PR](https://github.com/microsoft/vcpkg/pull/24348) to add vcpkg support

Thanks! That's really good to hear!
