### ISSUE TITLE
Security threat due to insecure functions malloc used in mem_track.h file. 

### ISSUE THREAD

**Issue by Priya1794** [wolfSSL/wolfssl#3241]
Hi,

I am getting security threat in below code for memtrack.h class https://github.com/wolfSSL/wolfssl/blob/master/wolfssl/wolfcrypt/mem_track.h

Occurrences of "mem.track.h" method which is an insecure function acc to security tool.
 mt = (memoryTrack*)malloc(sizeof(memoryTrack) + sz);

Below is the issue description and reference links from security team.

**Issue description :** Use of insecure functions/potential dangerous functions
**Reference link:** https://cwe.mitre.org/data/definitions/676.html , CWE-789 - Uncontrolled Memory Allocation 
This would explain why **SECURITY TEAM** is recommending the change of these functions.

Please provide solution for this as soon as possible as it is very urgent.

Thanks and Regards

**Comment by kaleb-himes** [comment]
@Priya1794,

Thank you for the report. The mem_track.h header is for use in development only when optimizing the wolfSSL library. This feature is for determining how much HEAP memory is being utilized by a given cipher suite or crypto algorithm. Users trying to optimize or tune the build to a specific heap usage can configure wolfSSL with:

```
$ ./configure --enable-trackmemory
```

and then execute one of the example applications to see an output like so:

```
$ ./wolfcrypt/test/testwolfcrypt
<truncated for brevity>
Test complete
total   Allocs   =      2162
total   Deallocs =      2162
total   Bytes    =   6385505
peak    Bytes    =     63104
current Bytes    =         0
```

Then measure again with one of our tuning options:

```
$ ./configure --enable-trackmemory CFLAGS=-DALT_ECC_SIZE
$ make
$ ./wolfcrypt/test/testwolfcrypt
<truncated for brevity>
Test complete
total   Allocs   =      2162
total   Deallocs =      2162
total   Bytes    =   1155505
peak    Bytes    =     10208
current Bytes    =         0
```

As you can see the first test used the same number of allocations and de-allocations but the "peak Bytes" was 63k. In the tuned build the same number of allocations and de-allocations resulted in a peak usage of only 10k, much more optimal for embedded use-cases.

This is not a feature of the library in release mode and is not recommended for release mode therefore this feature will not be changed. Thank you again for the report though!

Warm Regards,

KH
