### ISSUE TITLE
Use of non-portable malloc() instead of XMALLOC used in test.h file.

### ISSUE THREAD

**Issue by Priya1794** [wolfSSL/wolfssl#3242]
Hi,

I am getting security threat in below code for test.h class .https://github.com/wolfSSL/wolfssl/blob/master/wolfssl/test.h

There are occurrences of "malloc" method which is an insecure function acc to security tool.

*buf = (byte*)malloc(*bufLen);
 *derBuf = (byte*)malloc(bufLen);
encCtx = (AtomicEncCtx*)malloc(sizeof(AtomicEncCtx));
 decCtx = (AtomicDecCtx*)malloc(sizeof(AtomicDecCtx));

Below is the issue description and reference links from security team.

**Issue description** : Use of insecure functions/potential dangerous functions
**Reference link:** https://cwe.mitre.org/data/definitions/676.html , CWE-789 - Uncontrolled Memory Allocation 
This would explain why **SECURITY TEAM** is recommending the change of these functions.

Please provide solution for this as soon as possible as it is very urgent.

**Comment by haydenroche5** [comment]
I've filed this in our internal list of feature requests / cleanups. Closing.
