### ISSUE TITLE
"WOLFSSL_FFDHE_3072~WOLFSSL_FFDHE_8192" groups report an error

### ISSUE THREAD

**Issue by xielizyh** [wolfSSL/wolfssl#3293]
Hi,
   when using wolfSSL_UseKeyShare(ssl, WOLFSSL_FFDHE_3072), it return a error code, that is "-112". Is it meanning that it is mow unable to use DH 3072-bit parameters?

Thanks in advance.

**Comment by dgarske** [comment]
Hi @xielizyh ,

Make sure you have FP_MAX_BITS defined to be the max RSA/DH key size times 2. So for 3072 bit DH you should add `CFLAGS="-DFP_MAX_BITS=6144` or `#define FP_MAX_BITS 6144`. 

Also with TLS 1.3 you need to define the DH key parameters you'd like to include using `-DHAVE_FFDHE_3072` or `#define `HAVE_FFDHE_3072`.

Thanks,
David Garske, wolfSSL

**Comment by xielizyh** [comment]
Hi @garske,

Follow your settings, the FFDHE-3072~FFDHE-8192 groups were all successfully implemented. 

![image](https://user-images.githubusercontent.com/33270435/93174459-93fd6600-f760-11ea-93bc-6be00433ca85.png)

Thanks.

**Comment by dgarske** [comment]
You are welcome. Marking issue closed.
