### ISSUE TITLE
RSA padding ignored on EVP_DigestVerifyFinal

### ISSUE THREAD

**Issue by bgermann** [wolfSSL/wolfssl#3313]
After setting RSA PSS padding via EVP_PKEY_CTX_set_rsa_padding(..., RSA_PKCS1_PSS_PADDING), calling EVP_DigestVerifyFinal ignores the padding and handles the verification as if RSA_PKCS1_PADDING was set.

**Comment by dgarske** [comment]
@julek-wolfssl , would you mind looking into this report?

**Comment by julek-wolfssl** [comment]
I'm on it but I'm having some trouble with verifying the signature.

**Comment by julek-wolfssl** [comment]
A PR with a fix is available at #3335

**Comment by bgermann** [comment]
The fix is functional, however there is an issue with the default salt length. See PR.

**Comment by julek-wolfssl** [comment]
PR #3335 has been merged to the master branch. Thanks @bgermann for your report.
