### ISSUE TITLE
wolfssl 4.5.0:  wolfcrypt/test/ linking fails when is OPENSSL_EXTRA feature is not enabled

### ISSUE THREAD

**Issue by e2iplayer** [wolfSSL/wolfssl#3390]
As in the subject.
When during configure all features enabling OPENSSL_EXTRA will be disabled then build fails with following linker error: 
/usr/local/bin/ld: wolfcrypt/test/test.o: in function `EVP_test':
test.c:(.text+0x4672): undefined reference to `wolfSSL_EVP_CIPHER_CTX_init'
....
many unresolved symbols

**Comment by kaleb-himes** [comment]
@e2iplayer,

The report is unclear, can you please provide the entire configure command being tested to reproduce this issue?

Thanks!

- K
