### ISSUE TITLE
error "undefined reference to `XREALLOC'" during linking

### ISSUE THREAD

**Issue by r44083** [wolfSSL/wolfssl#340]
I try to use wolfssl with embedded STM32F407 MCU.
So, I configured the library (file wolfssl\wolfcrypt\settings.h) like this:
```c
#define WOLFSSL_USER_IO
#define NO_WRITEV
#define NO_FILESYSTEM
#define WOLFSSL_STATIC_RSA
#define WOLFSSL_STATIC_DH
#define USE_CERT_BUFFERS_2048
#define STATIC_CHUNKS_ONLY
#define NO_WOLFSSL_MEMORY
```
Also, I have this define too:
```c
/* Uncomment next line if using FreeRTOS */
#define FREERTOS
```
But I still have a problem during building the project: error during linking
```
undefined reference to `XREALLOC'
```
but when I use "#define NO_WOLFSSL_MEMORY", I get different error from linker
```
final link failed: Memory exhausted.
```
(I use GNU Tools for ARM Embedded Processors 4.8.1)

Could you please explain me what I am doing wrong?

**Comment by cconlon** [comment]
Closing, as this was handled through wolfSSL support channel instead.
