### ISSUE TITLE
How to decode PKCS#7 signed data or how to convert pkcs7 file ( PKCS#7 signed data) to .crt file

### ISSUE THREAD

**Issue by WKJay** [wolfSSL/wolfssl#3429]

**Comment by kaleb-himes** [comment]
@WKJay, please checkout our suite of PKCS7 examples here: https://github.com/wolfSSL/wolfssl-examples/tree/master/pkcs7

Thanks!

- KH

**Comment by WKJay** [comment]
Thanks a lot!
