### ISSUE TITLE
How to get finished message

### ISSUE THREAD

**Issue by WKJay** [wolfSSL/wolfssl#3484]
I have found that current version of wolfssl does not support  "SSL_get_finished" function, is there any possible to get the finished message ?

**Comment by tmael** [comment]
Hi @WKJay 

Thanks for filing this issue. 

Can you tell us more about your project? 

SSL_get_finished and SSL_get_peer_finished functions are unavailable at the moment. AFIK, I don't think wolfSSL has the capability to allow applications to obtain the latest Finished messages sent to or expected from a peer. 
We'll be more than happy to add this to our OpenSSL compatibility expansion backlog. When do you need it? 

Best Regards,
Tesfa

**Comment by WKJay** [comment]
Hi @tmael

Thanks for your reply.

I am recently working on  EST protocal. In this protocol, when I generate certificate signing request, I need to embed tls-unique information in it, which refers to the finished message. 

That's why I need this feature. But I am not in a hurry because I have found a way to obtain the latest finished message by modifying source code and it seems to work fine.

If this feature could be added in the future release, it will be very nice :)

Regards,
Jay

**Comment by tmael** [comment]
Hi Jay,

Thanks for your project info! 
I'm glad you managed to obtain the Finished msg.  Would you mind sharing how you accomplished that? 

Thanks,
Tesfa

**Comment by WKJay** [comment]
Hi Tesfa,

Of course I can share.

I found that wolfssl sends finished message use `SendFinished` function, which defined in `internal.c`. And in this funcion, it invokes `BuildFinished`  to build finished message. So I simply copy the buffer contains finished message to my own buffer after `BuildFinished`.

```C

/* make finished hashes */
    hashes = (Hashes*)&input[headerSz];
    ret = BuildFinished(ssl, hashes,
                     ssl->options.side == WOLFSSL_CLIENT_END ? client : server);
    if (ret != 0) return ret;
   
    XMEMCPY(finished_msg,hashes,TLS_FINISHED_SZ);  //THIS IS MY CODE 

```

I don't know if this operation is correct but I can acturally get what I want in this way .

Best Regards,
Jay

**Comment by tmael** [comment]
@WKJay. Thanks for sharing. Looks good to me. 
BTW, feel free to send any questions to support@wolfssl.com.

**Comment by WKJay** [comment]
@tmael Thanks for the reply :)

**Comment by tmael** [comment]
You are welcome @WKJay!  I will go ahead and close out this issue. If any other questions come up, please do not hesitate to open a new issue or email support@wolfssl.com
