### ISSUE TITLE
Connect to AWS IoT Core failed, error code -188

### ISSUE THREAD

**Issue by Shaing** [wolfSSL/wolfssl#3491]
Hi,

I has surveyed for two days, and I am stuck.
I has tried below conditions
1. connect wo SNI
![image](https://user-images.githubusercontent.com/19544390/98885657-649f7700-24cd-11eb-8aff-32bae18ef8a6.png)

2. W/SNI
![image](https://user-images.githubusercontent.com/19544390/98885760-944e7f00-24cd-11eb-90a8-847d7139e908.png)

both of the result was -188, ASN no signer error to confirm failure.

Did I lost something? or has there successful experience can share some tip for me? or others issue? 

Thx,
A.H.

**Comment by tmael** [comment]
Hi @Shaing,

Thanks for reaching out! 
I suspect the likely cause is a missing signer CA. 
Can you double-check that ./certs/AmazonRootCA1.pem is the Certificate Authority?

Does the X509v3 cert extensions contain the following?
```
$ openssl x509 -in ./certs/AmazonRootCA1.pem -noout -text
...
            X509v3 Basic Constraints: 
                CA:TRUE

```

Thanks,
Tesfa

**Comment by Shaing** [comment]
Hi @tmael 

Thanks for reply fast.

and YES, here is following
```
$ openssl x509 -in AmazonRootCA.pem -noout -text
X509v3 extensions:
            X509v3 Basic Constraints: critical
                CA:TRUE
            X509v3 Key Usage: critical
                Digital Signature, Certificate Sign, CRL Sign
```

**Comment by tmael** [comment]
Hi @Shaing,

Thanks for the info!  But you were using AmazonRootCA1.pem, not AmazonRootCA.pem when launching your client application.

**Comment by Shaing** [comment]
Hi @tmael,

It's same file but different name that I has confirmed.
Sorry for this confused.

**Comment by Shaing** [comment]
Hi @tmael ,
If OK, could you try it again from AWS IoT Core(free) and analyse the root cause? It's very helpful for me and Embedded development.

Thank you so much.
A.H.

**Comment by tmael** [comment]
Hi @Shaing,

I'm unsure where you got your `AmazonRootCA.pem`. 

I was able to connect with the following:
$ ./examples/client/client -h a21fz4ez46exvr-ats.iot.us-west-2.amazonaws.com -p 8883 -A certs/sf-class2-root.crt

`sf-class2-root.crt` was obtained by clicking the `here` link on this page:
https://aws.amazon.com/blogs/security/how-to-prepare-for-aws-move-to-its-own-certificate-authority/
* Note: Amazon doesn’t own this root and doesn’t have a test URL for it. The certificate can be downloaded from here.

Could you let me know if that works for you? 

Thanks

**Comment by Shaing** [comment]
Hi @tmael ,

Yeah !!!
It works!!! Thank you so much.

and reply where is AmazonRootCA.pem from https://docs.aws.amazon.com/iot/latest/developerguide/server-authentication.html
```
RSA 2048 bit key: Amazon Root CA 1.
```

The cert file info. is from AWS demo scenario.

Thx,
A.H.

**Comment by tmael** [comment]
@Shaing, 
Glad it worked for you! 
I will go ahead and close out this issue. If any other questions come up, please do not hesitate to open a new issue or email support@wolfssl.com
