### ISSUE TITLE
Can mp_read_unsigned_bin / mp_to_unsigned_bin_at_pos support non-MP_8BIT?

### ISSUE THREAD

**Issue by reasly** [wolfSSL/wolfssl#3539]
Take mp_read_unsigned_bin for example, the following code will caue a->used to increase TOO fast, if it is not MP_8BIT. Later in clamp, the out of bound a->used will cause array out of bound.
Suggest to remove " a->used += xx" statement, and add a  "  a->used  = a-> alloc ; "  before  mp_clamp (a);

`int mp_read_unsigned_bin (mp_int * a, const unsigned char *b, int c)
{
  int     res;

  /* make sure there are at least two digits */
  if (a->alloc < 2) {
     if ((res = mp_grow(a, 2)) != MP_OKAY) {
        return res;
     }
  }

  /* zero the int */
  mp_zero (a);

  /* read the bytes in */
  while (c-- > 0) {
    if ((res = mp_mul_2d (a, 8, a)) != MP_OKAY) {
      return res;
    }

#ifndef MP_8BIT
      a->dp[0] |= *b++;
      a->used += 1;
#else
      a->dp[0] = (*b & MP_MASK);
      a->dp[1] |= ((*b++ >> 7U) & 1);
      a->used += 2;
#endif
  }
  mp_clamp (a);
  return MP_OKAY;
}`

**Comment by tmael** [comment]
Hi @reasly,

Thanks for contacting wolfSSL support! 
Would you like to submit a pull request with your proposed changes?
