### ISSUE TITLE
wolfssl 4.6.0: the tls13.test scripts fail when --enable-earlydata

### ISSUE THREAD

**Issue by xielizyh** [wolfSSL/wolfssl#3597]
Hi, 
  when using the latest wolfssl 4.6.0 version, the `tls13.test` scripts test failed with the config: `./configure --enable-debug --enable-psk --enable-earlydata`.  But it is passed when using in wolfssl  4.5.0 version. The test-suite.log is as follows:
[test-suite.log](https://github.com/wolfSSL/wolfssl/files/5741077/test-suite.log)

**Comment by tmael** [comment]
Hi @xielizyh,

Thanks for contacting wolfSSL! 

Looks like a typo in the test tls13.test script. This change should resolve the issue. 

```
$ git diff
diff --git a/scripts/tls13.test b/scripts/tls13.test
index 9c861b51f..e747dcfba 100755
--- a/scripts/tls13.test
+++ b/scripts/tls13.test
@@ -280,7 +280,7 @@ if [ "$early_data" = "yes" -a "$psk" = "yes" ]; then
     RESULT=$?
     remove_ready_file
     early_data_cnt=`grep 'Early Data' $server_out_file | wc -l`
-    if [ $early_data_cnt -ne 2 ]; then
+    if [ $early_data_cnt -ne 4 ]; then
         RESULT=1
     fi
     if [ $RESULT -ne 0 ]; then
```
