### ISSUE TITLE
Link-time error for some functions when using --enable-sp-math

### ISSUE THREAD

**Issue by guidovranken** [wolfSSL/wolfssl#3615]
Several functions are declared in the `sp_int.h` header, but not implemented or exported when wolfCrypt is compiled with `--enable-sp-math`.

Eg. the following program:

```c
#include <wolfssl/options.h>
#include <wolfssl/wolfcrypt/integer.h>

#define CF_CHECK_EQ(expr, res) if ( (expr) != (res) ) { goto end; }

int main(void)
{    
    printf("%p %p %p %p %p\n", mp_montgomery_setup, mp_montgomery_calc_normalization, mp_montgomery_reduce, sp_mul_2d, mp_mul_2d);
    return 0;
}
```

results in these link-stage errors:

```
p.c:8: undefined reference to `sp_mont_setup'
p.c:8: undefined reference to `sp_mont_norm'
p.c:8: undefined reference to `sp_mont_red'
p.c:8: undefined reference to `sp_mul_2d'
p.c:8: undefined reference to `sp_mul_2d'
```

The solution to this is probably that these function declarions in `sp_int.h` should probably be wrapped in blocks like:

```c
#ifdef WOLFSSL_SP_MATH_ALL
(declarations here)
#endif
```

**Comment by SparkiDev** [comment]
Hi @guidovranken
I've put up a pull request that wraps the function declarations I believe need to be protected.
Let me know if there is anything else.

**Comment by guidovranken** [comment]
Thanks.
