### ISSUE TITLE
AESNI enabled aesgcm cann't decrypt block that big than 256M in Visual Studio 2017(Win10)

### ISSUE THREAD

**Issue by peteryxk163** [wolfSSL/wolfssl#3746]
I'm using aesgcm with AESNI enabled  in Win10 & Visual Studio 2017.
When I encrypt and decrypt big file(256M), Decryption alwarys failed with AES_GCM_AUTH_E.
But when the Size is 256M-1, or little , It will success.

**Comment by tmael** [comment]
Hi @peteryxk163,

Let's continue the discussion on ZD#11487.

Thanks,
Tesfa

**Comment by tmael** [comment]
Fix via #3747
