### ISSUE TITLE
Windows Visual Studio "wolfSSL error: can't load ca file, Please run from wolfSSL home dir"

### ISSUE THREAD

**Issue by linghu258** [wolfSSL/wolfssl#3788]
Hi, I am having some difficulty running wolfSSL in visual studio. I was following the wolfSSL guide "https://www.wolfssl.com/docs/visual-studio/" and I encounter the error message: "wolfSSL error: can't load ca file, Please run from wolfSSL home dir" when I tried running client and server instances. How do I go about solving this issue? 

I am using wolfSSL-3.15.7 for a school project

**Comment by Wang-jiong-han** [comment]
I ran into the same problem. How did you fix this

**Comment by anhu** [comment]
Hi, can you open a terminal and change directory into the wolfssl directory and then execute the server from there? 

Also do the same for the client in another terminal as well. 

```
cd c:\path\to\wolfssl
examples\server\server.exe
```

```
cd c:\path\to\wolfssl
examples\client\client.exe
```


Warm regards, Anthony
