### ISSUE TITLE
wolfSSL fails to compile with SHA-512 and AES-GCM enabled without SHA-384 enabled

### ISSUE THREAD

**Issue by aburks** [wolfSSL/wolfssl#38]
wolfSSL fails to compile with SHA-512 (`WOLFSSL_SHA512`) and AES-GCM (`HAVE_AESGCM`) enabled without SHA-384 enabled because the `enum` `SHA384` is defined here: https://github.com/wolfSSL/wolfssl/blob/master/wolfssl/wolfcrypt/sha512.h#L74 

and then again here:
https://github.com/wolfSSL/wolfssl/blob/master/wolfssl/wolfcrypt/hmac.h#L87

**Comment by toddouska** [comment]
Thanks for the report, now fixed.
