### ISSUE TITLE
Add capabilities of enable-reproducible-builds to the CMake build

### ISSUE THREAD

**Issue by hcorion** [wolfSSL/wolfssl#3887]
Would love to see the work done here https://github.com/wolfSSL/wolfssl/pull/3745 put into the CMake build system, since some of us are building WolfSSL via CMake.

**Comment by haydenroche5** [comment]
Hi @hcorion. I will add this to my to-do list. I'm the primary maintainer of the CMake stuff for wolfSSL.

**Comment by haydenroche5** [comment]
@hcorion I added this with https://github.com/wolfSSL/wolfssl/pull/4014.
