### ISSUE TITLE
undefined reference to `wc_InitCert'

### ISSUE THREAD

**Issue by srieyulianti** [wolfSSL/wolfssl#3927]
Hi wolfssl team,

I am trying to generate X509 certificate by using the wolfSSL library. However, I got some issues as follows that mentioned undefined reference for some functions. I create a C file in the src folder and put the wolfSSL library in the include folder. I am running the program in Ubuntu machine 18.04. 

> main.c:(.text+0x232): undefined reference to `wc_InitCert'
> main.c:(.text+0x328): undefined reference to `wc_InitRng'
> main.c:(.text+0x33c): undefined reference to `wc_InitRsaKey'
> main.c:(.text+0x35f): undefined reference to `wc_MakeRsaKey'
> main.c:(.text+0x3ae): undefined reference to `wc_MakeSelfCert'
> collect2: error: ld returned 1 exit status

Here is the headers in C file:
#include <wolfssl/options.h>
#include <wolfssl/ssl.h>
#include <wolfssl/wolfcrypt/settings.h>
#include <wolfssl/wolfcrypt/asn.h>
#include <wolfssl/wolfcrypt/asn_public.h>
#include <wolfssl/wolfcrypt/coding.h>
#include <wolfssl/wolfcrypt/rsa.h>
#include <wolfssl/wolfcrypt/sha256.h>

I followed the installation process from wolfSSL website:

> ./configure
> make install

I am quite new with C programming language and wolfSSL especially. Did I make something wrong during installation process?
Thank you in advance for your help!

Best Regards,
Sri Yulianti

**Comment by embhorn** [comment]
Hello Sri,

I believe we answered your question in our Zendesk support platform, but I'll go ahead and post the solution here for posterity:

> Likely, you just need to enable support for those components in the configuration. To quickly get most of the library enabled, you can use ./configure --enable-all

Thanks,
@embhorn
