### ISSUE TITLE
TLS 1.3 - Client Certificate Request Callback Support

### ISSUE THREAD

**Issue by hicksjacobp** [wolfSSL/wolfssl#3928]
**Original community support request:** <https://wolfssl.zendesk.com/hc/en-us/community/posts/360077574892-TLS-1-3-Client-Certificate-Request-Callback-Support>

We are using WolfSSL for TLS communication, specifically 1.3.

We are looking to make use of TLS Post Handshake Authentication, in which the server makes a certificate request to the client after the client attempts to initiate the connection. This is because our client needs to present a unique certificate based on what the server trusts, and without human user intervention. It appears that WolfSSL does not make use of the `CBClientCert` callback for TLS 1.3 as it does for TLS 1.2. This means that as a consumer of WolfSSL, we can't define a callback to handle the server's certificate request for providing the client certificate and private key, unless there's something we're missing or overlooking.

It appears that `CBClientCert` calls were introduced in <https://github.com/dgarske/wolfssl/commit/2553390e6442e8a4ddc41aab583424e71b0c597c> (PR: <https://github.com/wolfSSL/wolfssl/pull/2466>). Currently, `CBClientCert` is only called in `src/internal.c` `DoCertificateRequest`.

`CBClientCert` specifically appears to be missing from `src/tls13.c` `DoTls13CertificateRequest` or `SendTls13Certificate`. We have a developer that made some changes in `SendTls13Certificate`, and wanted to verify them with WolfSSL maintainers to determine if they were appropriate, and also ask if this is on the roadmap to be supported by the WolfSSL library. You can view the proposed changes compared against `wolfssl/master` here: <https://github.com/wolfSSL/wolfssl/compare/master...hicksjacobp:tls13-cbclientcert?expand=1>. ~~I will be making a pull request shortly with these changes.~~ See #3929 for possible proposal to fix.

If there is something we're overlooking, then please instruct us how to proceed.

**Comment by SparkiDev** [comment]
Hi @hicksjacobp,

The pull request has been merged.

Thanks for providing a pull request for this issue!
