### ISSUE TITLE
Unifying error handling of GetASNTag()

### ISSUE THREAD

**Issue by ErrReporter** [wolfSSL/wolfssl#3936]
GetASNTag()
https://github.com/wolfSSL/wolfssl/blob/master/wolfcrypt/src/asn.c#L239
has many meaningful error codes like `BAD_FUNC_ARG` and `BUFFER_E`.

We observed that in many cases, `GetASNTag()`'s error codes are all converted to `ASN_PARSE_E` or unified to `BUFFER_E`. At least, this makes an inconsistency, otherwise, all users of this function should report the same error.

For example:
https://github.com/wolfSSL/wolfssl/blob/fd94d05b0a40473c2ad267fd5a8c0394eee8631a/wolfcrypt/src/asn.c#L771-L773
https://github.com/wolfSSL/wolfssl/blob/fd94d05b0a40473c2ad267fd5a8c0394eee8631a/wolfcrypt/src/asn.c#L959-L961

**Comment by embhorn** [comment]
Hi @ErrReporter 

The context of the call to `GetASNTag()` is important, and this is reflected in the modified return value. It would be more consistent the way you mention, but it would lose important debugging value to make the error codes homogenous.

Thanks,
@embhorn wolfSSL Support
