### ISSUE TITLE
wolfssl/IDE/Espressif/ESP-IDF/setup_win.bat doesn't work correctly under win10 powershell

### ISSUE THREAD

**Issue by thegoodhen** [wolfSSL/wolfssl#3978]
Calls to xcopy where the source directory address ends with a backslash fail, leaving the wolfSSL library in a misconfigured state. 

This general problem with xcopy is described in https://stackoverflow.com/questions/25840861/invalid-path-0-files-copied-error-while-using-xcopy-command

This can be fixed by removing the extra backslash. If you want, I can submit a pull request tomorrow? Thank you.

**Comment by embhorn** [comment]
Hi @thegoodhen 

Could you please confirm that #3980 corrects the batch file issue?

Kind regards,
@embhorn

**Comment by thegoodhen** [comment]
> Hi @thegoodhen
> 
> Could you please confirm that #3980 corrects the batch file issue?
> 
> Kind regards,
> @embhorn

Hello, it seems fine now. I tried running it and there were no errors. Thank you for your quick response. David
