### ISSUE TITLE
Is there plan to support deb package?

### ISSUE THREAD

**Issue by hustliyilin** [wolfSSL/wolfssl#3989]
I'm a user of ubuntu, Is there plan to support the wolfssl deb package? Thanks a  lot.

**Comment by dgarske** [comment]
@lechner, can you answer this?

These links might be useful:
https://packages.debian.org/search?keywords=wolfssl
https://repology.org/project/wolfssl/versions
https://tracker.debian.org/pkg/wolfssl

Thanks, David Garske, wolfSSL

**Comment by hustliyilin** [comment]
> @lechner, can you answer this?
> 
> These links might be useful:
> https://packages.debian.org/search?keywords=wolfssl
> https://repology.org/project/wolfssl/versions
> https://tracker.debian.org/pkg/wolfssl
> 
> Thanks, David Garske, wolfSSL

Thank you for your quick reply. The information you provided is enough for me, thanks again.
