### ISSUE TITLE
Can base64 encode / decode be public?

### ISSUE THREAD

**Issue by ekapke** [wolfSSL/wolfssl#40]
From coding.h:

/* decode needed by wolfSSL */
WOLFSSL_LOCAL int Base64_Decode(const byte* in, word32 inLen, byte* out,
                               word32* outLen);

Instead of pulling in a 3rd party base64 lib, would be excellent if wolf ssl users can use the base64 methods.

**Comment by toddouska** [comment]
Base64_Decode is now exported.  Base64_Encode can still be exported with any of the existing options or the new one WOLFSSL_BASE64_ENCODE to allow exporting of just that function w/o enabling the existing other options.
