### ISSUE TITLE
ChaCha20 with Poly1305 Fails to build

### ISSUE THREAD

**Issue by twilkerson1237** [wolfSSL/wolfssl#4008]
![ChaCha20Poly1305BuildFail](https://user-images.githubusercontent.com/79463048/117030181-5a687380-accd-11eb-860a-3cadb0f735e3.PNG)

**Comment by dgarske** [comment]
Hi @twilkerson1237 ,

Using ChaCha20 with Poly1305 and TLS requires `HAVE_ONE_TIME_AUTH` to be defined.

See:
https://github.com/wolfSSL/wolfssl/blob/master/wolfssl/internal.h#L4293
https://github.com/wolfSSL/wolfssl/blob/master/configure.ac#L3233

Thanks, David Garske, wolfSSL

**Comment by twilkerson1237** [comment]
Ah I missed that.
