### ISSUE TITLE
ssl.c fails to build with NO_DES3 defined

### ISSUE THREAD

**Issue by aburks** [wolfSSL/wolfssl#41]
ssl.c fails to build with `NO_DES3` defined because of the following lines: https://github.com/wolfSSL/wolfssl/blob/master/src/ssl.c#L2467-L2474

**Comment by cconlon** [comment]
Thanks for the catch.  Should be fixed as of https://github.com/wolfSSL/wolfssl/commit/6c963c8d8eb7c56766c0b94b715b53ec6886a9b6
