### ISSUE TITLE
Nginx Support with wolfSSL

### ISSUE THREAD

**Issue by myseemylife** [wolfSSL/wolfssl#413]
Sorry for oepning a issue asking this，
Does wolfSSL has been supported with Nginx？
we use openSSL or libreSSL，their static lib size both too big。

**Comment by cconlon** [comment]
Hi,

We have explored porting wolfSSL to nginx internally, but don't have anything publicly available yet.  We'd be happy to have a call to discuss your interests and what we have done so far.  If this would be of interest to you, send us an email to info@wolfssl.com and we can work on finding a time to talk.

Thanks,
Chris

**Comment by cconlon** [comment]
Hi,

Closing this issue for now.  Please feel free to reach out to us over email to continue the conversation!

Thanks,
Chris
