### ISSUE TITLE
justification for number of lines per file

### ISSUE THREAD

**Issue by M1cha** [wolfSSL/wolfssl#4195]
I noticed that wolfssl has exceptionally large C files with ssl.c being over 50k lines.
Are there technical and/or usability reasons for that?

Having to recompile that much code after changing one of those files may not matter with Cs quick compile-times, but I have a hard time understanding how to even comfortably work with such files as a developer - especially when you don't want to use a function index with your editor.

**Comment by kabuobeid** [comment]
Hi @M1cha,

There are a couple of reasons we have these high LoC files:
1) It allows more optimization in some older/embedded compilers, which may not optimize as strongly/at all across files as in the same file.
2) It reduces the number of files you have to load while working with wolfSSL across platforms.  This makes IDE integration simpler, for example.

I would suggest an IDE or an editor like VS Code or Sublime Text to work with these files comfortably.  We have various IDE examples in the IDE/ directory of our repo.

Thanks,
Kareem

**Comment by M1cha** [comment]
`1.` confirms my main theory - I don't know how big that effect is but it's definitely a good reason. Especially since in my experience LTO(which would solve the problem ignoring compiler compatibility) is untrustworthy and produces crashing binaries.

`2.` is a very interesting opinion that I've never heard before. In which way does it make it easier? Because there's less files in the file-list in all those build scripts(like Makefiles) that you have to maintain? why couldn't that list be in a central place so depending on the abilities of that build system you could either include that list or just generate the e.g. Makefile from that list?

I"m happy with neovim but thanks for the suggestion ;)

**Comment by kabuobeid** [comment]
For IDE integration, that is correct, it is far less files to have to add to each IDE.  Every IDE has a unique format so coming up with a script to generate IDE file lists would be a significant effort.
