### ISSUE TITLE
Unable to detect RNG health with --enable-intelrand

### ISSUE THREAD

**Issue by guidovranken** [wolfSSL/wolfssl#4239]
The DRBG random number generator can fail if an allocation failure occurs, e.g. here: https://github.com/wolfSSL/wolfssl/blob/3bb2d5525746b6a5d295d57789f2e08a33add740/wolfcrypt/src/random.c#L800

The user can check the RNG state by checking if `rng.status` equals `DRBG_OK`.

In case the RNG is not OK, it needs to be freed using `wc_FreeRng` and then re-initialized using `wc_InitRng`.

However when wolfCrypt is built with `--enable-intelrand` AND the underlying system has support for Intel RDSEED instructions, wolfCrypt will bypass the DRBG: https://github.com/wolfSSL/wolfssl/blob/3bb2d5525746b6a5d295d57789f2e08a33add740/wolfcrypt/src/random.c#L774

In that case, `status` will stay in the `DRBG_NOT_INIT` state.

This makes it difficult for the user to detect the RNG health/state.

I can think of two approaches to solving this:

- Set `status` to `DRBG_OK` when the Intel RDSEED generator is used.
- Implement a new dedicated RNG health function that can signal to the user when the RNG needs re-initializing.

Thoughts?

**Comment by ejohnstown** [comment]
@guidovranken, I made the change to set the status to DRBG_OK when using RDRAND. I also made similar changes for some of the other hardware we support.
