### ISSUE TITLE
HI！How can I use BN_dec2bn like OpenSSL when I use wolfssl?

### ISSUE THREAD

**Issue by Hoibben** [wolfSSL/wolfssl#4240]
My English is not good. How can I solve this problem? Thank you all!

**Comment by kabuobeid** [comment]
Hi @Hoibben ,

Thanks for reaching out to us.
It looks like we don't support `BN_dec2bn` just yet, this functions is still stubbed out unfortunately.
If this is an API you depend on, you can reach out to our sales team at facts@wolfssl.com

Thanks,
Kareem

**Comment by Hoibben** [comment]
@kabuobeid 
I've solved.
Thanks.
