### ISSUE TITLE
Access to struct member after clearing memory?

### ISSUE THREAD

**Issue by rliebscher** [wolfSSL/wolfssl#4246]
This piece of code seems a little bit weird.

```
/* free any resources, clear any keys */
void wc_ecc_ctx_free(ecEncCtx* ctx)
{
    if (ctx) {
        ForceZero(ctx, sizeof(ecEncCtx));
        XFREE(ctx, ctx->heap, DYNAMIC_TYPE_ECC);
    }
}
```
If the memory of ctx is cleared to zero, then ctx->heap will always read 0.

**Comment by dgarske** [comment]
Thank you @rliebscher for this report. I've put up a fix here: https://github.com/wolfSSL/wolfssl/pull/4249

Thanks,
David Garske, wolfSSL
