### ISSUE TITLE
SRP with SHA2-384/512 proof failing

### ISSUE THREAD

**Issue by dgarske** [wolfSSL/wolfssl#4278]
See PR https://github.com/wolfSSL/wolfssl/pull/4270
If `srp_test` uses `SRP_TYPE_SHA384` or `SRP_TYPE_SHA512` the `wc_SrpVerifyPeersProof` fails with `SRP_VERIFY_E`.
Reviewed code for a bit and could not see any reason for this failure. Recommend assigning this issue to Sean P when he returns.

**Comment by SparkiDev** [comment]
Issue comes from the N being too small.
#4307 uses a longer N and tests with all four supported digests.
