### ISSUE TITLE
404 example config link

### ISSUE THREAD

**Issue by gojimmypi** [wolfSSL/wolfssl#4289]
The `examples/configs/README.md` link on the [examples page](https://github.com/wolfSSL/wolfssl/tree/master/examples#configs) is 404 and I'm not sure where it should go to create a PR.

**Comment by dgarske** [comment]
Hi @gojimmypi , thanks for pointing this out. @lealem47 will put up a fix.

**Comment by lealem47** [comment]
Thanks for noticing @gojimmypi.
