### ISSUE TITLE
ER: Set memory for ecc.c to be DYNAMIC_TYPE_ECC instead of DYNAMIC_TYPE_BIGINT

### ISSUE THREAD

**Issue by aburks** [wolfSSL/wolfssl#43]
It'd be great if the memory allocated by `XMALLOC` in ecc.c was set to the type `DYNAMIC_TYPE_ECC` rather than `DYNAMIC_TYPE_BIGINT` because it would help a lot in tracking down memory issues related to ECC. Here are the specific lines:

https://github.com/wolfSSL/wolfssl/blob/master/wolfcrypt/src/ecc.c#L1382
https://github.com/wolfSSL/wolfssl/blob/master/wolfcrypt/src/ecc.c#L1396
https://github.com/wolfSSL/wolfssl/blob/master/wolfcrypt/src/ecc.c#L1421

**Comment by toddouska** [comment]
Thanks!  Fixed.
