### ISSUE TITLE
Latest stable release doesn't seem to include a configuration file 

### ISSUE THREAD

**Issue by nihalpasham** [wolfSSL/wolfssl#4304]
I may be missing something but here's what I get when I attempt to configure an installation. 

![image](https://user-images.githubusercontent.com/20253082/129487135-4cd6f888-6a0a-4c8d-9103-6945599c8548.png)

**Comment by kaleb-himes** [comment]
@nihalpasham, when pulling releases from github it is necessary to run `./autogen.sh` first to generate the configure script. 

We recommend instead downloading the official package from our website here: https://www.wolfssl.com/download/

The wolfssl-4.8.1.zip will always come with a read-to-use configure script.

Warm Regards,

KH
