### ISSUE TITLE
Feature Request: Port wolfSSL to vcpkg

### ISSUE THREAD

**Issue by Kiddinglife** [wolfSSL/wolfssl#4323]

**Comment by dgarske** [comment]
Hi Jake,

Re #3226. The feature request for "Port wolfSSL to vcpkg" is on our list to consider. If you are interested in providing some context to help us justify accelerating this work this please email facts@wolfssl.com with details.

Thanks,
David Garske, wolfSSL

**Comment by al-sabr** [comment]
Plugin wolfSSL inside of any C++ Cmake project would improve the package dependency management. OpenSSL is already ported to vcpkg and everyone is using it. If you want us to switch to wolfSSL this a good motivator.

**Comment by elms** [comment]
@Kiddinglife @al-sabr Good news, I have put a draft [PR](https://github.com/microsoft/vcpkg/pull/24348) to add vcpkg support. I'll work through the open issues and target merging after the next wolfSSL release.

**Comment by elms** [comment]
vcpkg for wolfSSL, wolfMQTT, and wolfTPM have merged https://github.com/microsoft/vcpkg/pull/24348
