### ISSUE TITLE
An improper locking bug(e.g., deadlock) on caam.ring.jr_lock

### ISSUE THREAD

**Issue by ycaibb** [wolfSSL/wolfssl#4376]
Hi, developers, thank you for your checking. It seems the lock `caam.ring.jr_lock` is not released correctly when `CAAM_ADR_SYNC(caam.ring.VirtualDesc, desc->idx * sizeof(unsigned int)) != 0` and other similar conditions in the function `caamAddJob`?
https://github.com/wolfSSL/wolfssl/blob/5dff4dd4e0f6fa0e2f74a74efc5d47497c17f65f/wolfcrypt/src/port/caam/caam_driver.c#L541-L591

Best,

**Comment by JacobBarthelmeh** [comment]
Hi @ycaibb ,

Thanks for the report. Visually looking at the code sections it does look like there is a couple return spots on unexpected error cases where not unlocked.

Regards,
Jacob
