### ISSUE TITLE
Big number modular exponentiation error

### ISSUE THREAD

**Issue by h1994st** [wolfSSL/wolfssl#4479]
Hi,

I try to calculate modular exponentiation, using the big number API in wolfSSL:

```c
// set `bn_two` to constant 2
BIGNUM *bn_two = BN_new();
BN_init(bn_two);
BN_set_word(bn_two, 2);

// r = 2 ^ p (mod m)
int ret = BN_mod_exp(r, bn_two, p, m, NULL);
```

However, `ret` is always `WOLFSSL_FAILURE`, if `p` is not odd. The error is triggered by the following code snippet:

https://github.com/wolfSSL/wolfssl/blob/60adf22ce1e74cbfc5a65f9b0c07d294e8b9d04d/wolfcrypt/src/tfm.c#L3308-L3310

Is `BN_mod_exp` designed not to handle even exponents? I am wondering if there are any alternative APIs that I can use for modular exponentiation. Thanks.

**Comment by julek-wolfssl** [comment]
I can investigate tomorrow.

**Comment by SparkiDev** [comment]
@h1994s BN_mod_exp(r, bn_two, p, m, NULL) => r = 2^p mod m

The operation is being done in Montgomery form which requires an odd modulus.
We could add the option of not doing it Montgomery form if the modulus is even.

But, the question is why do you have an even modulus (m)?

**Comment by h1994st** [comment]
@SparkiDev Thanks! I will try those configurations at first.

**Comment by h1994st** [comment]
Hi @SparkiDev , I tried the latest master branch, and my code works now. Thanks very much for your help!
