### ISSUE TITLE
ASN Signer -188 error for Let's Encrypt update and WOLFSSL_ALT_CERT_CHAINS solution

### ISSUE THREAD

**Issue by agathauy** [wolfSSL/wolfssl#4611]
Hello, referencing issue #4443 and the noted solution there, I would like to confirm if the following is what should be done for microcontrollers (for this case using an Arduino):
1. Adding `#define WOLFSSL_ALT_CERT_CHAINS`
2. Changing the pem text file to the updated one https://www.identrust.com/node/1330 with `openssl pkcs7 -inform DER -in IdenTrustCommercialRootCA.p7b -print_certs -outform PEM -out trustidrootx3_chain.pem`

Because currently, I'm still getting an ASN Signer -188 error for this. The arduino code used to run this was working prior to the let's encrypt update.

Just to check I tried to change  `wolfSSL_CTX_set_verify(ctx, SSL_VERIFY_PEER, 0);` to `wolfSSL_CTX_set_verify(ctx, SSL_VERIFY_NONE, 0);`. And so it works this way, but I believe this isn't ideal since the client couldn't verify the server's certificate?

For reference, below is the code I have for setting up wolfSSL. Thanks in advance for any help on this!

```
// near the top of the code #define WOLFSSL_ALT_CERT_CHAINS

WOLFSSL_METHOD* method;

// If not init, then ctx is not null
if (ctx != NULL) {
    Serial.println(F("[wolfSSLSetup]: ctx not null, so freed"));

    wolfSSL_CTX_free(ctx); ctx = NULL;
}

// Enable logging
wolfSSL_Debugging_ON();

wolfSSL_SetLoggingCb(&wolfssl_custom_logging_cb);

wolfSSL_UseSupportedCurve(ssl, WOLFSSL_ECC_SECP160K1);
method = wolfTLSv1_2_client_method();
//method =  wolfSSLv23_client_method();
//method = wolfTLSv1_3_client_method();
if (method == NULL) {
    Serial.println(F("[wolfTLSv1_2_client_method] unable to get method"));
    return -1;
}
ctx = wolfSSL_CTX_new(method);
if (ctx == NULL) {
    Serial.println(F("[wolfSSL_CTX_new] unable to get ctx"));
    return -1;
}

/* Add cert to ctx */
int x =     wolfSSL_CTX_load_verify_buffer(ctx, ROOT_CERTS_PEM,size_cert, WOLFSSL_FILETYPE_PEM);
int err            = 0;
char errBuf[81];

if (x != WOLFSSL_SUCCESS) {
    Serial.println(F("WolfSSL not success with ctx load"));
    err = wolfSSL_get_error(ssl, 0);
    wolfSSL_ERR_error_string_n(err, errBuf, 80);
    Serial.print(F("ERR wolfSSL_CTX_Load_verify_buffer: "));
    Serial.println(errBuf);
    return -1;
}

if (wolfSSL_CTX_UseSNI(ctx, 0, host, (word16) XSTRLEN(host)) != WOLFSSL_SUCCESS) {
    Serial.println(F("WolfSSL failed UseSNI"));

    wolfSSL_CTX_free(ctx); ctx = NULL;
    Serial.println(F("UseSNI failed"));
    //err_sys("UseSNI failed"));
    return -1;
}
// initialize wolfSSL using callback functions
//wolfSSL_CTX_set_verify(ctx, SSL_VERIFY_NONE, 0);
wolfSSL_CTX_set_verify(ctx, SSL_VERIFY_PEER, 0);

wolfSSL_SetIOSend(ctx, EthernetSend);
wolfSSL_SetIORecv(ctx, EthernetReceive);

Serial.println(F("Setup success!"));
```

**Comment by kareem-wolfssl** [comment]
Hi @agathauy ,

Yes, ALT_CERT_CHAINS + SNI is all you should need to get Let's Encrypt sites working again.  Is your site using Let's Encrypt?  If so, give this cert a try instead: https://letsencrypt.org/certs/isrgrootx1.pem
Let's Encrypt's updated X3 root from Identrust which you linked doesn't match the signature of the old X3 root, so we won't use it in an alt cert chain.  The X1 root I linked does match the cross-signed X1's signature, and is self-signed so we will use it as a CA with alt cert chains enabled.

Thanks,
Kareem

**Comment by agathauy** [comment]
Thanks so much for replying fast @kareem-wolfssl ! Will test this out :D

**Comment by kareem-wolfssl** [comment]
Hi @agathauy ,

Did my previous suggestion help?  Are you still seeing this issue?

**Comment by kareem-wolfssl** [comment]
I am closing this issue as we have not heard back in some time, please feel free to re-open it if you are still experiencing this issue.  Thanks!
