### ISSUE TITLE
Suggestions about error handlings for locking

### ISSUE THREAD

**Issue by ryancaicse** [wolfSSL/wolfssl#4653]
Hi, developers, I have a suggestion about error handlings for locking. Would it be better to handle the possible errors that return from pthread_mutex_lock.

For example, this example does not check the value returned by pthread_mutex_lock() for errors. If pthread_mutex_lock() cannot acquire the mutex for any reason, the function may introduce a race condition into the program (CWE-413).

The manners of error handlings could be flagging any warnings or returning before accessing the critical region.

```
void f(pthread_mutex_t *mutex) {
pthread_mutex_lock(mutex);

/* access shared resource */


pthread_mutex_unlock(mutex);
}
```
Handle
https://github.com/wolfSSL/wolfssl/blob/0e18e9c4047c84c011a5bddf085f7b4d81aa6c05/wolfcrypt/src/port/intel/quickassist_sync.c#L555-L559

Do not handle
https://github.com/wolfSSL/wolfssl/blob/5dff4dd4e0f6fa0e2f74a74efc5d47497c17f65f/wolfcrypt/src/port/caam/caam_qnx.c#L539-L541

**Comment by JacobBarthelmeh** [comment]
Thanks for the report @ryancaicse, we merged in some changes to check the return value of all pthread mutex locks in that file.
