### ISSUE TITLE
unresolved external symbol InetPton

### ISSUE THREAD

**Issue by namazso** [wolfSSL/wolfssl#4684]
```
C:\Downloads\wolfssl-master\src\ssl.c(49537,9): warning C4013: 'InetPton' undefined; assuming extern returning int [C
:\Downloads\wolfssl-master\wolfssl.vcxproj]
```

... later ...

```
"C:\Downloads\wolfssl-master\wolfssl64.sln" (Build target) (1) ->
"C:\Downloads\wolfssl-master\examples\echoserver\echoserver.vcxproj" (default target) (5) ->
  wolfssl.lib(ssl.obj) : error LNK2001: unresolved external symbol InetPton [C:\Downloads\wolfssl-master\examples\echos
erver\echoserver.vcxproj]
  C:\Downloads\wolfssl-master\x64\Release\echoserver.exe : fatal error LNK1120: 1 unresolved externals [C:\Downloads\wo
lfssl-master\examples\echoserver\echoserver.vcxproj]
```

if windows headers were included, InetPton would be defined as InetPtonW and not error out. Repro:

clone master, then in visual studio 2019 x64 powershell:

```
 echo "#ifndef _WIN_USER_SETTINGS_H_EXTRA_`n#define _WIN_USER_SETTINGS_H_EXTRA_`n#define OPENSSL_EXTRA`n#define OPENSSL_ALL`n#define WOLFSSL_ASIO`n#define ASIO_USE_WOLFSSL`n#define WOLFSSL_KEY_GEN`n#define BOOST_ASIO_USE_WOLFSSL`n#define HAVE_EX_DATA`n#define SSL_TXT_TLSV1_2`n#define SSL_TXT_TLSV1_1`n#define OPENSSL_NO_SSL2`n#define OPENSSL_NO_SSL3`n#endif`n" >> IDE\WIN\user_settings.h
 msbuild.exe /t:Build /p:WindowsTargetPlatformVersion=10 /p:PlatformToolset=v142 /p:Configuration=Release /p:Platform=x64 wolfssl64.sln
 ```

**Comment by embhorn** [comment]
Hi @namazso 

Are you building with VS? Which VS configuration are you building?

Thanks,
Eric - wolfSSL Support

**Comment by namazso** [comment]
yes, latest version of VS 2019.  Everything else is in the opening post, but I'll decipher the msbuild line for you:
`/p:WindowsTargetPlatformVersion=10 /p:PlatformToolset=v142`
retargeted for vs2019 toolset and latest win10 sdk (10.22000 on my system aka win11 sdk)
`/p:Configuration=Release`
Release config
`/p:Platform=x64`
On x64
`wolfssl64.sln`
all targets

**Comment by namazso** [comment]
for me the graphical IDE also reproduced the problems when doing the config changes (aka the echo line)

**Comment by embhorn** [comment]
Please try adding an include for `ws2tcpip.h`  in `wolfssl/wolfcrypt/wc_port.h`

```
diff --git a/wolfssl/wolfcrypt/wc_port.h b/wolfssl/wolfcrypt/wc_port.h
index eb4a4e0a4..e1d1c8be9 100644
--- a/wolfssl/wolfcrypt/wc_port.h
+++ b/wolfssl/wolfcrypt/wc_port.h
@@ -606,6 +606,7 @@

 /* THREADING/MUTEX SECTION */
 #ifdef USE_WINDOWS_API
+    #include <ws2tcpip.h>
     #ifdef WOLFSSL_GAME_BUILD
         #include "system/xtl.h"
     #else
```

**Comment by embhorn** [comment]
I can also confirm build errors with `OPENSSL_ALL` defined.

**Comment by duk-37** [comment]
relatively simple fix/workaround for this that works independent of include order: (`Windows.h` needs to be included before `ws2tcpip.h`)

(just needs to be above the two XINET_NTOP/XINET_PTON definitions)
```
#ifdef USE_WINDOWS_API
	#define _WINSOCKAPI_
	#include <Windows.h>
	#include <winsock2.h>
	#include <ws2tcpip.h>
#endif
```

**Comment by namazso** [comment]
@embhorn  i can confirm the patch works
