### ISSUE TITLE
5.0.0 --enable-asio without TLSv1.1

### ISSUE THREAD

**Issue by axawsi** [wolfSSL/wolfssl#4747]
When configuring with **--enable-asio**, it seems like the configure script adds the definitions for several wolfssl features which might actually be disabled:
https://github.com/wolfSSL/wolfssl/blob/master/configure.ac#L4879-L4884

In my case it failed downstream in https://github.com/boostorg/asio/blob/boost-1.75.0/include/boost/asio/ssl/impl/context.ipp#L206-L215 as **-DSSL_TXT_TLSV1_1** was defined, even though TLSv1.1 was missing in the libwolfssl.so.

I ran into this problem when building the 5.0.0 FIPS ready version of wolfssl (TLSv1.1 disabled).

I patched it locally by only adding **-DSSL_TXT_TLSV1_1**  if  **ENABLED_FIPS** was set, but I believe a better approach would be to use a specific parameter for controlling if TLSv1.1 (similar to **ENABLED_TLSV10** for TLSv1.0).

**Comment by kareem-wolfssl** [comment]
Hi @axawsi,

Yes, if TLS 1.1 is disabled (`ENABLED_OLD_TLS` is false), we need to exclude the TLS 1.1 flag.  I've created a PR that does this here: https://github.com/wolfSSL/wolfssl/pull/4758
Let me know if it resolves the issue for you.

Thanks,
Kareem
