### ISSUE TITLE
TLS server: incorrect extensions selection

### ISSUE THREAD

**Issue by t0x1c** [wolfSSL/wolfssl#4748]
Unable to connect to wolfSSL server (specifically with BouncyCastle client) if encrypt-then-mac extension is used. Here's explanation in BC source code:

> RFC 7366 3. If a server receives an encrypt-then-MAC request extension from a client and then selects a stream or Authenticated Encryption with Associated Data (AEAD) ciphersuite, it MUST NOT send an encrypt-then-MAC response extension back to the client.

So apparently wolfSSL server does choose AEAD cipher but does not exclude encrypt-then-mac extension in ServerHello message.
I believe, adding this check should be a relatively easy fix. Maybe inside TLSX_Write() function, or maybe rather in client hello parser.

**Comment by SparkiDev** [comment]
Hi @t0x1c

I have put up a fix for this: https://github.com/wolfSSL/wolfssl/pull/4750

Let me know if this works for you!

Sean :-)

**Comment by t0x1c** [comment]
Hi Sean,
I did a quick test and it seems to be working. Thanks!

**Comment by SparkiDev** [comment]
Hi @t0x1c 

The PR has been merged and as it works for you, I'm closing the issue.

Sean :-)
