### ISSUE TITLE
X509_verify_cert_error_string(0) incompatible with OpenSSL

### ISSUE THREAD

**Issue by mandree** [wolfSSL/wolfssl#4773]
as of 4c05d35452f4226f49b0b066b7f42892e0fc8a3e:
X509_verify_cert_error_string(0) is incompatible with OpenSSL and returns "unknown error number", whereas with OpenSSL 1.1.1, it returns "ok".

`fetchmail: SSL verify callback depth 1: verify_ok == 1, err = 0, unknown error number`
^ this was wolfSSL. v now follows OpenSSL:
`fetchmail: SSL verify callback depth 1: verify_ok == 1, err = 0, ok`

_Originally posted by @mandree in https://github.com/wolfSSL/wolfssl/issues/4592#issuecomment-1016798262_

**Comment by julek-wolfssl** [comment]
@mandree The fix for this has been merged to the master branch. Thank you for your report!
