### ISSUE TITLE
ER: API to convert Ed25519 keys to Curve25519 keys to be used for a shared secret

### ISSUE THREAD

**Issue by aburks** [wolfSSL/wolfssl#49]
It'd be great if wolfSSL had the ability to convert Ed25519 keys into Curve25519 keys in order to use Ed25519 keys to derive a shared secret. There's a reference implementation available in libsodium: https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_sign/ed25519/ref10/keypair.c

**Comment by toddouska** [comment]
Thanks for the request.  Discussing whether or not to implement.

**Comment by pzboyz** [comment]
This would be useful.

**Comment by haydenroche5** [comment]
We're tracking this request in our internal feature request list. If you're interested in having us add this feature, feel free to reach out to facts@wolfssl.com. In the meantime, I'm going to close this issue.
