### ISSUE TITLE
Hope to support RFC8998 (SM2, SM3, SM4), Thanks.

### ISSUE THREAD

**Issue by shove70** [wolfSSL/wolfssl#5141]
https://www.rfc-editor.org/rfc/rfc8998

**Comment by dgarske** [comment]
Hi @shove70 ,

We do support SM2 verify, but it is not in the public wolfSSL repository. Please emails facts@wolfssl.com if you are interested in evaluating it.

We will eventually add the other SM Chinese algorithms, but we will continue to keep them in a separate repository and release bundle.

Thanks,
David Garske, wolfSSL

**Comment by shove70** [comment]
> We do support SM2 verify, but it is not in the public wolfSSL repository. Please emails [facts@wolfssl.com](mailto:facts@wolfssl.com) if you are interested in evaluating it.
> 
> We will eventually add the other SM Chinese algorithms, but we will continue to keep them in a separate repository and release bundle.

Thank you for your guidance.
