### ISSUE TITLE
Espressif ESP-IDF component install fails when target directory path has embedded spaces

### ISSUE THREAD

**Issue by gojimmypi** [wolfSSL/wolfssl#5154]
### Version

current version

### Description

The [Windows Espressif ESP-IDF setup_win.bat](https://github.com/wolfSSL/wolfssl/blob/master/IDE/Espressif/ESP-IDF/setup_win.bat) component install does not properly handle spaces in the `IDF_PATH` or command-line parameter.

For example when someone has a `first last` login name and the ESP-IDF is installed for the current user desktop directory, the install will fail. 

credit @ejohnstown for finding this. 

See also https://github.com/wolfSSL/wolfssh/pull/405

**Comment by gojimmypi** [comment]
Although there are plans to address this, at this time it is currently a low priority as the [Espressif install](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/get-started/) states "_ESP-IDF does not support spaces in paths_".

![image](https://user-images.githubusercontent.com/13059545/172025094-fb174f52-3930-4c25-8a61-df9c99ce0233.png)

**Comment by PaulMartinsen** [comment]
Hi, I hit this same problem today and modified setup_win.bat to work with paths that contains spaces. I note that Espressif doesn't like spaces, but can confirm it does work for me. I made PR: #5919 . HTH.

**Comment by gojimmypi** [comment]
I'm closing this lingering issue as the [Espressif docs](https://docs.espressif.com/projects/esp-idf/en/release-v5.2/esp32/get-started/windows-setup.html) clearly indicate:

![image](https://github.com/wolfSSL/wolfssl/assets/13059545/0ce2b33e-d5ea-41b6-8473-cbc78fb5da69)

Still, where possible, we'll try to support spaces. Please open a new issue if there's a specific, problematic instance.

It's also a bit less relevant now that [Managed Components](https://components.espressif.com/components/wolfssl/wolfssl) are the preferred mechanism to install wolfSSL instead of the setup script.

See also: 

https://www.wolfssl.com/wolfssl-now-available-in-espressif-component-registry/
