### ISSUE TITLE
[Symbol spelling] wolSSL instead of wolfSSL (no "f")

### ISSUE THREAD

**Issue by space88man** [wolfSSL/wolfssl#5263]
### Version

master

### Description

 git grep wolSSL

```
src/pk.c:WOLFSSL_DH* wolSSL_DH_new_by_nid(int nid)
wolfssl/openssl/dh.h:WOLFSSL_API WOLFSSL_DH* wolSSL_DH_new_by_nid(int nid);
wolfssl/openssl/dh.h:#define DH_new_by_nid wolSSL_DH_new_by_nid
```

Is the spelling wrong or some insider joke?

**Comment by SparkiDev** [comment]
Hi @space88man,

Thanks for raising the issue!
A pull request has been put up that fixes this issue: #5265

Sean
