### ISSUE TITLE
[RFE] Expose runtime features flag :  alignment requirements of structs

### ISSUE THREAD

**Issue by space88man** [wolfSSL/wolfssl#5275]
### Version

master / 5.3.0

### Description

[RFE] Expose at runtime a features flag such as alignment requirements for structs

I am attempting to integrate wolfSSL into [kamailio](https://github.com/kamailio/kamailio) as a TLS transport.

I encountered the following impedance mismatch:
* kamailio provides custom memory allocators on 8-byte alignment
* wolfSSL when compiled with the default (`--enable-aligndata=yes`) has 16-byte alignment requirement on `WOLFSSL` This flag is used by Debian packaging.

The result is that some structs are aligned on 8-byte boundaries by the custom allocators. Optimisation flags
like `-O -O2 -Og` cause gcc to emit `movaps`. This caused alignment segfaults. (Interestingly, clang always emitted
`movups` so the misalignment was not an issue.)
 
It would be useful at runtime to be able to detect this mismatch: i.e., the consuming application like kamailio will test whether its memory allocators are compatible with the features of the wolfSSL library.

 kamailio happens to have 16-byte aligned memory allocators — however these are not used by default.

OpenSIPS, a similar project to Kamailio, has already integrated wolfSSL and that project has custom allocators (also on 8-byte boundaries). However that repo uses a wolfSSL commit that predates `--enable-aligndata`.

Separately I have filed an issue with kamailiio (https://github.com/kamailio/kamailio/issues/3157) requesting that their custom
allocators align on 16-bytes for large structs like `WOLFSSL`.

**Comment by space88man** [comment]
@kareem-wolfssl  - oh I did not intend to change at runtime - more to expose to the consuming application features baked into the library such as (my example) alignment requirement.

**Comment by kareem-wolfssl** [comment]
@space88man - Thanks for the update, I understand now.  The calling application should be including our build-time settings, eg. options.h/user_settings.h depending on how wolfSSL was built.  With these settings included, you just need to check if `WOLFSSL_USE_ALIGN` is defined to determine if we need any alignment.  Let me know if this is sufficient.
