### ISSUE TITLE
Outdated path in porting guide

### ISSUE THREAD

**Issue by arkivm** [wolfSSL/wolfssl#5285]
Under 2.4 in https://www.wolfssl.com/docs/porting-guide/, it says

> Simply put, you can define WOLFSSL_USER_IO, then write your own I/O callback functions using wolfSSL's default EmbedSend() and EmbedReceive() as templates.  These two functions are located in ./src/io.c.

I think the file should be `src/wolfio.c` which defines `Embed{Send,Receive}`

Also, wouldn't it be better to have the porting guide as part of a git repo such that people can directly send a PR?

**Comment by arkivm** [comment]
A month for a one-liner fix? Why don't you make the porting guide PR-able?

**Comment by dgarske** [comment]
Hi @arkivm ,

I am not sure about the reason for the delay. That is a very good suggestion. We have a private repo for the documentation. I don't think it includes the porting guide, but it should. And we should make that repo public. I will discuss with the team.

Thanks,
David Garske, wolfSSL

**Comment by dgarske** [comment]
Hi @arkivm, FYI: we are still working on a way to make our documentation repo public. The main holdup is streamlining the contributions for the docs. @cconlon is driving this effort. Thanks, David Garske, wolfSSL

**Comment by cconlon** [comment]
Hi @arkivm, thanks again for letting us know our `wolfio.c` filename was outdated in the wolfSSL Porting Guide.  This has been updated in our online HTML/PDF Porting Guide.  Like @dgarske mentioned, we were working on getting our product manuals into GitHub with that repository public.  We have [finished that](https://www.github.com/wolfssl/documentation) with our primary product manuals now, but have not yet added secondary documents like our Porting Guide to that repository.

Thanks again!
Chris
