### ISSUE TITLE
ER: wolfSSL should force the use of a signed 64-bit time_t

### ISSUE THREAD

**Issue by aburks** [wolfSSL/wolfssl#54]
In order to circumvent the Year 2038 problem, where the signed 32-bit `time_t` will rollover, wolfSSL should use a signed 64-bit `time_t` irrespective of the system it's running on.

**Comment by aburks** [comment]
Actually, this may be covered by the `TIME_OVERRIDES` define but I'm still investigating it.

**Comment by toddouska** [comment]
Thanks.  TIME_OVERRIDES does allow the user to define their own type there.  We'll keep on eye on the default system time_t for the default users.
