### ISSUE TITLE
RFC 9266: Channel Bindings for TLS 1.3 support

### ISSUE THREAD

**Issue by Neustradamus** [wolfSSL/wolfssl#5409]
### Version

last

### Description

Can you add the support of RFC 9266: Channel Bindings for TLS 1.3?
- https://datatracker.ietf.org/doc/html/rfc9266 

Little details, to know easily:
- tls-unique for TLS =< 1.2
- tls-exporter for TLS = 1.3 

Thanks in advance.

Linked to:
- https://github.com/wolfSSL/wolfssl/pull/5160
- https://github.com/wolfSSL/wolfssl/commit/9427ebc5bebe293a01f24b3449bf3ba6f2f69e1a
- https://wolfssl.zendesk.com/hc/en-us/requests/14575

**Comment by embhorn** [comment]
Hi @Neustradamus 

I'd be happy to create a formal feature request. Please send an email to support@wolfssl.com to initiate the process.

Thanks,
@embhorn wolfSSL Support

**Comment by embhorn** [comment]
Handling feature request in ZD, so closing this GH issue.

**Comment by Neustradamus** [comment]
@embhorn: Have you progressed on it?

**Comment by embhorn** [comment]
Hi @Neustradamus 

Your feature request was added to our internal queue. As you never specified a location or project details, we cannot prioritize your request.

We try to work on requested features whenever we get free engineering cycles unless a customer decides to back the effort for a finite implementation timeline. If at any time a feature becomes a progress blocker for a project it can be accelerated. That process can be started by contacting the account business manager.

Email: [facts@wolfssl.com](mailto:facts@wolfssl.com)

**Comment by Neustradamus** [comment]
Dear @wolfSSL team, @embhorn,

I think that you have seen the jabber.ru MITM and Channel Binding is the solution:
- https://notes.valdikss.org.ru/jabber.ru-mitm/
- https://snikket.org/blog/on-the-jabber-ru-mitm/
- https://www.devever.net/~hl/xmpp-incident
- https://blog.jmp.chat/b/certwatch

**Comment by Neustradamus** [comment]
Dear @wolfSSL team, dear all,

After several years of patience, I recall you that:
- tls-unique is not secure, vulnerable
- tls-server-end-point support is always missing
- tls-exporter support is always missing

Thanks in advance.
