### ISSUE TITLE
[Bug]: `wolfSSL_BIO_meth_set_destroy` is declared as stub

### ISSUE THREAD

**Issue by maxammann** [wolfSSL/wolfssl#5482]
### Contact Details

maximilian.ammann@trailofbits.com

### Version

5.4.0

### Description

The stub message in the following line is invalid: https://github.com/wolfSSL/wolfssl/pull/5481/files#diff-d3d328f21e7f35a2fabbe43c3af5c9ed22a3b4451f59ff09973b05a39d5efcdbR1868

See this closed PR for more information: https://github.com/wolfSSL/wolfssl/pull/5481

**Comment by embhorn** [comment]
Closing as fixed in #5483
