### ISSUE TITLE
OpenSSL compatibility layer: Add SSL_set1_host

### ISSUE THREAD

**Issue by bgermann** [wolfSSL/wolfssl#5681]
### Version

5.5.1

### Description

Please add the function SSL_set1_host to wolfssl/openssl/x509_vfy.h.
This is needed for mongoose web server; see [swupdate thread](https://groups.google.com/g/swupdate/c/a-dMYIYbhnk/m/l0XciUc2AwAJ).

**Comment by philljj** [comment]
Hi @bgermann, SSL_set1_host has been added to the OpenSSL Compatibility Layer in this recent PR #5711. Let me know if this resolves your issue.

**Comment by bgermann** [comment]
Yes, thanks!
