### ISSUE TITLE
ClientHello extensions parse lack of inspection of repeatability

### ISSUE THREAD

**Issue by SmallTown123** [wolfSSL/wolfssl#5863]
### Contact Details

small_town_123@163.com

### Version

5.5.1

### Description

When we tested TLS1.2 on the TLS handshake implementation part of wolfSSL,
we found that the Server lack of inspection of repeatability when parsing the
Extensions field of the ClientHello message, but responded normally.

This is inconsistent with the specification "There MUST NOT be more than one
extension of the same type." in section 7.4.1.4 of the RFC5246 documentation.

The resolution ambiguity is easily caused, and if the processing of an extension
is complex and consumes large resources, the malicious Client may attack the
Server by repeat someone Extensions.

### Reproduction steps

The problem can be verified by simply sending a ClientHello message to wolfSSL Server with duplicate extensions.

**Comment by kareem-wolfssl** [comment]
Hi @SmallTown123 ,

Thanks for the report.  I am assigning this to another engineer who will look into it further.
It would be helpful if you can include your build settings (./configure or user_settings.h), and confirm if you can reproduce this on the latest master.

Thanks,
Kareem

**Comment by SparkiDev** [comment]
@SmallTown123 

Thanks for the report!

A pull request has been put up to address the issue.
Feedback on the fix would be appreciated.

Thanks,
Sean

**Comment by SmallTown123** [comment]
Hi @kareem-wolfssl,

Sorry for not replying to you at the first time. 
And the issue has been fixed by Sean. 

Thanks,
Town

**Comment by SparkiDev** [comment]
@SmallTown123

Thanks for the feedback in the pull request!
The PR will be merged when I address review comments.

Sean :-)
