### ISSUE TITLE
is it correct? The iv_size of  TLS_ECDHE_PSK_WITH_AES_128_GCM_SHA256 is AES_IV_SIZE

### ISSUE THREAD

**Issue by 801room** [wolfSSL/wolfssl#5888]
### Version

master

### Description

file:keys.c

   case TLS_ECDHE_PSK_WITH_AES_128_GCM_SHA256 :
        ssl->specs.bulk_cipher_algorithm = wolfssl_aes_gcm;
        ssl->specs.cipher_type           = aead;
       ...
        ssl->specs.iv_size               = AES_IV_SIZE;
       ...

Whether the iv_size should be 4 bytes? So use  AESGCM_IMP_IV_SZ?

**Comment by embhorn** [comment]
Hi @801room 

I've requested a review of this by the team. Could you tell us a bit about your project?

Thanks,
@embhorn
