### ISSUE TITLE
Failure in few test cases while executing make test command

### ISSUE THREAD

**Issue by sandilya761** [wolfSSL/wolfssl#5961]
### Version

wolfssl-5.5.1

### Description

Some of the test cases are failing while executing **make test** command. Following image contains the failed test cases:

![image](https://user-images.githubusercontent.com/57587519/211149601-1ec05e7b-2244-4a00-9823-e3b819d74489.png)

![image](https://user-images.githubusercontent.com/57587519/211149650-5c862a39-cbfa-4c1b-9f27-50d8a1e75ee2.png)

Following are my environment details:
**Wolfssl version:** 5.5.1
**make version:** GNU Make 4.3
**Kernel version:** 5.7.0-kali1-amd64.

**Comment by ejohnstown** [comment]
Can you tell me how you are configuring wolfSSL? I tried:

    ./configure --enable-all && make check

and didn't have any failures. I'm testing this in a VM of the Kali Linux 2022.4 image.

**Comment by kareem-wolfssl** [comment]
Hi @sandilya761,

Please retry this with our latest release, 5.5.4.  As John stated please share your configure line if you continue to have issues.

**Comment by sandilya761** [comment]
I tried the following command with **5.5.4 version**:
`./configure --enable-all && make check`

It is getting stuck after scripts/ocsp.test as shown in the image below:

![image](https://user-images.githubusercontent.com/57587519/211720031-5bca838e-fd41-4a56-b0b0-e78f5e168082.png)

**Comment by kareem-wolfssl** [comment]
The next test should be our unit test, please try running it standalone with `./scripts/unit.test` and let me know if it still freezes.  If it does, please attach the full output here.
Note that this test can take a long time.

**Comment by sandilya761** [comment]
`./scripts/unit.test` command is working fine.

![image](https://user-images.githubusercontent.com/57587519/212132562-973704d2-a953-4a66-a4c0-d77014461632.png)

**Comment by kareem-wolfssl** [comment]
Hi @sandilya761,

Running `make test` is equivalent to `make check`.
Please try rebuilding with `--disable-jobserver`, with this enabled the tests run in a somewhat random order, disabling it will cause the tests to run in a consistent order.

Thanks,
Kareem

**Comment by sandilya761** [comment]
It's working fine. 

Thank You!!
