### ISSUE TITLE
Missing strnlen() on MingW

### ISSUE THREAD

**Issue by gvanem** [wolfSSL/wolfssl#60]
MingW doesn't have `strnlen()` which is needed in sniffer.c + snifftest.c. To solve it, I added this to my `config.h`:
```
    extern __inline__ size_t strnlen (const char *str, size_t maxsize)
    {
      size_t n;
      for (n = 0; n < maxsize && *str; n++, str++)
        ;
      return (n);
    }
```
Maybe the missing functions (strnlen, strsep) could be added to a more suitable place?

**Comment by ejohnstown** [comment]
I replaced the call to `strnlen()` with `strlen()` and did my size check separately. `strnlen()` isn't very portable, as you found, so we shouldn't use it.
