### ISSUE TITLE
wolfssl error: ssl_accept error-313

### ISSUE THREAD

**Issue by sandilya761** [wolfSSL/wolfssl#6036]
### Version

5.5.4

### Description

error in following commands:

./examples/server/server -d -l ECDHE-ECDSA-AES256-SHA -c ./certs/server-ecc.pem -k ./certs/ecc-key.pem
./examples/client/client -A ./certs/server-ecc.pem

Following is the error:

![image](https://user-images.githubusercontent.com/57587519/215808593-3ceab869-7bea-4e56-95ca-ba7006e92ba3.png)

![image](https://user-images.githubusercontent.com/57587519/215808798-dad00175-9565-481b-ba75-45368d12178e.png)

**Comment by embhorn** [comment]
Hello @sandilya761 

Please try loading the CA cert in the client, not the server's cert:

```
./examples/client/client -A ./certs/ca-ecc-cert.pem
```

Thanks,
@embhorn - wolfSSL Support

**Comment by embhorn** [comment]
Also, `ECDHE-ECDSA-AES256-SHA` is a TLS v1.0 cipher suite…  You would need `--enable-oldtls` to support it.
Please understand this is a very OLD cipher suite, and we actively discourage using these in new projects.

**Comment by sandilya761** [comment]
Thanks @embhorn. It's working.
