### ISSUE TITLE
[Bug]: Incompatibility in the OpenSSL compat layer: d2i_PKCS8_PRIV_KEY_INFO_bio and PKCS7_verify only operate on mem-based BIOs instead of any BIO

### ISSUE THREAD

**Issue by bgermann** [wolfSSL/wolfssl#6174]
### Version

5.5.4

### Description

As #6173 was closed without actually understanding the impact of the reported bug, I am filing this one.
The d2i_PKCS8_PRIV_KEY_INFO_bio maps to wolfSSL_d2i_PKCS8_PKEY_bio and PKCS7_verify maps to wolfSSL_PKCS7_verify. Both OpenSSL functions operate on any BIO input parameter, e.g. one representing file I/O. The OpenSSL compat layer functions do not operate on any BIO but only on ones that are built with the BIO_METHOD BIO_s_mem or BIO_s_secmem.

**Comment by anhu** [comment]
@bgermann , 
Thanks again for sharing your perspective.  I will re-iterate for our OpenSSL compatibility layer, we remedy missing functionalities as feature requests. Please get in touch with us via facts@wolfssl.com to register your desire for those functionalities.
