### ISSUE TITLE
RIOT-OS does support writev, so NO_WRITEV is not necessary

### ISSUE THREAD

**Issue by Flole998** [wolfSSL/wolfssl#6211]
In https://github.com/wolfSSL/wolfssl/blob/35b68fb23d2316d4cf42816f2f27ead601594c92/wolfssl/wolfcrypt/settings.h#L678 there is a define for `NO_WRITEV` on RIOT-OS. However, RIOT-OS does support writev, so that should be removed.

Additionally in RIOT-OS that define is there aswell (in pkg/wolfssl/include/user_settings.h) and I will make sure that is removed over there aswell.

**Comment by embhorn** [comment]
Hi @Flole998 

I've created a draft PR to address this issue.

Thanks,
@embhorn - wolfSSL Support
