### ISSUE TITLE
Wolfssl with curl, error -313 for sending curl request

### ISSUE THREAD

**Issue by reflexaaff** [wolfSSL/wolfssl#6291]
### Version

5.6.0

### Description

Building wolfssl
``
    ./configure --host=arm-buildroot-linux-musleabihf --prefix=/usr \
        --enable-debug --enable-curl --enable-opensslall --enable-fastmath --enable-sp --enable-static --enable-keygen \
        --disable-examples --disable-crypttests  --disable-shared --disable-oldnames \
``
curl `--with-wolfssl=/pathtowolfssl/`

Debug log wolfssl:
[DEBUG LOG WOLFSSL PASTERBIN](https://pastebin.com/bPXGjtgj)

After switching from opensl to wolfssl, the curl stopped sending requests, the curl itself returns error 35, and wolf ssl -313.
Everything was fine on the openssl.
Let me know if you have ever experienced this, what could be the problem?
Thank you in advance

**Comment by embhorn** [comment]
Hi @reflexaaff 

Thanks for contacting wolfSSL Support. That error code corresponds to `    FATAL_ERROR                  = -313,   /* recvd alert fatal error  */`, which indicates the peer rejected the connection.

Are you connecting to a public server that we could test?

Thanks,
