### ISSUE TITLE
[Bug]: Missing opening "{" in sp_int.c

### ISSUE THREAD

**Issue by StMartin81** [wolfSSL/wolfssl#6317]
### Contact Details

martin.stolpe@gmail.com

### Version

5.6.0

### Description

I think in [sp_int.c](https://github.com/wolfSSL/wolfssl/blob/81ab16b1050e1ac76781a9929f1b19d52581d77c/wolfcrypt/src/sp_int.c#L13071), l. 13071 there should be an opening "{" in the if-statement.

### Reproduction steps

./configure --enable-static --disable-shared --without-pic --enable-reproducible-build --enable-cryptonly --enable-rsapub --disable-examples --disable-crypttests --disable-filesystem --disable-oldtls --disable-tlsv12 --disable-tls13 --disable-sha3 --disable-sha512 --disable-sha384 --disable-eccshamir --disable-ecc --disable-errorstrings --disable-errorqueue --disable-oldtls --disable-tlsv12 --disable-tlsv10 --disable-memory --disable-trackmemory --disable-oaep --disable-dh --disable-aes --disable-aescbc --disable-aesgcm --disable-coding --disable-base16 --disable-md5 --disable-poly1305 --disable-chacha --disable-filesystem --disable-inline --disable-secure-renegotiation-info --disable-supportedcurves --disable-extended-master --disable-enc-then-mac --disable-pkcs12 --disable-examples --disable-crypttests --disable-crypttests-libs --disable-pkcs8 --disable-oldnames --disable-hkdf --disable-rsapss --enable-lowresource --disable-errorstrings --enable-sp=smallrsa2048,smallstack,nomalloc,asm --host=arm-none-eabi --with-arm-target=thumb CC=arm-none-eabi-gcc LD=arm-none-eabi-ld AR=arm-none-eabi-ar RANLIB=arm-none-eabi-ranlib CFLAGS=--specs=nosys.specs -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fdump-rtl-expand -fstack-usage
make

**Comment by SparkiDev** [comment]
Hi @StMartin81

Thanks for reporting the issue.
I've confirmed that the brace is missing and put up a pull request to fix this: #6321 

Please let us know if you have problems with the PR.

Thanks,
Sean

--
Sean Parkinson, wolfSSL
Senior Software Engineer
