### ISSUE TITLE
[Bug]: wc_error_mutex not unlocked

### ISSUE THREAD

**Issue by vuvova** [wolfSSL/wolfssl#6348]
### Version

v5.6.0-stable

### Description

`wc_PeekErrorNodeLineData()` in `wolfcrypt/src/logging.c` does `ERRQ_LOCK()` but then it can early return without unlocking the mutex. This causes test failures in MariaDB test suite.

Here's the fix:
```diff
--- a/wolfcrypt/src/logging.c
+++ b/wolfcrypt/src/logging.c
@@ -1223,6 +1223,7 @@ unsigned long wc_PeekErrorNodeLineData(const char **file, int *line,
         ret = peekErrorNode(idx, file, NULL, line);
         if (ret == BAD_MUTEX_E || ret == BAD_FUNC_ARG || ret == BAD_STATE_E) {
             WOLFSSL_MSG("Issue peeking at error node in queue");
+            ERRQ_UNLOCK();
             return 0;
         }
         /* OpenSSL uses positive error codes */
```

### Reproduction steps

that's rather tricky. get mariadb, say, 10.4, update the wolfssl submodule to v5.6.0-stable. build and run the main.ssl_cypher test.

Or simply look at https://github.com/wolfSSL/wolfssl/blob/v5.6.0-stable/wolfcrypt/src/logging.c#L1226

**Comment by kareem-wolfssl** [comment]
Hi @vuvova,

Thanks for the report and proposed fix, I agree this is a bug, I've created a PR here which should fix this: https://github.com/wolfSSL/wolfssl/pull/6357

Thanks,
Kareem
