### ISSUE TITLE
[Bug]: DTLS 1.3 start handshake with arbitrary epoch number

### ISSUE THREAD

**Issue by Conradowatz** [wolfSSL/wolfssl#6368]
### Contact Details

conrad@owatz.de

### Version

5.6.0

### Description

In DTLS 1.3 the epoch number determines in which connection state you are an which key material to use.
Epoch 0 is used for unencrypzted messages, e.g. ClientHello or ServerHello. Epoch 2 is used for traffic protected by the handshake secret.
However, wolfSSL does not seem to check the epoch number of unencrypted traffic in DTLS 1.3. In my test I could send an unencrypted ClientHello or ServerHello with epoch number set to 2 and it got parsed normally. The handshake can succeed as long as the rest of the epoch numbers are sent correctly, meaning continuing with 2 for encrypzted handshake traffic.
The RFC states, that `The epoch number is initially zero and is incremented each time keying material changes and a sender aims to rekey. `

![grafik](https://user-images.githubusercontent.com/10256310/235697554-53257905-8df7-436b-9e86-e94258d8ddca.png)

### Reproduction steps

To use DTLS 1.3 you have to enable it in user_setting.h:
```
#define WOLFSSL_DTLS
#define WOLFSSL_DTLS13
```

To reproduce the handshake I used an unreleased version of TLS-Attacker and modified the epoch value of the ClientHello or ServerHello.

**Comment by rizlik** [comment]
Hi @Conradowatz,
Thanks for reporting this, I'm currently looking into that and I'll provide feedback soon.

Marco
