### ISSUE TITLE
This is a license-related issue.

### ISSUE THREAD

**Issue by shenhaicheng** [wolfSSL/wolfssl#6404]
### Version

wolfssl-5.6.0-stable

### Description

Due to special circumstances, we cannot use the software with the GPLv3 license.From the[ https://www.wolfssl.com/license/ ]( https://www.wolfssl.com/license/ )website, we know that the license of wolfssl is GPLv2.However, in some .m4 files, the license declaration of these files is GPLv3.(eg:ax_append_compile_flags.m4: line31-44 )
 
    Copyright (c) 2011 Maarten Bosmans <mkbosmans@gmail.com>
 
    This program is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by the
    Free Software Foundation, either version 3 of the License, or (at your
    option) any later version.
 
    This program is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
    Public License for more details.
 
    You should have received a copy of the GNU General Public License along
    with this program. If not, see <https://www.gnu.org/licenses/>.

    As a special exception, the respective Autoconf Macro's copyright owner
    gives unlimited permission to copy, distribute and modify the configure
    scripts that are the output of Autoconf when processing the Macro. You
    need not follow the terms of the GNU General Public License when using
    or distributing such scripts, even though portions of the text of the
    Macro appear in them. The GNU General Public License (GPL) does govern
    all other use of the material that constitutes the Autoconf Macro.
 
    This special exception to the GPL applies to versions of the Autoconf
    Macro released by the Autoconf Archive. When you make and distribute a
    modified version of the Autoconf Macro, you may extend this special
    exception to the GPL to apply to your modified version as well.

The following is the command for compiling the wolfssl. I'd like to know if our current compilation method meets the GPL exception. Thanks in advance!

    ./autogen.sh; 
    chmod 550 ./configure; 
    ./configure  --host=$(LIBWOLFSSL_CONFIGURE_OPTS) --prefix=$(strip $(TARGET_DIR)/$(TARGET_SYSTEM)) 
     --disable-crypttests --disable-examples 
    --enable-keygen --enable-rsapss --enable-aesccm 
    --enable-aesctr --enable-des3 --enable-camellia 
    --enable-curve25519 --enable-ed25519 
     --enable-curve448 --enable-ed448 
    --enable-sha3 --enable-shake256 --enable-ecccustcurves 
    --with-max-rsa-bits=4096

**Comment by dgarske** [comment]
Hi @shenhaicheng ,

These are generated from running `./autogen.sh` -> `autoreconf --install --force` and come from the auto tools project. They are not part of our repository.

@danielinux or @douzzer any feedback/thoughts on this topic?

Thanks,
David Garske, wolfSSL

**Comment by douzzer** [comment]
As @dgarske explained, the m4 files are only used by/for autotools.  Even if used in conjunction with a commercial distribution of wolfssl or related application, no additional requirements apply to that distribution.

Note that the implicated m4 scripts are _not_ GPLv3, they are an explicitly modified license that relaxes any and all requirements regarding the generated `configure` script.

Therefore when you use the distribution archives of wolfssl (or of any autotools-configured software with a pregenerated `configure` script) you are _not_ using it with GPLv3 software in it.  Indeed you can delete the entire `m4/` directory with no effect on the build process.  If you scrutinize the pregenerated `configure` script you will discover it has no references to `m4/` other than some comments.

**Comment by shenhaicheng** [comment]
Thank you for your reply.
We tried to delete the entire `m4/` directory, but encountered the following error.
```
./autogen.sh
aclocal: warning: couldn't open directory 'm4': No such file or directory
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:106: error: possibly undefined macro: AC_C___ATOMIC
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:263: error: possibly undefined macro: AS_CASE
configure.ac:496: error: possibly undefined macro: AC_PATH_DEFAULT_KERNEL_SOURCE
configure.ac:502: error: possibly undefined macro: AC_DEFAULT_KERNEL_ARCH
configure.ac:1110: error: possibly undefined macro: AC_DEFINE
autoreconf: error: /usr/bin/autoconf failed with exit status: 1
```

And then we tried to block `autogen.sh` -> `autoreconf --install --force`, failed to generate the `configure`. Is there a problem with my compilation method? Thanks.

**Comment by anhu** [comment]
Hi, 

Please see https://www.wolfssl.com/download/ .  There you will find a release of wolfSSL that you can download.  It will already have a pre-generated `configure` script and so you won't need the m4 directory. 

Warm regards, Anthony

**Comment by zhangjing-master** [comment]
Thank you for your reply.
We tried to delete the entire m4/ directory and  executed  ./configure. However, the error is as follows: 

`configure: ---
configure: Running make clean...
/usr1/home/z30032141/wolfssl-5.6.0/build-aux/missing: line 81: aclocal-1.15: command not found
WARNING: 'aclocal-1.15' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make: *** [Makefile:4216: aclocal.m4] Error 127
configure: ---
configure: Generating user options header...`

The local aclocal version is 1.16. 5. Therefore, can we dynamically set the aclocal version?

aclocal --version
aclocal (GNU automake) 1.16.5
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by shenhaicheng** [comment]
Thank you for your answers. We set up the autoconf compilation environment to solve these problems.
By the way，If we want to use wolfssl for commercial use, do we need the COMMERCIALLY LICENSED versions？Thanks!

**Comment by anhu** [comment]
YES!! Please send a message to facts@wolfssl.com to get the conversation started about licensing wolfSSL for commercial use.  Please be sure to specify your company or organization's name and location.  The appropriate Regional Business Director will then reach out to you.. 
Warm regards, Anthony

**Comment by anhu** [comment]
I see you problems are solved so I will now close this issue.  Thank you and please do email us at facts@wolfssl.com.
