### ISSUE TITLE
[Bug]: ClientHello indicates RSA support even if disabled

### ISSUE THREAD

**Issue by maxgerhardt** [wolfSSL/wolfssl#6451]
### Contact Details

maximilian.gerhardt@rub.de

### Version

5.6.0-stable

### Description

When configuring WolfSSL with

```cpp
#define NO_RSA
```

the generated Client Hello message still indicates a signature algorithm that has RSA support.

![image](https://github.com/wolfSSL/wolfssl/assets/26485477/0dff15bb-80cf-494b-9479-236b30bf9aa9)

This is because

https://github.com/wolfSSL/wolfssl/blob/37c03e3f115df2471dca337b96bc6b364f22ffb4/src/tls.c#L6503-L6504

indiscriminately adds these signature algorithms.

### Reproduction steps

1. Create a config with `#define NO_RSA`
2. Compile and run a DTLS 1.2 client example
3. Capture network output
4. Decode in Wireshark
5. Inspect signature_algorithms extension list

### Relevant log output

```shell
my_IOSend called with 117 bytes
TLS TX Data (117 bytes):
  0000  16 fe fd 00 00 00 00 00 00 00 00 00 68 01 00 00  ............h...
  0010  5c 00 00 00 00 00 00 00 5c fe fd 6f 40 d2 d9 a5  \.......\..o@...
  0020  62 fb ae 72 4a 22 45 a9 aa 2b d2 84 10 f9 84 e6  b..rJ"E..+......
  0030  a7 15 99 7e ff 0e 29 13 a8 32 0b 00 00 00 08 c0  ...~..)..2......
  0040  2c c0 2b c0 23 c0 24 01 00 00 2a 00 0d 00 0a 00  ,.+.#.$...*.....
  0050  08 05 03 04 03 05 01 04 01 00 0b 00 02 01 00 00  ................
  0060  0a 00 0a 00 08 00 18 00 1b 00 17 00 1a 00 16 00  ................
  0070  00 00 17 00 00                                   .....
```

**Comment by maxgerhardt** [comment]
For reference: A similiar configured mbedTLS DTLS 1.2 client does not have that in the list.

![image](https://github.com/wolfSSL/wolfssl/assets/26485477/8d964855-6655-49f3-9d2b-b4ba610f0c73)

Handshake packet
```
16 FE FF 00 00 00 00 00 00 00 00
00 68 01 00 00 5C 00 00 00 00 00 00 00 5C FE FD
64 14 37 FF A9 86 2C 7B A1 0E 8D E3 F1 EF A1 8F
60 8A 61 F8 C3 A6 AB 15 63 E9 01 A3 1B 68 6C 85
00 00 00 0A C0 2B C0 2C C0 23 C0 24 00 FF 01 00
00 28 00 0D 00 0A 00 08 06 03 05 03 04 03 03 03
00 0A 00 08 00 06 00 1B 00 17 00 1A 00 0B 00 02
01 00 00 16 00 00 00 17 00 00
```

**Comment by anhu** [comment]
Hi @maxgerhardt , 

Yes, we allow users to set the support signature algorithms via `wolfSSL_CTX_set1_sigalgs_list()` and other similarly named APIs. 

Please try using those to set the supported sigalgs. 

Warm regards, Anthony

**Comment by maxgerhardt** [comment]
Unfortunetly that doesn't change the list at all, even the packet size is the same
```
my_IOSend called with 117 bytes
TLS TX Data (117 bytes):
  0000  16 fe fd 00 00 00 00 00 00 00 00 00 68 01 00 00  ............h...
  0010  5c 00 00 00 00 00 00 00 5c fe fd b8 c0 c9 a2 f4  \.......\.......
  0020  74 b5 5d 2b 76 c7 1b f8 de 64 7b 0f b6 fd 2f 97  t.]+v....d{.../.
  0030  1c 09 09 ab 92 cd fd 95 a1 ee 98 00 00 00 08 c0  ................
  0040  2c c0 2b c0 23 c0 24 01 00 00 2a 00 0d 00 0a 00  ,.+.#.$...*.....
  0050  08 05 03 04 03 05 01 04 01 00 0b 00 02 01 00 00  ................
  0060  0a 00 0a 00 08 00 18 00 1b 00 17 00 1a 00 16 00  ................
  0070  00 00 17 00 00                                   .....
```

And the code is definitely inactive now.

![image](https://github.com/wolfSSL/wolfssl/assets/26485477/36e590ff-cdb7-43a0-a23b-bd548100ca61)

**Comment by anhu** [comment]
Hi @maxgerhardt , 

I have another fix ready, but it will require some changes to our unit tests which I have not done yet.  Please stay tuned. 

Warm regards, Anthony.

**Comment by anhu** [comment]
Updated.  Please have another look at the PR.

**Comment by maxgerhardt** [comment]
See comment in PR.
