### ISSUE TITLE
CMake Options missing

### ISSUE THREAD

**Issue by joeftiger** [wolfSSL/wolfssl#6526]
### Version

5.6.3 (#3b3c175af0e993ffaae251871421e206cc41963f)

### Description

When using wolfSSL as a CMake project, various compile options like
- HPKE
- ECH
- Keying Material (TLS Exporter)

are missing.

I tried adding them myself (probably not clean) like following:
```cmake
# Hybrid Public Key Encryption (RFC9180)
add_option("WOLFSSL_HPKE"
        "Enable wolfSSL hybrid public key encryption (default: disabled)"
        "no" "yes;no")

if(WOLFSSL_HPKE)
    if(NOT WOLFSSL_ECC)
        message(FATAL_ERROR "HPKE supported only with ECC (WOLFSSL_ECC)")
    endif()
    list(APPEND WOLFSSL_DEFINITIONS "-DHAVE_HPKE")
endif()

# Encrypted Client Hello (ECH)
add_option("WOLFSSL_ECH"
        "Enable wolfSSL encrypted client hello (default: disabled)"
        "no" "yes;no")

if(WOLFSSL_ECH)
    if(NOT WOLFSSL_HPKE)
        message(FATAL_ERROR "ECH supported only with HPKE (WOLFSSL_HPKE)")
    endif()
    if(NOT WOLFSSL_SNI)
        message(FATAL_ERROR "ECH supported only with SNI (WOLFSSL_SNI)")
    endif()
    list(APPEND WOLFSSL_DEFINITIONS "-DHAVE_ECH")
endif()

# Keying Material Exporter / TLS Exporter
add_option("WOLFSSL_KEYING_MATERIAL"
        "Enable wolfSSL keying material export (default: disabled)"
        "no" "yes;no")

if(WOLFSSL_KEYING_MATERIAL)
    list(APPEND WOLFSSL_DEFINITIONS "-DHAVE_KEYING_MATERIAL")
endif()
```

When I then try to enable `-DWOLFSSL_HPKE=yes` with its dependencies, I get undefined references to HPKE-related functions.

Is it possible to include these features in CMake?
I tried it as a `make` project, but it keeps failing on `autogen.sh` already.

**Comment by dgarske** [comment]
Hi @joeftiger ,

Thank you for this feature request and sample CMake logic to implement. I've asked @bandi13 to review and put up a PR.

Thanks,
David Garske, wolfSSL
