### ISSUE TITLE
About Middlebox Compatibility Mode

### ISSUE THREAD

**Issue by HaewonSeo** [wolfSSL/wolfssl#6554]
### Version

woflssl-v5.6.2-stable

### Description

./configure '--enable-all'  'C_EXTRA_FLAGS=-DWOLFSSL_TLS13_MIDDLEBOX_COMPAT'

Hi, 

When I define WOLFSSL_TLS13_MIDDLEBOX_COMPAT in v5.4.0, TLS1.3 server sent change_cipher_spec after ServerHello.
And in v5.6.2 with the same configuration, the TLS1.3 server did not send change_cipher_spec after ServerHello.

I wonder if "ssl->options.tls13MiddleBoxCompat = 1;" is missing on the server side in v5.6.2.

**Comment by julek-wolfssl** [comment]
Hi @HaewonSeo,

it appears that you are correct. We will provide a fix as soon as possible.

Juliusz
