### ISSUE TITLE
[Bug]:  aes_gcm_asm.asm doesn't support Windows x86-64 calling convention

### ISSUE THREAD

**Issue by ilka1999** [wolfSSL/wolfssl#6608]
### Version

5.6.3

### Description
 aes_gcm_asm.asm doesn't support Windows x86-64 calling convention

[according](https://learn.microsoft.com/en-us/cpp/build/x64-software-conventions?view=msvc-170#register-volatility-and-preservation) to MS convention, registers XMM6-15 are nonvolatile. 

see my [previous](https://github.com/wolfSSL/wolfssl/issues/5190) report for details please

for example, clang can use XMM6-15 registers for initialization constants

**Comment by ilka1999** [comment]
for example, clang can use XMM6-15 registers for initialization constants

**Comment by SparkiDev** [comment]
Hi @ilka1999,

I see the issue and have prepared a fix for this: https://github.com/wolfSSL/wolfssl/pull/6617

Please try out the PR code and let me know if this works for you.

Thanks,
Sean

--
Sean Parkinson, wolfSSL
Senior Software Engineer

**Comment by SparkiDev** [comment]
Hi @ilka1999

It has been some time since I posted the PR.
I was wondering if you had had a chance to try it out?

Sean

**Comment by ilka1999** [comment]
Hi Sean

I'm a native code expert, not a wolfSSL user.
My friend who can test wolfSSL is offline right now (on vacation) and should be available in a week.
I'll ask him.

Ilias

**Comment by SparkiDev** [comment]
Thanks @ilka1999.

Sean

**Comment by SparkiDev** [comment]
Hi @ilka1999

I've updated the pull request based on the fixes required from your observations.
Note that the functions use stack for temporary storage.

Thanks,
Sean

**Comment by SparkiDev** [comment]
Hi @ilka1999

The PR that fixes the issues you raised has been committed.
Let us know if there are any more problems like this!

Thanks,
Sean
