### ISSUE TITLE
Support for Intel SHA extensions

### ISSUE THREAD

**Issue by ironsoul0** [wolfSSL/wolfssl#6787]
### Version

5.6.3

### Description

We wanted to ask if there are any plans to start supporting [Intel SHA extensions](https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sha-extensions.html) for accelerating SHA implementations. If I am not mistaken, currently the speedup is [achieved](https://www.wolfssl.com/intels-extended-instructions-accelerates-hash-algorithms/) through the usage of Intel's Extended Instructions (AVX1 and AVX2) but our benchmark results suggest that they are suboptimal compared to Intel SHA extensions. We benchmarked against OpenSSL which [uses these extensions](https://github.com/openssl/openssl/blob/2743594d73e65c38375c619e89ec62579e2c24a9/crypto/sha/asm/sha1-586.pl#L432). We understand that only very high end CPUs might support SHA extensions but still would like to get your view on this.

Our compilation setup for WolfSSL:

```
./configure \
   --prefix=$DESTDIR \
   --enable-all \
   --enable-static \
   --enable-opensslall \
   --enable-opensslextra \
   --disable-harden \
   --disable-errorqueue \
   --enable-tls13 \
   --enable-aesni \
   --enable-intelasm \
   --enable-aesgcm \
   --enable-aesgcm-stream \
   --enable-sp \
   --enable-alpn \
   --enable-sni
  ```

**Comment by dgarske** [comment]
Hi @ironsoul0 ,

Can you tell us which SHA versions are you interested in improving? Is it SHA-1, SHA-2 or SHA-3? We support speedups for SHA-2 and SHA-3 using AVX instructions. For SHA-1 we do not support any Intel ASM speedups yet.

Can you tell us more about your use of wolfSSL? We are happy to investigate adding the Intel SHA instruction support, but we need to have some context for your use case and understand if this is commercial or open source.

Thanks,
David Garske, wolfSSL
