### ISSUE TITLE
[Bug]: Streaming AES EAX API cannot be used because `AesEax` is private

### ISSUE THREAD

**Issue by guidovranken** [wolfSSL/wolfssl#6862]
### Version

git master

### Description

```c
#include <wolfssl/options.h>
#include <wolfssl/wolfcrypt/aes.h>

int main(void)
{
    AesEax eax;
    return 0;
}
```

This can't compile because while `AesEax` is declared in `aes.h`, it's definition is in `aes.c`, meaning that no function outside `aes.c` can instantiate `AesEax`, and therefore cannot use any of the AES EAX streaming API's (`wc_AesEaxInit`, `wc_AesEaxDecryptUpdate`, `wc_AesEaxDecryptFinal`), though these are supposed to be public API's.

### Relevant log output

```shell
p.c:6:12: error: variable has incomplete type 'AesEax' (aka 'struct AesEax')
    AesEax eax;
           ^
/home/jhg/wolf-aes-eax/wolfssl/wolfssl/wolfcrypt/aes.h:605:16: note: forward declaration of 'struct AesEax'
typedef struct AesEax AesEax;
               ^
1 error generated.
```

**Comment by kareem-wolfssl** [comment]
Hi Guido,

Thanks for the report.  This should be fixed by https://github.com/wolfSSL/wolfssl/pull/6864
