### ISSUE TITLE
:[enhancement] PEM_X509_INFO_read_bio doesn't set error when parsing a certificate fails

### ISSUE THREAD

**Issue by colmenero** [wolfSSL/wolfssl#6890]
### Version

5.5.1

### Description

[wolfSSL_PEM_X509_INFO_read_bio](https://github.com/wolfSSL/wolfssl/blob/f1e2165c591f074feb47872a8ff712713ec411e1/src/x509.c#L10833) returns a [WOLFSSL_X509_INFO](https://github.com/wolfSSL/wolfssl/blob/f1e2165c591f074feb47872a8ff712713ec411e1/wolfssl/ssl.h#L439) structure containing a CRL, certificate, and/or private keys loaded from the [bio](https://github.com/wolfSSL/wolfssl/blob/f1e2165c591f074feb47872a8ff712713ec411e1/wolfssl/ssl.h#L536). If there is a failure parsing a certificate from the bio, we should be able to get a reason for the error (either as a return code, or another mechanism such as [ERR_get_error](https://github.com/wolfSSL/wolfssl/blob/f1e2165c591f074feb47872a8ff712713ec411e1/src/ssl.c#L16564)).

For example, let's assume that we have wolfSSL compiled with `--enable-certext` and the certificate in the bio has an [unsupported extension](https://www.wolfssl.com/documentation/manuals/wolfssl/chapter07.html#supported-certificate-extensions) (e.g.`Issuer Alternative Name`) marked as critical. `wolfSSL_PEM_X509_INFO_read_bio` fails but we have no information regarding why. OpenSSL on the other hand returns the `unhandled critical extension` log message.

The backtrace is (from low to high level):
* `DecodeCertExtensions` fails and returns `ASN_CRIT_EXT_E`
* `ParseCertRelative` returns `ASN_CRIT_EXT_E`
* `loadX509orX509REQFromBuffer` doesn't handle the return code and returns `NULL`
* `wolfSSL_X509_load_certificate_buffer` returns `NULL`
* `wolfSSL_PEM_X509_X509_CRL_X509_PKEY_read_bio` returns generic `WOLFSSL_FAILURE`

The important part seems to be that [`loadX509orX509REQFromBuffer` only checks if `ParseCertRelative` succeeded or not](https://github.com/wolfSSL/wolfssl/blob/f1e2165c591f074feb47872a8ff712713ec411e1/src/x509.c#L4659).

**Comment by embhorn** [comment]
Hi @colmenero 

Thanks for requesting this enhancement. Please have a look at the changes in #6892 and let me know if this accomplishes the level of reporting you are looking for.

Thanks,
@embhorn - wolfSSL Support

**Comment by colmenero** [comment]
Yes, the changes in [#6982](https://github.com/wolfSSL/wolfssl/pull/6892) achieve what I was expecting.
It would be great if they could make it into master.

Thanks a lot @embhorn for the fix!

**Comment by embhorn** [comment]
Hi @colmenero 

Great! We are currently in a code freeze, but I'll submit this PR for review ASAP.

This issue will be closed after the PR is merged.
