### ISSUE TITLE
need altpkg upload for 3.10.0

### ISSUE THREAD

**Issue by rofl0r** [wolfSSL/wolfssl#693]
hi @cconlon, i'm in the process of updating the sabotage linux package and found that the current version is not available in the altpkg dir. would you be so kind as to upload it, thanks!

**Comment by cconlon** [comment]
Hi @rofl0r, thanks for the reminder!  I'll get this up today.

**Comment by cconlon** [comment]
Just created and uploaded the altpkg (.tar.xz) for 3.10.0, thanks!

**Comment by rofl0r** [comment]
thanks to you!
