### ISSUE TITLE
[apple-universal] ./configure file is not found

### ISSUE THREAD

**Issue by rahul0x24** [wolfSSL/wolfssl#7027]
### Version

master

### Description

Thanks for adding the support for the Apple universal framework.

I wanted to try it out but unfortunately when I tried to run the `./build-wolfssl-framework.sh`, I got the following error

`./build-wolfssl-framework.sh: line 76: ./configure: No such file or directory`

It looks like the `configure` file was ignored when pushing to the Github.

**Comment by dgarske** [comment]
@bigbrett will you please review this report? Thank you

**Comment by bigbrett** [comment]
Hi @rahul0x24 

When cloning wolfSSL from GitHub, you will need to run the[ ./autogen.sh](https://github.com/wolfSSL/wolfssl/blob/master/autogen.sh) script first to generate the `configure` script used by our build system. 

Once you have generated your configure script, the `build-wolfssl-framework.sh` script should work as expected. See the following steps.

```
git clone https://github.com/wolfSSL/wolfssl.git
cd wolfssl
./autogen.sh
cd IDE/apple-universal
./build-wolfssl-framework.sh
```

**Comment by rahul0x24** [comment]
Thank you, I had to install `automake` using `brew` but that `./autogen.sh` command worked for me :).

**Comment by rahul0x24** [comment]
Thank you @bigbrett. That worked for me. :)
