### ISSUE TITLE
[Question] Should SNI be parsed early in a ClientHello callback à la OpenSSL?

### ISSUE THREAD

**Issue by space88man** [wolfSSL/wolfssl#7130]
### Version

master

### Description

OpenSSL recommends manually parsing SNI in the ClientHello callback and use `SSL_CTX_set_tlsext_servername_callback`  for acknowledgement only. This supersedes using only `SSL_CTX_set_tlsext_servername_callback` and foregoes helper functions like `SSL_get_servername` as they are not available during the ClientHello callback. The reason for the current recommendation is not entirely clear but is related to the order of parsing and that the SNI server callback happens quite late.

Does wolfSSL recommend the same method of parsing SNI ?

**Comment by anhu** [comment]
Hello @space88man , 

These APIs are part of our OpenSSL compatibility layer. We recommend that you use these APIs as they would be expected to be used if you were building against OpenSSL.  

Please let me know if you have any further questions. 

Warm regards, Anthony

**Comment by space88man** [comment]
Thanks @anhu : in my code I'm not expected to use the OpenSSL compatibility layer — what is the "correct" wolfSSL-way of doing SNI (and switching out the WOLFSSL_CTX *)?

> Hello @space88man ,
> 
> These APIs are part of our OpenSSL compatibility layer. We recommend that you use these APIs as they would be expected to be used if you were building against OpenSSL.
> 
> Please let me know if you have any further questions.
> 
> Warm regards, Anthony

**Comment by anhu** [comment]
I think I understand now, 
in `doc/dox_comments/header_files/ssl.h` please look up the following APIs: 

- `wolfSSL_UseSNI`
- `wolfSSL_CTX_UseSNI`
- `wolfSSL_SNI_SetOptions`
- `wolfSSL_CTX_SNI_SetOptions`
- `wolfSSL_SNI_GetFromBuffer`
- `wolfSSL_SNI_Status`
- `wolfSSL_SNI_GetRequest`

That file show examples for how to use each of these APIs. You can find further examples of how to use this APIs in `examples/server/server.c`, `examples/client/client.c` and `tests/api.c` .  I hope this helps!!

Warm regards, Anthony
