### ISSUE TITLE
[Question] Does wolfssl support grpc?

### ISSUE THREAD

**Issue by farazrbx** [wolfSSL/wolfssl#7174]
### Version

latest

### Description

I'm trying to compile grpc with wolfssl instead of openssl.
It is mentioned here that the OpenSSL compatibility layer should work with grpc. https://www.wolfssl.com/wolfssl-2021-annual-report/
But I get compile errors complaining about some undeclared identifiers.

```
/grpc/src/core/tsi/ssl_transport_security.cc:756:24: error: use of undeclared identifier 'X509_V_FLAG_PARTIAL_CHAIN'
                       X509_V_FLAG_PARTIAL_CHAIN | X509_V_FLAG_TRUSTED_FIRST);
                       ^
/grpc/src/core/tsi/ssl_transport_security.cc:756:52: error: use of undeclared identifier 'X509_V_FLAG_TRUSTED_FIRST'
                       X509_V_FLAG_PARTIAL_CHAIN | X509_V_FLAG_TRUSTED_FIRST);
                                                   ^
/grpc/src/core/tsi/ssl_transport_security.cc:895:30: error: use of undeclared identifier 'X509_STORE_CTX_get0_param'
  X509_VERIFY_PARAM* param = X509_STORE_CTX_get0_param(ctx);
```

**Comment by embhorn** [comment]
Hello @farazrbx 

The grpc project is listed as supported using wolfEngine, i.e. still using OpenSSL, but swapping out the cryptography layer for wolfCrypt using the wolfEngine project.

Are you interested in a native port of grpc using wolfSSL? Please send an email to facts@wolfssl.com for more information.

> [wolfEngine](https://github.com/wolfSSL/wolfEngine) (1 release)
wolfEngine made public on GitHub and first official release with version 0.9.0.
Allows users to achieve FIPS compliance with wolfCrypt FIPS + OpenSSL. Supports all algorithms in wolfSSL’s FIPS certificate (and others):
.
.
.
Integrates seamlessly with anything that uses OpenSSL, including:
...
grpc


Kind regards,
@embhorn
