### ISSUE TITLE
[Bug]: a potiential divide by zero exception

### ISSUE THREAD

**Issue by CR7-source** [wolfSSL/wolfssl#7349]
### Contact Details

a860641231@163.com

### Version

5.6.3

### Description

I have found a potential divide by zero vulnerability in the wolfSSL project and would like to report it to the maintainers. This vulnerability has the potential to cause unexpected application behavior, crashes.Can you please help me check it? Thank you for your effort and patience!
Below is the execution sequence of the program that may produce divide by zero vulnerability .
1. wolfssl-5.6.3-stable/examples/server/server.c ServerEchoData function: On line 409 ,variable **rx_time** and **tx_time** are defined to be 0.However they are used as the divisor on line 513 and 514. It it possible that **rx_time** and **tx_time** are still to be 0,leading to a divide by zero vulnerability .

![image](https://github.com/wolfSSL/wolfssl/assets/74168640/96e630ec-850e-4d4a-9229-3a8f638f1735)

**Comment by kareem-wolfssl** [comment]
Hi @CR7-source ,

Thanks for the report.  I've made a fix locally which you can find here: https://github.com/kareem-wolfssl/wolfssl/commit/4d4f4e3f30779d5cb62789e62eb1ac5d30e2879d
We are currently in a release cycle, I will get this fix PRd and merged once we've finished our release.
