### ISSUE TITLE
segmentation fault issue 

### ISSUE THREAD

**Issue by hajjihraf** [wolfSSL/wolfssl#751]
Hi, 
I encountered a segmentation fault issue in the API wc_Sha256Update.

the problem is observed only when separate IO static buffer is defined (WOLFMEM_IO_POOL or WOLFMEM_IO_POOL_FIXED)
attached are the "wolfServer.c", "wolfClient.c" and "user_settings.h" that I used in my testing .

[src.zip](https://github.com/wolfSSL/wolfssl/files/770754/src.zip)

Thanks,

**Comment by JacobBarthelmeh** [comment]
Thank you hajjiharaf for providing the example and bringing this to our attention. We will review the issue, and provide feedback.

Regards,
Jacob

**Comment by JacobBarthelmeh** [comment]
hajjiharaf,

As an update on this I was able to duplicate the behavior seen and have found the root cause. Pull request #771 was opened to fix it.

Regards,
Jacob

**Comment by hajjihraf** [comment]
Hi Jacob,

Thanks for the update :)

Best Regards,
Achraf
