### ISSUE TITLE
Ed25519 signature verification bug

### ISSUE THREAD

**Issue by iontra-shubham** [wolfSSL/wolfssl#7510]
Instead of "break;", it should be "return BAD_FUNC_ARG;"

If any of sig[i] is greater than 0x00 than  S is becomes larger than the order: 2^252 + 0x14def9dea2f79cd65812631a5cf5d3ed = 0x1000000000000000000000000000000014def9dea2f79cd65812631a5cf5d3ed. In that case verifications fails.

https://github.com/wolfSSL/wolfssl/blob/52861cbdbf8742673a6c14a76a00ba6550c14028/wolfcrypt/src/ed25519.c#L752

**Comment by dgarske** [comment]
Hi @iontra-shubham ,

Thank you for this report. We will review and respond shortly.

Thanks,
David Garske, wolfSSL
