### ISSUE TITLE
[Bug]: wc_Curve448PublicKeyToDer returns error when output is NULL

### ISSUE THREAD

**Issue by EugenCazacu** [wolfSSL/wolfssl#7516]
### Version

5.6.6

### Description

Configuration: all configurations including HAVE_CURVE448 and --enable-curve448

`wc_Curve448PublicKeyToDer` behaves differently from `wc_Curve448PrivateKeyToDer` when output is NULL. `wc_Curve448PrivateKeyToDer` returns the size needed by the  output and `wc_Curve448PublicKeyToDer` returns `BAD_FUNC_ARG`. I would expect both functions to behave similarly and ideally return the needed buffer size on a call with `output == NULL`

Suggested fix: output should not be checked for NULL in the implementation (similar with `wc_Curve448PrivateKeyToDer`)

### Reproduction steps

call wc_Curve448PublicKeyToDer with output == NULL

**Comment by julek-wolfssl** [comment]
Hi @EugenCazacu, thank you for the report. Please find a fix at https://github.com/wolfSSL/wolfssl/pull/7519.

Juliusz
