### ISSUE TITLE
Does wolfssl has an openssl equivalent of d2i_X509_AUX

### ISSUE THREAD

**Issue by alexsn** [wolfSSL/wolfssl#7801]
### Version

5.7.2

### Description

I'm migrating some openssl code to wolfssl, in openssl we use [d2i_X509_AUX](https://docs.openssl.org/master/man3/i2d_re_X509_tbs/) for which I couldn't find an equivalent is wolfssl?

Is there something similar I can use?

**Comment by kareem-wolfssl** [comment]
Hi @alexsn ,

For X509_AUX the only APIs we currently have are wolfSSL_PEM_read_bio_X509_AUX, which reads a PEM cert into an X509_AUX, and wolfSSL_PEM_write_bio_X509_AUX, which writes the X509_AUX into a PEM cert.  But in general, we don't currently support the extra information included in an X509_AUX so these APIs are just treating the struct as an X509 anyways.  I would recommend using wolfssl_d2i_X509.
