### ISSUE TITLE
[Bug]: DTLS fragmentation is broken

### ISSUE THREAD

**Issue by Frauschi** [wolfSSL/wolfssl#7825]
### Contact Details

tobias.frauenschlaeger@oth-regensburg.de

### Version

master

### Description

When enabling DTLS with fragmentation support, the unit tests fail. More specifically, the test `972: test_dtls_frag_ch` fails according to the `test-suite.log`.

### Reproduction steps

```
./configure --enable-all --enable-asn=template --enable-dtls13 --enable-dtls-frag-ch
make
make check
```

### Relevant log output

```shell
972: test_dtls_frag_ch                                   :
ERROR - tests/api.c line 83190 failed with:
    expected: wolfSSL_get_error(ssl_c, -1) == WOLFSSL_ERROR_WANT_READ
    result:   -328 != 2

 failed (  0.00295)
```

**Comment by julek-wolfssl** [comment]
Thank you @Frauschi for the report. The issue was that ECH and the ciphersuites were pushing the ClientHello message in the test over the fragmentation limit. https://github.com/wolfSSL/wolfssl/pull/7914 fixes this.
