### ISSUE TITLE
generate_documentation.sh - Check for executables only when needed

### ISSUE THREAD

**Issue by knight-of-ni** [wolfSSL/wolfssl#7857]
### Version

5.7.2

### Description

generate_documentation.sh checks for exectuables such as git, cmake, g++, etc in all cases, whether they are needed or not.

This is problematic in a package building environment (rpm in my case) as that requires one to pull in additional packages that aren't used.

A PR to resolve this is incoming...

Background:
I have a fedora package review request for wolfssl here:
https://bugzilla.redhat.com/show_bug.cgi?id=2302646

I expect it to be approved shortly.

Currently, I am patching out all the "command -v" statements so the script succeeds when _make dox-html_ is called during the build process. It would be nice if I didn't have to do this.

**Comment by embhorn** [comment]
Hi @knight-of-ni 

Thanks for recommending this improvement. I have requested a review by one of our engineers.
