### ISSUE TITLE
more portable shebang for Bash and Perl script

### ISSUE THREAD

**Issue by mpsuzuki** [wolfSSL/wolfssl#7878]
### Version

5.7.2 and later

### Description

Since #4941, all sh scripts are intentionally rewritten as Bash scripts, with "#!/bin/bash" shebang. As filed in #7244, most *BSD distributions do not place their prebuilt Bash in **/bin/bash** but in **/usr/local/bin/bash** (or **/usr/pkg/bin/bash**).

If the shebang is **#!/usr/bin/env bash**, the users on the systems with Bash (as far as PATH is configured appropriately) can execute the scripts without rewriting the shebang.

https://github.com/mpsuzuki/wolfssl-patch-dev/commit/893b498a75b24c9d5d2d62f0576593ba8711500a (for Bash) and https://github.com/mpsuzuki/wolfssl-patch-dev/commit/583c70e0433bd1d92101311d2a49f1df9820df8a (for Perl) are such changesets.

Such changesets are unacceptable? I guess such modification might have been discussed once, but I could not find.

**Comment by vifino** [comment]
Hi! As one of the maintainers of the wolfSSL package in NixOS, I'd also like to see this happen. It would remove a bit of patching on our end.
