### ISSUE TITLE
Build options

### ISSUE THREAD

**Issue by parsahatami98** [wolfSSL/wolfssl#7922]
Hello there
I am trying to build wolfssl to use with libz-ng , nginx ,wolfclu, xtls/xray-core , with tls1.2-1.3 also with dtls1.2-1.3 and post-quantum compability options in a debian based linux x86_64. What feature should i enable while building? I tried many times with no error in make check. But failing while installing wolfclu and nginx build after patching.
Please help and guide me
Thank you

**Comment by parsahatami98** [comment]
![Screenshot_2024-08-31-14-22-19-309_com.github.android.jpg](https://github.com/user-attachments/assets/9fe5dbf6-a461-4103-bd84-0c18d01a0213)

Xray core is a proxy to bypass China's GFW and also useful in Iran and Russia. If it is possible, please consider to add supporting it. With your libs i can assume it may be better than lightway core by Expressvpn.

**Comment by anhu** [comment]
Hi @parsahatami98 , 

Please have a look at https://github.com/wolfSSL/wolfssl-nginx?tab=readme-ov-file#post-quantum-algorithms and see if that is helpful.  Let me know if you have further problems. 

Warm regards, Anthony

**Comment by anhu** [comment]
By the way, can you please let us know about your project, goals and where you are located?

**Comment by anhu** [comment]
Hi, Any further questions?

**Comment by parsahatami98** [comment]
Hello
Yup i tried to build wolfssl with these options : all, experimental, kyber, liboqs, des3, oldnames, aescbc, aescbc-lenght-check, dtls3, dtls-frag-ch, dtlscid, hkdf, hkpe, srtp-kdf, sctp, x963kdf, libz path to zlib-ng, wolfclu, dual-alg-certs, smallcache, fastmatg, nginx, and harden and disabling oldtls
WolfClu showing error not finding wolfssl_P521_SABER_level5 , also not finding Kyber_90s and NTRU_HRSS and NTRU_HPS
And tried to modifying nginx quic in github VirtuBox/nginx-ee and installing nginx mainline and patching wolfssl-nginx after patching dynamic tls records in github kn007 , all unsuccessful and showed errors

**Comment by parsahatami98** [comment]
Project : making a vpn  for self use 
Goal : using other than usual libraries using Xtls/x-ray core that may work with openssl or as a reverse proxy using nginx
Location : somewhere in IRAN

**Comment by anhu** [comment]
Please open a ticket by sending a message to support@wolfssl.com .
