### ISSUE TITLE
[Bug]: `--enable-sp=yes,asm` causes crashes when AVX support is missing

### ISSUE THREAD

**Issue by vifino** [wolfSSL/wolfssl#7976]
### Contact Details

Here, on GitHub, preferrably.

### Version

5.7.2

### Description

Running HAProxy with wolfSSL configured with `enable-sp=yes,asm` causes HAProxy to coredump on startup if AVX/AVX2 is not supported.

The function tripping the coredump is `sp_256_get_point_33_avx2_4`.

Please make sure this is guarded by runtime detection of AVX/AVX2, like AES-NI.

### Reproduction steps

1. `--enable-haproxy --enable-quic --enable-reproducible-build --enable-bigcache --enable-sp=yes,asm --enable-sp-math-all --enable-harden --enable-intelasm --enable-aesni`
2. Run on CPU without AVX support (for example in VM)
3. Watch it coredump. :(

**Comment by SparkiDev** [comment]
Hi @vifino,

The code switches on the availability of BMI2 and ADX which in hardware is only available with AVX2.
But, since you have this issue, I have made a code change in a this PR: #7979.

Let me know if this works for you.

Sean
