### ISSUE TITLE
ER: Add crypto API for ChaCha20-Poly1305

### ISSUE THREAD

**Issue by aburks** [wolfSSL/wolfssl#8]
Add an API for the ChaCha20-Poly1305 AEAD as defined by https://tools.ietf.org/html/draft-irtf-cfrg-chacha20-poly1305.

**Comment by toddouska** [comment]
Thanks for the request.  We'll work on it this week.

**Comment by aburks** [comment]
I'll actually have a pull request for you tomorrow if you want to wait and have a look at that.

**Comment by aburks** [comment]
Added pull request #10 to fix this issue.

**Comment by toddouska** [comment]
Thanks for the pull request, merged.
