### ISSUE TITLE
[Bug]: Kyber (original) is not working

### ISSUE THREAD

**Issue by Frauschi** [wolfSSL/wolfssl#8023]
### Version

master

### Description

When compiling the WolfSSL version of Kyber with the Round 3 version enabled, tests are failing. The final FIPS version is working properly, however.

Failing configuration:
```
./configure --enable-all --enable-asn=template --enable-experimental --enable-kyber=yes,original
make
make check
```

Working configuration:
```
./configure --enable-all --enable-asn=template --enable-experimental --enable-kyber=yes
make
make check
```

**Comment by SparkiDev** [comment]
Hi @Frauschi,

I've put up a pull request that fixes the original algorithm.
Thanks for raising the bug!

Sean

**Comment by Frauschi** [comment]
Hi @SparkiDev,

I verified the patch on my side, it is working properly now. Thanks for the fast response!

Tobi
