### ISSUE TITLE
API/ABI changes review for wolfSSL

### ISSUE THREAD

**Issue by lvc** [wolfSSL/wolfssl#811]
The review of API/ABI changes for wolfSSL since 2.0.2 version: https://abi-laboratory.pro/tracker/timeline/wolfssl/

The report is updated 3 times a week (RSS: https://abi-laboratory.pro/tracker/rss/wolfssl/feed.rss). Hope it will be helpful for users and maintainers of the library.

Created with the help of open-source abi-tracker tool: https://github.com/lvc/abi-tracker

The tool checks _all_ API symbols declared in header files (doesn't take docs into account), so there may be some false positives.

Thank you.

![wolfssl-1](https://cloud.githubusercontent.com/assets/1517837/24135516/99ef8374-0e23-11e7-9146-64c39b10fdb4.png)

![wolfssl-2](https://cloud.githubusercontent.com/assets/1517837/24135518/9eeb6ca8-0e23-11e7-8a84-c56e4a6efc8e.png)

## Environment
* Linux x86_64
* GCC 4.9
* wolfSSL 2.0.2 and higher

**Comment by cconlon** [comment]
Hi!

Thanks for letting us know wolfSSL is being tracked on the abi-laboratory.pro site, and for setting it up!  We use the abi-tracker tool internally during our release cycle, but haven't had time to automate the process yet.  This will be very helpful!

When looking over the generated report (https://abi-laboratory.pro/tracker/timeline/wolfssl/), it looks like several of our GitHub releases/tags are skipped.  For example between the listed "3.9.3" and "3.10.3" tags, all of the following are missing from the report:

v3.9.10-stable
v3.9.10b
v3.10.0-stable
v3.10.0a
v3.10.2-stable

From the pattern, it seems that all tags ending in non-decimal numbers might currently be skipped?

As a thanks for getting this set up for us, I'd like to send some wolfSSL swag your way.  Can you email me your mailing address so we can ship a few things out to you?  You can reach me at chris (at) wolfssl (dot) com.

Thanks again!
Chris

**Comment by lvc** [comment]
Hi,

The report has been fixed: https://abi-laboratory.pro/tracker/timeline/wolfssl/

Thank you.

![wolfssl-3](https://cloud.githubusercontent.com/assets/1517837/24324954/2306c482-11a9-11e7-849d-86f66c33e2d1.png)

**Comment by cconlon** [comment]
Thanks for the fixes!

**Comment by dgarske** [comment]
@lvc, I am not sure if you are the right contact still, but the ABI tracker for wolfSSL does not have our Dec 23, 2020 release v4.6.0 listed. Is there a way we can fix that? Thanks, David Garske, wolfSSL

**Comment by linuxhw** [comment]
Fixed: https://abi-laboratory.pro/?view=timeline&l=wolfssl

Thank you.
