### ISSUE TITLE
[Bug]: wolfssl coexists does not support session callback

### ISSUE THREAD

**Issue by icing** [wolfSSL/wolfssl#8145]
### Contact Details

stefan.eissing@gmail.com

### Version

master

### Description

When building wolfSSL as described below, I adapted curl to link with both wolfSSL and openssl at the same time. Many thanks for that! The only feature that seems to be missing the the new session callback. That can be registered but is never invoked.

Looking at the source, the callback is only stored when opensslextra is configured, which we do not want in curl. 

Is there another configure option, I missed, or is this indeed missing?

Thanks for the help!

### Reproduction steps

1. `./configure --prefix=/path --enable-ip-alt-name --enable-quic --enable-earlydata --enable-psk --enable-opensslcoexist`

**Comment by douzzer** [comment]
@icing why aren't you just `--enable-opensslextra`ing to solve this?  There are no longer conflicts between `--enable-opensslextra` and `--enable-opensslcoexist`.  Give it a try?

**Comment by icing** [comment]
@douzzer won't that drag in OpenSSL symbols that will conflict with linking curl together with wolfssl and openssl *into the same* executable?

**Comment by douzzer** [comment]
@icing

>won't that drag in OpenSSL symbols that will conflict with linking curl together with wolfssl and openssl _into the same_ executable?

not anymore -- #8132 , merged on Friday, fixes all the name conflicts in `OPENSSL_EXTRA`.  you still can't use `OPENSSL_ALL` with `OPENSSL_COEXIST` though.  but as long as you omit `OPENSSL_ALL`, the library is now _always_ built with no symbol conflicts relative to OpenSSL.

>got a bit lost in the configure options jungle.

we've all been there!
