### ISSUE TITLE
Unable to override Certificate verfiy with wolfssl_set_verify callback

### ISSUE THREAD

**Issue by gonzzor** [wolfSSL/wolfssl#905]
The callback in wolfssl_set_verify is never called when a certificate fails a check, for example, the date. 

This worked before the release of 3.11.0.

The code at https://github.com/wolfSSL/wolfssl/blob/22ce2f183dc48a3074988891c66b041b0582b38d/src/internal.c#L7366 is supposed to make the error not fatal if there is a verifyCallback, but the code later in the same file https://github.com/wolfSSL/wolfssl/blob/22ce2f183dc48a3074988891c66b041b0582b38d/src/internal.c#L7510 will bail because err is still set if HAVE_OCSP isn't defined.

Further down in the same code
https://github.com/wolfSSL/wolfssl/blob/22ce2f183dc48a3074988891c66b041b0582b38d/src/internal.c#L7547
 the error "ret = DOMAIN_NAME_MISMATCH;" will go un-noticed as well. The variable ret will be overwritten before it's used. This will happen if the peer certificate is signed with a ECDSAk.

**Comment by dgarske** [comment]
Thanks for the detailed report. I can reproduce this issue as well and am working on a fix.
