### ISSUE TITLE
add wolfSSL to OSS-Fuzz

### ISSUE THREAD

**Issue by kcc** [wolfSSL/wolfssl#940]
Hello. 

OSS-Fuzz is an automated continuous fuzzing service for open source software. 
https://github.com/google/oss-fuzz
We already fuzz openss, boringssl, gnutls, botan, and nss there with [quite a few results](https://security.googleblog.com/2017/05/oss-fuzz-five-months-later-and.html)

* https://github.com/openssl/openssl/tree/master/fuzz
* https://github.com/google/boringssl/blob/master/FUZZING.md
* https://github.com/randombit/botan/tree/04da65d697dd0e967153cf0c24302107591a13f5/src/extra_tests/fuzzers/jigs
* https://gitlab.com/gnutls/gnutls/tree/master/devel/fuzz
* https://github.com/nss-dev/nss/tree/master/fuzz

We would like to see wolfSSL at OSS-Fuzz as well. 

AFIACT @nettrino has fuzzed wolfSSL manually (https://github.com/wolfSSL/wolfssl/commit/8fac3fffead13282f76e18cc18283e73c0d7dbbc, https://github.com/wolfSSL/wolfssl/commit/9c7bea46d24b4dab092adb299b2717ddee8e7a44, https://github.com/wolfSSL/wolfssl/commit/92e501c8e4d6138627be10b5d74bc7a41adc403d, https://github.com/wolfSSL/wolfssl/commit/2951e167b5d6922abce453bd0706314a5dab704f), but automated fuzzing could give more.

**Comment by levi-wolfssl** [comment]
Now that [PR #715](https://github.com/google/oss-fuzz/pull/715) has been merged into OSS-Fuzz, wolfSSL is now at OSS-Fuzz.
