### ISSUE TITLE
Documentation bugs for STRING_USER

### ISSUE THREAD

**Issue by neglect-yp** [wolfSSL/wolfssl#990]
This document, https://www.wolfssl.com/wolfSSL/Docs-wolfssl-manual-5-portability.html, requires us to define **XSTRING_USER** if we need. However, **STRING_USER** is used in source codes.

```
$ grep -r STRING_USER *
cyassl/ctaocrypt/settings.h:    #define STRING_USER
wolfssl/wolfcrypt/settings.h:    #define STRING_USER
wolfssl/wolfcrypt/settings.h:    #define STRING_USER
wolfssl/wolfcrypt/types.h:      #ifndef STRING_USER
```

```
$ grep -r XSTRING_USER *
```

**Comment by dgarske** [comment]
Thanks for the report of the `XSTRING_USER` typo in the user manual. This has been updated in our internal docs to `STRING_USER` and will be updated online during our next release cycle in the next few weeks.
